### ISSUE TITLE
SEP 6, 24, & 31: Allow source and destination account of funds to differ from the SEP-10 client account

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1039]
SEP-10 enables clients (or users) to use the same credentials to authenticate with any number of independent services. Put simply, SEP-10 is the 'Login with Google' of the Stellar ecosystem. The difference is that instead of your Google username and password to login, you use a transaction containing your Stellar account signed by your secret key.

However, SEP-10 does not directly contribute to the security of funds held by or transferred to and from the authenticated Stellar account. Rather, SEP-10 authentication only ensures the KYC and transaction information provided to the anchor cannot be altered by a malicious actor.

Despite this, there is an implicit assumption in SEP-6, 24, & 31 that the account authenticated via SEP-10 is either the source or destination account of funds sent on Stellar. There is no reason that must be the case, since a user who initiated a transaction should be able to alter the source or destination of funds if they use the login credentials for the account that initiated the transaction.

We should update SEP-6, 24, and 31 to clarify that using a source account or specifying a destination account different from the account authenticated via SEP-10 is acceptable.

This change primarily benefits users of custodial services, who cannot sign challenge transactions with the secret key of their account because they do not have access to it. With this change, a straightforward solution would be to self-custody a Stellar account and secret key used in SEP-10 authentication, while using the Stellar account managed by a third party as the source and destination of outgoing and incoming transactions, respectively.

**Comment by JakeUrban** [comment]
cc @leighmcculloch @tomerweller

**Comment by leighmcculloch** [comment]
> there is an implicit assumption in SEP-6, 24, & 31 that the account authenticated via SEP-10 is either the source or destination account of funds sent on Stellar. There is no reason that must be the case, since a user who initiated a transaction should be able to alter the source or destination of funds if they use the login credentials for the account that initiated the transaction.

I think there could be cases where this matters. It's common for money transfer services to want to know who exactly is sending and receiving and disallow sending/receiving to someone who isn't themselves. For example, I think Wise requires this. If a deposit/withdrawal occurs with the SEP-10 authenticated account the service knows that it is the individual authenticated that will be sending or receiving. They have no guarantees on who is sending or receiving if the sender/receiver can be any other account.

I otherwise think the observations that SEP-10 is really just "Login with Stellar" is spot on, it really is just an authentication scheme. I think we do need to evaluate if it matters if random accounts are used for sending/receiving though or if an anchor needs authentication. If they don't then I think the change is fine.

> This change primarily benefits users of custodial services, who cannot sign challenge transactions with the secret key of their account because they do not have access to it. With this change, a straightforward solution would be to self-custody a Stellar account and secret key used in SEP-10 authentication, while using the Stellar account managed by a third party as the source and destination of outgoing and incoming transactions, respectively.

You mention that the user will self-custody a Stellar account for authentication. How will that work with multiple devices? Will each device have a separate account for authentication? How will anchors reconcile them to be the same individual? There's a rise in complexity introducing self-custody accounts/keys in a custodial setup where they aren't otherwise needed.

Another approach is simply for the server to sign for the client. The client starts SEP-10, passes the challenge tx to the server, the server signs it and gives it back to the client.

Another approach is the custodial server talks directly to the anchor to do SEP-10 and provides the JWT to the client.

Both of these approaches assume that M addresses (muxed accounts) or G addresses+memos can be used as the authenticated account, such that user A who is authenticated has a JWT that can only be used with their account and it gives no access to user B's account.

@JakeUrban @tomerweller Thoughts?

**Comment by JakeUrban** [comment]
>  If a deposit/withdrawal occurs with the SEP-10 authenticated account the service knows that it is the individual authenticated that will be sending or receiving. They have no guarantees on who is sending or receiving if the sender/receiver can be any other account.

I had the same thoughts, but I think there are a few counterpoints. 

First, a user can send funds to another account once their funds have been on-ramped by the anchor. And in the withdrawal case, someone else with a Stellar account can send funds to the user withdrawing and authenticating via SEP-10. So the same flow can be accomplished even with the anchor's account restrictions.

And secondly, other crypto applications allow this functionality. Take Coinbase for example. You can buy XLM and then send it to another address without restrictions, you don't need to prove that you control the destination account. This is effectively the same flow, but with Coinbase's UI instead of the client-server API calls.

We could let anchors define their own policy on this topic, stating that anchor could return 400 if they don't want to support these requests.

> You mention that the user will self-custody a Stellar account for authentication. How will that work with multiple devices? Will each device have a separate account for authentication? How will anchors reconcile them to be the same individual?

When I say self-custody, I'm talking about the service that uses a custodian to hold their users' funds.

Lets take an example. Say MyWallet app custody's users funds using Fireblocks in Stellar account A, and MyWallet uses MyAnchor to on-ramp funds into A. MyWallet would use another Stellar public key B when authenticating with MyAnchor via SEP-10, and assign a memo and memo type to each of their users. 

Does that address your concerns?

> Another approach is simply for the server to sign for the client. The client starts SEP-10, passes the challenge tx to the server, the server signs it and gives it back to the client. Another approach is the custodial server talks directly to the anchor to do SEP-10 and provides the JWT to the client.

In both these approaches we'd have to get all custodians to support SEP-10 authentication, and I don't think thats a scalable model. When custodians add support for a blockchain, the core functionality they want to implement is sending and receiving for their accounts. Asking for SEP-10 support would be a unique ask.

**Comment by leighmcculloch** [comment]
> So the same flow can be accomplished even with the anchor's account restrictions.

The same flow can be accomplished with traditional finance money services too. I don't know if this is a problem, I'm highlighting that there could be and I'd be interested to know if the regulations any anchors need to follow will require some sort of confidence level auth provides, or if simply declaring "its my account" via a checkbox might be enough. I don't want to block this if you know this won't be a blocker.



> MyWallet would use another Stellar public key B when authenticating with MyAnchor via SEP-10, and assign a memo and memo type to each of their users.

Where is key B stored?

**Comment by JakeUrban** [comment]
> Where is key B stored?

MyWallet's own infrastructure.
