### ISSUE TITLE
SEP-38: Allow unauthenticated requests to non-`/quote` endpoints

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1086]
### What problem does your feature solve?

Anchors may want to allow unauthenticated clients to make requests to the `GET /prices` and `GET /price` endpoints. 

For example, client applications may want to show rates from multiple liquidity providers to a user, or simply display the exchange rates of an anchor's pairs before the user has indicated they want to start a transaction.

### What would you like to see?

Make SEP-10 authentication optional for the `GET /price` and `GET /prices` endpoints.

### What alternatives are there?

Leaving SEP-10 required for `GET /price` and `GET /prices`.

**Comment by JakeUrban** [comment]
@leighmcculloch, can you think of any reason why we shouldn't relax the authentication requirements for these endpoints?

**Comment by JakeUrban** [comment]
We can add flags to the `GET /info` response indicating if `GET /price` and `GET /prices` require authentication, just like SEP-6 does.

**Comment by leighmcculloch** [comment]
🤔 That's a good point. 

If I recall correctly we made the end points authenticated so that an anchor can provide rates unique to that user, but I can't think of a reason to not make the authentication optional with the obvious restriction that rates specific to that user can't be offered when the user isn't authentication.
