### ISSUE TITLE
SEP-12: Delete does not recommend to adhere to data retention policy of the regulators  of the applicable jurisdiction 

### ISSUE THREAD

**Issue by TravisG82** [stellar/stellar-protocol#1091]
the Current SEP-12 Recommends that once the Anchor  gets the delete request, it should go ahead and delete the customer information. However local regulations require that once must retain customer records for certain duration . To quote a few,  BAFIN in Germany and BSA in US and FINTRAC in Canada requires for AML reasons to log  records for minimum period of 5  years and not adhering to it could lead to fines.

**Comment by leighmcculloch** [comment]
@JakeUrban Do you have thoughts and insights on how this plays out in existing implementations?

My assumption is that deletion from the API would disable the capability to use that data any longer, but an implementation could still retain the information for as long as they were required by their jurisdiction.

**Comment by JakeUrban** [comment]
@leighmcculloch I'll bet that businesses are retaining user information to comply with regulations despite what our specification states. We should update the language to match what businesses may be legally obligated to do.

**Comment by TravisG82** [comment]
@JakeUrban , @leighmcculloch  .. thank you for looking into this. 

I would also agree that businesses who are already in this field with Fiat currencies should have been doing it however can never be 100% sure that they do it unless they confirm. However as a guideline it makes sense to provide them our recommendation to comply with local regulatory policy. 

To add further, i would propose  as a future enhancement that as a response , a note should be send back to the requester which informs them in the line of context  that
1. Customer record is archived and no longer an active one.
2. Customer Record will be permanently deleted post X period . 
 
Final wording of the response is up to each business to take up in their own legal wordings and language.

**Comment by JakeUrban** [comment]
We can add an optional `message` field to the response for this.

**Comment by TravisG82** [comment]
Shall then i go ahead and raise a PR ?

**Comment by leighmcculloch** [comment]
I think we can probably forego the comment in the response, as such information may be complex and difficult to provide succinctly. The system responding to the request may also not have the information at hand to provide it. There's a good chance information about how long information is held will be part of the terms of service of the anchor.

However, I think we could add some discussion about this to SEP-12. So that integrators know that deletion with the API doesn't necessarily mean deletion of the data entirely, it is really just preventing future use, and that anchors may hold onto information longer for a variety of reasons or regulations.

**Comment by leighmcculloch** [comment]
Please feel welcome to open a PR!
