### ISSUE TITLE
SEP-24: Withdraw transaction refund handling.

### ISSUE THREAD

**Issue by lijamie98** [stellar/stellar-protocol#1122]
It seems Plan-E is the clear consensus. 

#### Plan E: Add extra field `refund`

```
GET /transaction?id=xxx
{
    "id": "xxx",
    "kind": "withdrawal",
    "amount_in": 110, # amount of original transaction.
    ...,
    "status": "completed",
    // original stellar transaction ID
    stellar_transaction_id: "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020",
    "refunds": {
        "type": "partial",
        "amount_refunded": "10",
        "transactions": [
            {
                "amount": 10,  # amount refunded in stellar network
                "stellar_transaction_id": "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020"
            },
            {
                "amount": 15, # amount refunded in external network, if applicable.
                "external_transaction_id": "54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402"
            }
        ]
    }
}

```
---

### What problem does your feature solve?
In the withdraw process, the user may transfer the USDC to the anchor. However, the anchor may need to refund the transaction due to technical or business reasons. 

In that scenario, there are two Stellar network transactions but only one SEP-24 transaction. The wallet won't be able to see the "anchor-initiated" refund transactions. 

### What would you like to see?
The wallet should be able to see both the withdraw transaction and the "reverse" transaction.

The goal of this ticket is to choose one of the three alternatives (others are welcome) to propose a change for the refund process. 

### What alternatives are there?
There are three plans:

#### Plan A: Create a new value: `refund` ore `reverse` of the `kind` field.

In this plan, a new possible value, `refund` will be added to SEP-24. A new transaction schema will be added.

##### Pros: 
- New schema does not impact the existing `withdraw` and `deposit` transactions without overloading the meanings of the existing fields.
- First class citizen. Easier to maintain in the long run
- The wallet will be able to link multiple `refund` transactions with the existing `withdraw` or `deposit` transaction.

#### Cons:
- Impact to the existing wallet to interpret the `refund` kind.

The impact may be limited because for existing wallets working with existing anchor, the new `refund` kind has no impact. For wallets working with this new anchor, we can quickly implement. 

#### Plan B: Create a separate `deposit` transaction
The anchor can create a separate `deposit` transaction with the same amount of the `withdraw transaction. We may overload the `refunded` field to indicate a refund transaction. 

or use the `memo` field to indicate if this is a refund. 

##### Pros:
- Least impact to existing wallets.

##### Cons:
- The user may see `deposit` transaction not initiated from the wallet.
- The wallet won't be able to link both transactions together.

#### Plan C: Create a separate `deposit` transaction with `memo` 
The anchor may create a separate `deposit` transaction with a `memo` that links to the withdraw transaction.

##### Pros:
- Least impact to wallets.

##### Cons:
- Overloading the memo field may have impact with other functions.
- It is yet another protocol to between the anchor and the wallet to interpret the memo to link both transactions.

#### Plan D: Add extra field in the existing `transaction` schema
Add an extra field such as `sub_transactions` or `refund_transactions` to the Transaction schema to subsequent transactions related to the original one.

Example:
```
GET /transaction?id=xxx

{
    "id": "xxx",
    "kind": "withdrawal",
    "amount_in": 110,
    ...,
    status: "completed",
    // original stellar transaction ID
    stellar_transaction_id: "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020",
    sub_transactions: [
        {
            "type": "refund",
            "total_refunded": "10",
            // refund transaction ID
            "transaction_id": "54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402"
        },
       {
            "type": "future_type...",
           ...,
        }
       ]
}
```

##### Pros
- Non-breaking
- Can attach multiple subsequent transactions to the original one.

##### Cons
- TBD (cannot think of one at this moment)

#### Plan E: Add extra field `refund`
```
GET /transaction?id=xxx

{
    "id": "xxx",
    "kind": "withdrawal",
    "amount_in": 110, # amount of original transaction.
    ...,
    "status": "completed",
    // original stellar transaction ID
    stellar_transaction_id: "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020",
    "refunds": {
        "type": "partial",
        "amount_refunded": "25",
        "transactions": [
            {
                "amount": 10,  # amount refunded in stellar network
                "stellar_transaction_id": "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020"
            },
            {
                "amount": 15, # amount refunded in external network, if applicable.
                "external_transaction_id": "54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402"
            }
        ]
    }
}

```

**Comment by accordeiro** [comment]
@JakeUrban @leighmcculloch @CassioMG would love your thoughts here too.

**Comment by CassioMG** [comment]
**Plan A:** "The wallet will be able to link multiple `refund` transactions with the existing `withdraw` or `deposit` transaction."

@lijamie98 Just for clarity, how would the wallet link this refund transaction with other existing withdraw/deposit transactions?

**Comment by lijamie98** [comment]
Yes, we may add a `linked_transaction_id` or `original_transaction_id` field so that the wallet can easily link them together.

**Comment by accordeiro** [comment]
Interesting @JakeUrban, I like the non-disruptive approach. Do you see a problem with also including the `refund` object in the (all) `/transactions` endpoint in your proposal?

**Comment by accordeiro** [comment]
I'd imagine most wallets that don't support this would simply ignore the attribute. But of course this could cause some breakage - which is also true even if we only alter the `/transaction?id=<id>` endpoint

**Comment by lijamie98** [comment]
I can guess there may be transactions other than `refund` that may be attached to the original `transaction`. We may consider these as sub-transactions attached to the original one as this:

```
GET /transaction?id=xxx

{
    "id": "xxx",
    "kind": "withdrawal",
    "amount_in": 110,
    ...,
    status: "completed",
    // original stellar transaction ID
    stellar_transaction_id: "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020",
    sub_transactions: [
        {
            "type": "refund",
            "total_refunded": "10",
            // refund transaction ID
            "transaction_id": "54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402"
        },
       {
            "type": "future_type...",
           ...,
        }
       ]
}
```

**Comment by lijamie98** [comment]
Adding Plan D in the issue description.

**Comment by JakeUrban** [comment]
I like the idea of generalizing related transactions.

Another `type` of sub-transaction is the transaction needed to create the account if it doesn't exist.

**Comment by CassioMG** [comment]
> I can guess there may be transactions other than `refund` that may be attached to the original `transaction`. We may consider these as sub-transactions attached to the original one as this:
> 
> ```
> GET /transaction?id=xxx
> 
> {
>     "id": "xxx",
>     "kind": "withdrawal",
>     "amount_in": 110,
>     ...,
>     status: "completed",
>     // original stellar transaction ID
>     stellar_transaction_id: "b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020",
>     sub_transactions: [
>         {
>             "type": "refund",
>             "total_refunded": "10",
>             // refund transaction ID
>             "transaction_id": "54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402"
>         },
>        {
>             "type": "future_type...",
>            ...,
>         }
>        ]
> }
> ```

@lijamie98 this looks good! In this sample you posted, should the wallet expect a Sep-24 transaction to be found and returned by the Anchor once fetching `GET /transaction?stellar_transaction_id= 54321ab047a193c6fda1c47f5962cbcca8708d79b87089ababd57532c21c5402` ?

**Comment by lijamie98** [comment]
@CassioMG That's a good point. I would vote for a YES. Any concerns? 
@leighmcculloch @marcelosalloum @accordeiro @JakeUrban

**Comment by lijamie98** [comment]
This is blocking one of our anchors. Can I suggest that we go with PLAN-D?

**Comment by leighmcculloch** [comment]
I prefer the refund transactions that are explicitly denoted as such, outlined in https://github.com/stellar/stellar-protocol/issues/1122#issuecomment-1035494060. I think that is easier for an integrating developer to understand. It also gives us some freedom since the refund resource can contain refund specific fields, as is demonstrated where the example @JakeUrban shared has a total amount refunded explicitly shown.

What type of sub-transactions do we anticipate there being? And would it be clearer to make those their own resources as they are encountered?

**Comment by lijamie98** [comment]
> I prefer the refund transactions that are explicitly denoted as such, outlined in [#1122 (comment)](https://github.com/stellar/stellar-protocol/issues/1122#issuecomment-1035494060). I think that is easier for an integrating developer to understand. It also gives us some freedom since the refund resource can contain refund specific fields, as is demonstrated where the example @JakeUrban shared has a total amount refunded explicitly shown.
> 
> What type of sub-transactions do we anticipate there being? And would it be clearer to make those their own resources as they are encountered?

I think the `type:` field is consistent with the design of the SEP-24 transaction schema. It will be awkward if we have multiple refunds with different amount.

The type of sub-transactions are unknown at this moment. It serves as a placeholder for future types.

**Comment by leighmcculloch** [comment]
One thing that I think is confusing about the sub-transactions design is that the `total_refunded` is inside a single transaction. Is that total refunded for all refunds, or just a single tx? Would a developer just need to iterate over the list to find transactions that are refunds and add the values together?

**Comment by accordeiro** [comment]
Would we be able to hit `/transactions?id=xxx` using the nested transaction ids (like `/transaction?id= b9d0b2292c4e09e8eb22d036171491e87b8d2086bf8b265874c8d182cb9c9020`) on @leighmcculloch's example above? Or would that return a 404? If the latter, we should probably use a different name like `"refund_tx_ids"` so it doesn't seem like we're referring to the same `transaction` top level resource.

**Comment by leighmcculloch** [comment]
According to @JakeUrban's earlier comment the IDs are Stellar transaction hashes or external off-chain identifiers.

> ```js
> // for withdraw transactions, these are stellar transaction hashes
> // for deposit transactions, these are off-chain identifiers
> ```

**Comment by CassioMG** [comment]
> 

This is exactly what I was about to ask, and the answer is somewhat still unclear to me. I'll try exemplifying for clarification.

If I'm understanding correctly in this example that @JakeUrban [posted](https://github.com/stellar/stellar-protocol/issues/1122#issuecomment-1035494060) the user completed a withdrawal of amount `110` but then the Anchor partially refunded it with an amount of `10`, which appears as a payment transaction (of amount 10) on stellar network. Is that correct?

So, let's say the wallet gets this `stellar_tx_id_123` from this payment transaction of amount `10` (through horizon) and then try fetching more details from Anchor through `GET /transaction?stellar_transaction_id=stellar_tx_id_123`.

What should be the expected response here? Should the Anchor return the same Sep-24 transaction object as if the wallet were fetching the original withdrawal transaction?

I think it'd be great to get the same transaction object since the wallet could easily iterate over `refunds.transactions` to check if `stellar_tx_id_123` is there to discover if it's one of the refunds tx or the original one. Or even simply compare if `stellar_tx_id_123` is different than the original `"id"` ("xxx" in the example).

Does that make sense?

**Comment by lijamie98** [comment]
Updated the description by adding Plan E. 

When I first read about SEP, my felt traces of incremental changes and that sometimes confused me when I read it. That's why I kind of leaning towards a future proof design. But have something that's future proof can be disruptive and may have interest conflict with incremental design. 

Plan A, Plan D and Plan E represents three different directions. I don't have strong opinions on which one is better because they have pros and cons. 

@CassioMG I think people are leaning towards plan E. Once we decide on one of the plans, we can deep dive and confirm.

**Comment by marcelosalloum** [comment]
The question I'd like to answer first is how the wallet uses the `GET /transaction?key=val` endpoint? Where does the tx ID come from? When the wallet gets the tx ID, does it already know it's internal/external? Does it already know it's a refund?

If the wallet is uncertain about the transaction being internal/external, then we shouldn't overload the query parameters `?stellar_transaction_id={id}` or `?external_transaction_id={id}`.

If the wallet is not certain about it being a refund, then we shouldn't go with `GET /transaction?refund_tx_id={id}` either.

Thoughts?

**Comment by JakeUrban** [comment]
I vote for plan E. The sub-transactions idea is interested but I'd rather design for the known use case rather than generalize prematurely.

I agree with @marcelosalloum that we should not overload the `stellar_transaction_id` or `external_transaction_id` `GET /transaction` parameters.

I personally like the `refund_tx_id` parameter idea, but see Marcelo's point about the wallet not knowing whether or not it is a refund. The `contains_id` parameter argument is interesting, although it may require a heavy query or set of queries for the anchor who effectively has to search across multiple dimensions.

Before we choose to standardize something like `GET /transaction?contains_id=`, are we sure that wallet applications will need to fetch transaction records based on the refund ID? If I'm a wallet and I'm rendering a transaction history view, I'd think something like this is the most intuitive:

```
1. transaction A
2. transaction B (refunded)
3. transaction C
...
```

The user can then click on transaction B to get the refund info.

Are we thinking the wallet will do something like this? Showing the refund transaction as a distinct transaction?

```
1. transaction A
2. transaction B
3. transaction B refund
4. transaction C
```

**Comment by leighmcculloch** [comment]
>are we sure that wallet applications will need to fetch transaction records based on the refund ID?

This is a good point. Unclear. I think if we can limit the refund transactions to living inside the `refunds.transactions` list and not be a top-level transaction, that might keep the use simpler? If we say they are queryable via the /transactions endpoint, shouldn't they also show up in lists? That seems problematic for backwards compatibility.

**Comment by JakeUrban** [comment]
I agree @leighmcculloch, my preference would be to not support fetching transaction records by a refund ID.

**Comment by CassioMG** [comment]
> I vote for plan E. The sub-transactions idea is interesting but I'd rather design for the known use case rather than generalize prematurely.
> 
> I agree with @marcelosalloum that we should not overload the `stellar_transaction_id` or `external_transaction_id` `GET /transaction` parameters.
> 
> I personally like the `refund_tx_id` parameter idea, but see Marcelo's point about the wallet not knowing whether or not it is a refund. The `contains_id` parameter argument is interesting, although it may require a heavy query or set of queries for the anchor who effectively has to search across multiple dimensions.
> 
> Before we choose to standardize something like `GET /transaction?contains_id=`, are we sure that wallet applications will need to fetch transaction records based on the refund ID? If I'm a wallet and I'm rendering a transaction history view, I'd think something like this is the most intuitive:
> 
> ```
> 1. transaction A
> 2. transaction B (refunded)
> 3. transaction C
> ...
> ```
> 
> The user can then click on transaction B to get the refund info.
> 
> Are we thinking the wallet will do something like this? Showing the refund transaction as a distinct transaction?
> 
> ```
> 1. transaction A
> 2. transaction B
> 3. transaction B refund
> 4. transaction C
> ```

I have this scenario in mind: let's say a stellar wallet app has a History section in which it'd like to display all transactions that happened for this user in the stellar network. In this case the refund transaction would appear like the below since by the end of the day it's a new payment transaction from the Anchor to the user:
```
1. transaction A
2. transaction B
3. transaction B (*refund)
4. transaction C
```

In case we can't use the refunded tx id to `GET /transaction` to display more info about this refund transaction to the user then the wallet would have to make some heavy lifting on the frontend to fetch all transactions (`GET /transactions`) from each Anchor to search across all of Sep-24 transactions to discover if any of those stellar transactions is a refund transaction.

I have 2 suggestions in which we could split this heavy lifting between Anchor & Wallet:

A) - Allow `GET /transaction?refund_tx_id=` (instead of the heavy `contains_id=`) so that it could work like this for wallets:
1.  Wallet displays all stellar network transactions listed in History page
2. User taps on a History item
3. Wallet tries fetching more info using `GET /transaction?stellar_transaction_id=`
4. In case `3.` gets a 404 then wallet could retry using `GET /transaction?refund_transaction_id=`
5. In case `4.` succeeds then this means it's a refund transaction and wallet is able to show more info
^ Making the user await for a retry doesn't seem like a big issue in this case since refunds should rarely happen

B) - Allow something like `GET /refunds` or `GET /transactions?refunds_only=true` so that wallets could easily fetch all refund transactions from an Anchor `beforehand` in order to detect if a stellar network payment is a refund tx or not when showing it on History page (again, since refunds should rarely happen this fetching should return a list of only a few refund transactions which could be quickly mapped on the frontend)

I also like **plan E**, I think the biggest question is whether Anchors should support directly querying refund transactions or not. I think they should somehow provide that, specially considering a refund could happen in any point in time (like it could happen the day after, the month after, or the year after) so wallets won't be sure in which timeframe they should be looking at considering the scenario I mentioned.

How does that sound?

**Comment by JakeUrban** [comment]
> let's say a stellar wallet app has a History section in which it'd like to display all transactions that happened for this user in the stellar network

🤔  I see your point. If you're using the Stellar Network as your source of data (transaction IDs), then you wouldn't be able to quickly look up the SEP-related transaction data from the anchor. This is assuming that you know that the particular transaction ID on the stellar network relates to a specific anchor's SEP service though.

I'm not against a `refund_tx_id` parameter, but unless we have a concrete use case (i.e. Vibrant) that wants this functionality, I would suggest that we wait and see what the demand is from the ecosystem.

**Comment by lijamie98** [comment]
I had updated the description for Plan-E is the clear consensus.

**Comment by CassioMG** [comment]
> 🤔 I see your point. If you're using the Stellar Network as your source of data (transaction IDs), then you wouldn't be able to quickly look up the SEP-related transaction data from the anchor. This is assuming that you know that the particular transaction ID on the stellar network relates to a specific anchor's SEP service though.
You are right, the wallet wouldn't need to fetch all transactions from all anchors but instead all transactions related to this specific Anchor which sent this payment.

> I'm not against a `refund_tx_id` parameter, but unless we have a concrete use case (i.e. Vibrant) that wants this functionality, I would suggest that we wait and see what the demand is from the ecosystem.
Makes sense, maybe before going deeper into this we could check with the Anchor how they feel about supporting a `refund_tx_id` parameter. What do you think?

**Comment by JakeUrban** [comment]
Sounds like a plan to me. I'll start drafting the PR 👍

**Comment by lijamie98** [comment]
> Sounds like a plan to me. I'll start drafting the PR 👍

Thanks @JakeUrban !
