### ISSUE TITLE
StellarTokenLists - list of tokens and their associated Anchors

### ISSUE THREAD

**Issue by antb123** [stellar/stellar-protocol#1126]
### What problem does your feature solve?

Currently anchors are tied one to one to an issuer. For some tokens such as USDC there are multiple Anchors available however they are hard coded in the wallets.

### What would you like to see?

A one to many type supported via a new json token list format. This list could also be used to filter out spam tokens. 

The format could be based on the existing format proposed by uniswap and described on tokenlists.org. From the Ethereum website "Token Lists is a community-led initiative to improve discoverability, reputation and trust in ERC20 token lists in a manner that is inclusive, transparent, and decentralized."

This will help in both token and anchor discoverability and improves the user experience. Each wallet or stellar.expert could support multiple lists and allow the users to filter according to their preferences.

### What alternatives are there?
Hard code lists of anchors into apps like what is currently done in Stellarterm, stellarx and lobstr and others.

```
{
    "name": "KB Trading Test List",
    "timestamp": "2021-12-09T21:17:44.251Z",
    "version": {
        "major": 4,
        "minor": 1,
        "patch": 6
    },
    "tokens": [
        {
            "logoURI": "https://ntokens.com/img/brl-icon.png",
            "issuer": "GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP",
            "name": "Brazilian Real",
            "code": "BRL",
            "decimals": 2,
            "anchors": [
                "ntokens.com",
                "kbtrading.org"
            ]
        },
        {
            "logoURI": "https://www.centre.io/images/usdc/usdc-icon-86074d9d49.png",
            "issuer": "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
            "name": "USD Coin",
            "code": "USDC",
            "decimals": 2,
            "anchors": [
                "usdcswap.io",
                "polaris.stably.io",
                "aqilpay.com)"
            ]
        }
    ]
}

```

Each of these anchors should have a stellar toml file corresponding to SEP-001 in the .well-known directory.

### References
(1) [https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md)
(2) [https://tokenlists.org/](https://tokenlists.org/)
(3) [Old stellarterm json format](https://github.com/stellarterm/stellarterm-directory/blob/add-ultrastellar/static/anchors.json)

**Comment by yuriescl** [comment]
This is really necessary at the moment. The community could have many lists available, each list would have a list of tokens and their respective anchors. Right now it's difficult to differentiate between legitimate (which have real value in the world) and fake tokens, since apparently the main source of information about the market is StellarExpert, and there are many fake tokens ranked high in their list.

For example, Lobstr could have its own list, and the community could trust Lobstr that all tokens and anchors in its list are reliable, since Lobstr made the list.
Anyone could build a list and make it publicly available.

Wallets could offer an option for the user to choose which token list to use, and then only the tokens/anchors in that list would be available to use in the wallet, this will increase security for the user and prevent deposits and withdrawals to fake tokens.
StellarExpert could also support these lists and allow the user to choose the list, then, the rankings would only show the tokens in that list, removing the fake tokens from the rankings :)

**Comment by leighmcculloch** [comment]
@antb123 Is this something like what you're looking for?

https://resources.stellar.org/anchors

Or you're looking for something like this but specifically an API?

cc @zacf

**Comment by yuriescl** [comment]
> https://resources.stellar.org/anchors

Thanks for sharing, I didn't know about this webpage, it's very useful.
Anthony have shared some details about the idea with me and I think the basic idea is to have something loadable into any wallet.
The popular wallets like Lobstr, Solar, usually recommend assets to their users, but this feature is specific to those wallets.
It would be interesting to have a standard in which any wallet could load a list of assets and display as "trusted" or "recommended". This helps preventing users from adding ("establishing trustline to") fake tokens and depositing/withdrawing to fake tokens.

Scenario we're trying to **avoid:**
Joe tells Bill about Stellar and Bill downloads Solar wallet. Bill is clueless about assets, issuers, anchors, etc. Bill heard that Stellar.Expert is a good place to look for assets. Bill sees many assets in Stellar.Expert and adds a lot of them, thinking they're all legitimate and carry real value. Bill deposits $1000 into a fake token (ex: USDC but issued by a illegitimate anchor), but then realizes he can't trade or withdrawal to any other currency since the fake token is a scam. Bill feels bad and uninstalls Solar wallet and never goes back to use Stellar again.

Scenario we're trying to **achieve:**
Joe tells Bill about Stellar and Bill downloads Solar wallet. Solar wallet loads a list of trusted assets from Lobstr by downloading a "token list", as described previously in this discussion. Now Bill can add any token without leaving the wallet, and can trust the wallet that the tokens are legit. Bill can also choose another token list from another source to see other assets. The legitimacy of the token list relies on the legitimacy of who made the token list.

The concept of token lists is already present in other popular chains like Ethereum.
See https://tokenlists.org/

**Comment by yuriescl** [comment]
I've lost count of how many times I had to warn someone about the illegitimate tokens.
Also, one of the first solutions that may come into mind regarging that is for wallets to only suggest/display tokens that are trusted.
But what if there's a new token with a lot of potential, but the developer of the wallet doesn't know about it? This would require all wallets to always keep track of assets, which doesn't seem ideal.
It's easier to just trust a list, the list updates over time and the user knows who made the list.
