### ISSUE TITLE
SEP-12: Use 404 HTTP status code when endpoint isn't supported

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1136]
SEP-12 `POST /customer/files` and `POST /customer/callback` endpoints are optional for anchors who want or need to support it.

We should mention in the SEP that anchors should ideally return 501 Not Implemented if requests are made to this endpoint.

**Comment by leighmcculloch** [comment]
My understanding is the HTTP 501 response code is specifically for indicating if the HTTP method is not implemented. E.g. You might get this if you use a DELETE or a POST when only GET is supported. In reality I don't think 501 gets used much as most folks seem to use 405.

This isn't to say we can't use 501 since it semantically seems to overlap with the use case you describe. However, I wonder if there will be oddities for any http clients that maybe don't expect this error code or won't handle it well.

Returning a 404 could also be appropriate since the resources are not supported the resources don't exist.

I don't yet feel strongly one way of the other.

**Comment by JakeUrban** [comment]
Good points @leighmcculloch, I think as long as we have the behavior defined, the specific HTTP codes used are secondary. Once I have more time to think about this a bit more I can come back to this issue and continue discussion.

**Comment by JakeUrban** [comment]
Hi Leigh, I'm making a change to SEP-31 that requires this same functionality (returning an error code if the endpoint isn't supported) and after reading the HTTP status code definitions, I think 404 is the correct status.

Both 501 and 405 refer to "request methods" and make specific examples to methods such as GET and HEAD. 404 is the only status code that focuses instead on the "resource" URI.

When I come back around to this issue for the purposes of SEP-12, I will use 404.

**Comment by leighmcculloch** [comment]
👍🏻
