### ISSUE TITLE
A new approach to deposit/withdrawal process (SEP-0006)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-protocol#115]
During my review of #106  I started questioning whether the approach we've taken to deposit/withdrawal servers in the first version of [SEP-0006](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md) and proposal in #106 is a good approach.

Here's a list of a few scenarios that will be hard/impossible to implement using the current protocol:
* Many companies are doing their KYC checks by asking for a webcam photo and/or a scan of user's ID or passport. I've experienced this at Coins.ph, Poloniex and GDAX. How would you send a file or request a webcam access? It's a bunch of new code/things to standardize in SEP. It will cause a bunch of issues (different formats, code needed to write in mobile apps to access webcam/file system).
* Fields required for KYC can have many different formats, ex date. It would be great to send these information back to the app doing a deposit to make typing on mobile easier (ex. for date we could show a calendar widget). However it's a protocol extension and, again, a lot of code to implement this properly. Processing errors and reporting them to user will be a hell.
* I'm pretty sure that some companies will want to open a new account for users who want to deposit money, ask them to read Terms of Use (especially after GDPR). Hard to ensure that apps implementing SEP-0006 do their job and show these documents to users. It would be also great to allow users to login using their existing account (FB/Google/maybe bank account - see PSD2 directive in European Union).

What I'm trying to show here is that protocol we invent today may become useless because of the things we didn't consider as needed, new regulations, etc. Even updating it every once in a while will require anchors and app developers to update their code, we will end up with a lot of breaking changes and, in the end, incompatibilities.

I think we should simplify this protocol as much as possible and move the whole user interaction part to the anchor. Anchor can show their web application endpoint (in a browser widget in mobile app or a popup in web app) collecting the data they need. After successful/failed processing on the anchor side the result is sent back to the app. Here's a simple sequence diagram:

![screen shot 2018-05-15 at 13 54 39](https://user-images.githubusercontent.com/464938/40055245-8df7483a-5847-11e8-9a8c-0eb7fce10d4a.png)

The flow is as follows:
1. User requests deposit/withdrawal in mobile app.
2. Mobile app gets the URL of the form to display to user (stellar.toml + asset information).
3. Mobile app displays a popup with a web app in anchor's domain.
4. User fills the form, KYC checks (this will be HTML/JS page so can access file system/webcam easily) and submits a form. In case of errors, the user is redirected by to the form to fix them.
5. The result is sent back to the mobile app. Essentially it can be either:
   * Deposit/withdrawal process has been started successfully.
   * Failure (user cancelled the process, bad API request, internal server error).
6. The result is displayed to the user.

We end up with a very simple protocol. The communication between mobile/web app and anchor is required only to find the URL to display to the user and report result back.

Here are the advantages of using a web app to process the request:
* All required fields, error reporting etc is done within anchor's application so there's no need to develop the code responsible for displaying/processing a form in web/mobile wallets and it's super simple for anchors because it's just a web app (HTML/JS + backend code).
* User can create an account using FB/Google or by connecting their bank account/Android Pay/Google Pay accounts.
* User can create a deposit transfer right away using PayPal or their bank account API.
* User can use autofill option in the browser. Very helpful especially on mobile.

If it's designed correctly it's possible that we will never have to extend the protocol ex. to support new fields etc.

Of course it's just an overview, if we agree to build something like this we will standardize requests and callbacks format.

**Comment by tomquisel** [comment]
@bartekn I love it!

Some thoughts:

1. What are your thoughts for communicating status back to the web/mobile app? Perhaps there's a status URL that can be embedded in an iframe?
1. The ability to view past transactions and status of current transactions with the anchor in a wallet / trading app seems valuable. I think this can be solved with the `/transactions` endpoint we already have, but there's an unaddressed issue of authentication. If we want to commit to the idea that the transaction history for any account with an issuer is public, then `/transactions` will do the trick. Otherwise, there may need to be some kind of popup / iframe approach for transaction history as well. However, the iframe approach does not allow the wallet to organize transactions across all issuers in a single time-ordered list, which is desirable. What are your thoughts on those options?

**Comment by s-a-y** [comment]
I generally like the idea, very easy for web users indeed.

We might need to keep an option to have JSON-based data exchange for other potential use-cases that don't necessarily have ability to show browser to the user:
- my messenger bot (can link to webpage, but bad user experience)
- SMS/USSD based interface
- Smart TV or Alexa
- maybe some embedded devices and/or robots without user control

Looks like for these cases instead of trying to parse page using phantom-js or similar we need some way to exchange data in a more or less standard way.

**Comment by bartekn** [comment]
> What are your thoughts for communicating status back to the web/mobile app? Perhaps there's a status URL that can be embedded in an iframe?

Web is simple, it can be just HTTP callback endpoint or [`postmessage`](https://caniuse.com/#search=postmessage) in JS (for popups).

On [Android](https://developer.android.com/guide/webapps/webview#HandlingNavigation) you can notify your app on URL change to the specific domain and then parse GET params. There's a way to [connect JS code to Android](https://developer.android.com/guide/webapps/webview#BindingJavaScript) but it looks like it's not super secure if you load domains you don't control.

However I developed maybe 2 simple mobile apps in the past and it was a very long time ago 😉. Would be great to have mobile developers contribute to the discussion here. If it doesn't work we still need some ways to return status to bots (as @s-a-y said):
* HTTP status receiver - when anchor wants to send a status it sends a HTTP request to URL provided by app developer in deposit/withdraw request. There are many platforms that help with message passing / message queues for mobile devs (AWS / [iron.io](https://www.iron.io/)?).
* Simple one: just move the user to deposits/withdrawals list right away so when they end the process they already see a status. After successful and failed transfers, they should appear as processing/done. For simple errors like bad request/signatures etc. we can make anchors to display them for 1 hour and then they can disappear.

> The ability to view past transactions and status of current transactions with the anchor in a wallet / trading app seems valuable. I think this can be solved with the `/transactions`.

Yeah, I think `/transactions` endpoint should stay as it was (or similar).

> We might need to keep an option to have JSON-based data exchange for other potential use-cases that don't necessarily have ability to show browser to the user.

But it means we're back to the old protocol with problems we wanted to solve. I agree that we need some way to talk with bots/SMS (I think that displaying a link to open in a browser and then using one of the methods above to get the status back are OK) but I think maybe 1% of users will ever deposit money by Smart TV or Alexa. It seems better to drop support for them and have simpler protocol for 99% of use cases.

> maybe some embedded devices and/or robots without user control

I'd say that deposit/withdrawals are _human-required_ protocols rather than _machine_ protocols like [SEP-0003](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0003.md). By _human-required protocol_ I mean human interaction is required to complete the action **during** the process (ex. they need to login to PayPay/bank account, register/login to anchor service, read docs, take a photo for KYC etc.). Whereas _machine protocols_ are only **initiated** by humans and then machines talk to each other. So I think we don't have to support robots here.

**Comment by s-a-y** [comment]
> It seems better to drop support for them and have simpler protocol for 99% of use cases.

I'm fine with that, just looking at all options.

> I'd say that deposit/withdrawals are human-required protocols rather than machine protocols like SEP-0003. By human-required protocol I mean human interaction is required to complete the action during the process (ex. they need to login to PayPay/bank account, register/login to anchor service, read docs, take a photo for KYC etc.). Whereas machine protocols are only initiated by humans and then machines talk to each other. So I think we don't have to support robots here.

ok, no bitcoin-paying fridges then. It does look different, so it can very well be a separate protocol developed when there is a demand.

**Comment by tomquisel** [comment]
After thinking about this, I think the best approach is to be backwards compatible, and enable human-free deposits and withdrawals at least in simple cases.

I'd suggest leaving [SEP6](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md) as it is, with one additional response field for the deposit and withdrawal endpoints. The field would be `issuer_form_url`, and it would kick off the popup and the flow you suggested above, @bartekn.

At the end of the form flow, there are at least two options:

1. deposit/withdrawal info is sent back to the wallet either with `postmessage` or an HTTP callback.
2. the form flow can just display the deposit/withdrawal info at the end, but then we lose the ability for the wallet to execute the withdrawal seamlessly. The user would need to manually copy the recipient address and memo from the popup to the wallet when withdrawing.

**Comment by istrau2** [comment]
@tomquisel I see. Well in that case, why do we need the popup to communicate the instructions to the calling application?

Perhaps a simpler flow is:
1. Hit `/deposit` or `/withdrawal`
2. Server returns instructions or `issuer_form_url`
3. After popup closes, client can hit `/deposit` or `/withdrawal` again and see if there are instructions (if there are then it means the user successfully created instructions and if not then they didn't.

The only issue here is what if the anchor wants to offer some kind of integrated deposit via the form? In other words, the form doesn't simply create instructions, rather it actually initiates a deposit. In that case, the client needs to call it every time a user wants to deposit regardless of whether or not instructions exist... (just thinking out loud here)

**Comment by istrau2** [comment]
> I think to initiate a deposit, a user will need to execute an external transaction (submit a BTC payment, initiate a bank account transfer) that will require secret credentials the anchor should not know.
Unless the anchor is the bank itself... or a bitcoin wallet... I think this SEP needs to allow for integrated deposit workflows. How about if we leave it up to the anchor. The client simply shows the user the instructions if they are returned by `/deposit` and doesn't if there are no instructions (i.e. it still returns `issuer_form_url`)

> And for withdrawals, they'll start with a Stellar transaction, which the wallet can handle most easily outside of the anchor.
Not necessarily, what about KYC (i.e. a user bought this asset on the DEX and now wants to withdraw)? What if a bank wants to offer an integrated withdrawal workflow? I think we need to allow for the same thing on withdrawals (i.e. `issuer_form_url` or deposit instructions returned from `/federation`

**Comment by tomquisel** [comment]
I've done some more thinking on this, and it's clear that KYC is going to become more and more common. If a user wants to hold, deposit, or withdraw many tokens, going through manual KYC for each token will quickly become burdensome. The burden is especially high with `auth_required` tokens for which a user must KYC even to hold the token.

A solution to this is to have the user's wallet hold onto their KYC info, and (after user confirmation) automatically transmit it to the issuer when a user wants to interact with the issuer's token. To make this practical, there needs to be a protocol that defines a standardized list of possible fields that can be transmitted. As @bartekn points out, there are so many possible fields and use cases that we can't hope to capture them all, but we can make an effort to support the most common cases.

Given this, we end up with three different ways for a wallet & issuer to interact:

1. Via the existing SEP6 protocol and its very limited fields
1. Via a new SEP6 extension that adds a standard list of KYC fields
1. Via a custom human-in-the-loop flow specified in the `issuer_form_url` we've been discussing

The new automated method with KYC fields can function along the lines of @istrau2's `/form` endpoint #106 and the proposed `/kyc` endpoint #103. It should accommodate both KYC fields and non-KYC fields, such as those needed for bank withdrawals. It should also specify the needed fields dynamically like in #106 rather than statically in the `stellar.toml` file.

Here are some use cases we'll want handle with the standardized field list:

* KYC (both US and international)
* Bank transfers in the US, Asia, and other key markets

What other use cases seem important to be able to handle automatically?

**Comment by tomquisel** [comment]
@s-a-y Yep, it looks final! I'll submit a PR for SEP6 this week.

**Comment by istrau2** [comment]
@tomquisel I don't like the idea of having hardcoded KYC fields. Everyone does it differently. I think we should use the `/form` workflow. Do you want me to try and modify my PR with some of this or were you going to submit a new PR?

**Comment by tomquisel** [comment]
I agree with you about that @istrau2. I'm putting together a new PR, and the plan is to have the `/deposit` and `/withdrawal` endpoints respond with an error message that lists the missing fields. They can then be submitted to a new `/customer` endpoint. What do you think?

**Comment by istrau2** [comment]
@tomquisel Yes, that sounds right to me.

**Comment by jedmccaleb** [comment]
incorporated into #136
