### ISSUE TITLE
SEP-31: remove option of making a transaction using **indicative** quotes

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/stellar-protocol#1172]
### What

Remove the option of making a transaction using **indicative** quotes. If quotes are to be used we should go with firm quotes only.

### Why

Indicative quotes are good to give a sense of the market price but it sounds non-realistic if the Sending Anchor sends the money to the Receiving Anchor without knowing the conversion price in advance.

This flow also adds quite a lot of complexity to the implementation and it could be avoided/simplified if we used indicative just for consultation and firm quotes for the actual conversion.

Affected SEPs

* SEP-31
* SEP-38
* SEP-6 (likely)

**Comment by marcelosalloum** [comment]
Cc @leighmcculloch, @JakeUrban, @lijamie98, @reecexlm

**Comment by JakeUrban** [comment]
Can you describe the additional complexity that would be added to the system in order to support indicative quotes?

I'm extremely hesitant to remove this option from the protocol for technical implementation reasons. Even if the use of indicative quotes in transactions is uncommon in practice, those who want to use it should be able to.

If an anchor doesn't need to support using indicative quotes in transactions (because none of their senders want it), they can choose to return 400 for those `POST /transactions` requests.

Regarding our specific implementation in the Anchor Platform, we can reach out to our pilot partners and their SEP-31 senders to see if we can leave support for indicative quotes in transactions out of the MVP.

**Comment by JakeUrban** [comment]
@marcelosalloum can we close this issue now that we've decided to continue supporting indicative quotes?

**Comment by marcelosalloum** [comment]
Closing this issue since we've decided to continue supporting indicative quotes.
