### ISSUE TITLE
Transfer SEPs (6, 24, 31): Using muxed accounts for receipt of payments

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1271]
Right now, the SEPs require that the anchor receiving a payment (ex. an anchor facilitating a SEP-6 withdrawal) specify a Stellar account (`G...`) and a memo for the client to use when submitting the payment transaction.

However, its completely possible for the anchor to encode the per-transaction memo in the Stellar account address, generating a muxed account, and instructing the client to send to the muxed account address.

The question, is this something we want to support? It might reduce the implementation complexity because anchors and clients don't have to handle memos. 

However, it would be a breaking change in the sense that existing clients would have to update their payment logic to expect the omission of a memo and the presense of a muxed account.

cc @nikita-gorodeckij

**Comment by JakeUrban** [comment]
Personally, I don't know if the benefit of supporting this use case outweighs the cost of requiring clients to update their implementations. But I wanted to bring up the topic for discussion. @nikita-gorodeckij, can you elaborate on your use case? Why use muxed accounts for this?

**Comment by marcelosalloum** [comment]
I like the idea of supporting muxed accounts since this is already fully supported by the network and the SDKs.

Since the support is native to the ecosystem, wallets should be able to support it without much effort. Also, memos are tied to transactions while muxed accounts can be tied directly to Payments (or other operations), which allows an Anchor to fulfill many SEP-31 flows (or many SEP-6 flows) in a single Stellar transaction.

**Comment by marcelosalloum** [comment]
I can even think of use cases where SEP-31 can accept both Muxed account + memo at once, where we can include two types of extra information – in the memo and in the Muxed account – when submitting the payment to the network.
