### ISSUE TITLE
CAP-0054: Move signing domain?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1288]
Related to https://discord.com/channels/897514728459468821/935999748840751125/1004049166944718960, in which @leighmcculloch suggested

> Prepend or append the signing domain, rather than inserting it into the middle of the message. This will simplifying verifying signatures in applications that do not need to know the structure of the internal message.

**Comment by jonjove** [comment]
@leighmcculloch can you elaborate on what you mean here? Do you mean that the `domain` should move in the definition of `MessageV0`? Or do you mean that the signature should appear at a different point in the argument list of a contract function? Or something else entirely?

**Comment by leighmcculloch** [comment]
Using the token contracts `MessageV0` as the basis for this discussion:
<img width="246" alt="Screen Shot 2022-08-08 at 3 12 16 PM" src="https://user-images.githubusercontent.com/351529/183523514-d1016278-cb1b-403f-a18a-e1a41fece719.png">


I think we should separate the domain from the actual request data that the developer hopes to sign. There are probably a variety of ways to do this though. I can speak to one way, but it isn't the only way we could do this.

In many cases the domain can be constructed as some general mechanics in building a request, and if it is prepended to the request, it is easier to shift it to some general auth implementation in the SDK, independent of custom request messages. If it is prepended to the binary to sign it is also easier for something like the CLI to implement this auth approach, because the CLI can take all the arguments, encode them, prepend the domain which is automatically determined, then sign the entire message.

The reason I suggest moving it out of MessageV0 is because of Map ordering there's no guarantee it wouldn't end up somewhere in the message, so it is difficult to encode the request independently of the domain that needs prepending.

Sort of related, the domain needs to be more than an enum it is today, and more than the function name that it is likely to contain tomorrow (https://github.com/stellar/soroban-token-contract/issues/81). We could probably make this `Binary` accessible via a host function that automatically defines it as some XDR structure that contains:
- network passphrase
- contract id
- contract fn

And, we could make a verify SDK function that automatically prepends these things.

None of this would restrict developers doing something different if they needed.

**Comment by leighmcculloch** [comment]
The above also relates to why I suggest moving the nonce into the explicit function parameters (https://github.com/stellar/stellar-protocol/issues/1287). If we do both of these things the message being signed is simplified into:
```rust
#[contracttype]
pub struct MessageV0 {
    pub domain: Binary,
    pub args: Vec<EnvVal>,
}
```
Or, into:
```rust
(Binary, Vec<EnvVal>)
```
And then the full signed message can be defined as:
```rust
(Binary, Vec<EnvVal>, Vec<Signature>)
```

**Comment by sisuresh** [comment]
If I understand correctly, you're saying we should remove the domain from `MessageV0` because the underlying object is a Map so the position of the domain isn't guaranteed. This will make authorization harder to understand since the pre-image won't exist in a single object, and I'm not convinced of the upside here. Filling in the domain is easy at the moment, and we can keep it that way if the SDK can return whatever the domain turns into in the future.

**Comment by leighmcculloch** [comment]
@sisuresh I was suggesting changing domain into a Binary (now called Bytes in the XDR and SDK) so that it can contain all of the domain (network passphrase, contract id, contract fn name, etc). It still needs to be part of the message that is signed.

**Comment by sisuresh** [comment]
Ah ok that makes sense. It sounded like you were advocating for something like `sign(domain.serialize() + Message::V0(args).serialize()`.

**Comment by jonjove** [comment]
I believe (and feel free to disagree) that the goal should be to make it easy for the SDK, CLI, and wallets to sign messages which comply with some ecosystem standard. In general, I don't think it can be easy to bespoke messages that don't comply with that ecosystem standard so we shouldn't worry about those.

Given the above goal, I don't think concerns like

> The reason I suggest moving it out of MessageV0 is because of Map ordering there's no guarantee it wouldn't end up somewhere in the message, so it is difficult to encode the request independently of the domain that needs prepending.

should motivate the design. The SDK, CLI, and wallets already know the message format (because it's an ecosystem standard) so they can put the information in the spots required. For the same reason, I don't see the advantage of

> I was suggesting changing domain into a Binary (now called Bytes in the XDR and SDK) so that it can contain all of the domain (network passphrase, contract id, contract fn name, etc).

I think the objectives of the ecosystem standard should be

- the message format shouldn't differ from the format of any other `contracttype` because the message _is_ a `contracttype`
- the message should contain a version (in the token contract this is achieved by the `Message` enum) so we can support future changes or other cryptography
- the message should specify independently each piece of data that can be determined automatically by a wallet (eg. contract ID, contract function, network ID, etc) so that the message remains easy to read and implementers know how to construct it
- the message should specify a single vector of data that cannot be determined automatically by a wallet (probably just arguments containing the nonce) so that the must-be-provided part is clearly separated
- the message type should live in the SDK (for contracts to use) and some external crate (for CLI, wallets to use) -- note that these types are different because the SDK version uses `RawVal` whereas the CLI, wallets should depend on `SCVal`

If we achieve all of this, then I think we will have made signatures as easy as possible to use across the different systems. Thoughts @leighmcculloch @sisuresh?

**Comment by leighmcculloch** [comment]
+1 I think this approach is good. I want to make one modification:

> * he message should specify independently each piece of data that can be determined automatically by a wallet (eg. contract ID, contract function, network ID, etc) so that the message remains easy to read and implementers know how to construct it
> * the message should specify a single vector of data that cannot be determined automatically by a wallet (probably just arguments containing the nonce) so that the must-be-provided part is clearly separated

I think the independence of these data pieces should go as far possible down to the lowest abstraction. i.e. The encoded form of the message should result in the user provided data being separated and not interleaved with the automatically determined data.

This is a small change I think, it means making the message to be signed a Vec instead of a Map:
```
(automatically_derived_data, user_data)
```

The why for this is to limit the systems that need to know about and interact with map ordering. So that not all systems that might verify the data, or extract the user data, or create the data, need to know how map ordering works. And to make it so that in the XDR encoded form the automatically derived data sits independent of the user data.

**Comment by jonjove** [comment]
> So that not all systems that might verify the data, or extract the user data, or create the data, need to know how map ordering works.

This is very interesting. I didn't understand that this (meaning so all systems don't "need to know how map ordering works") is why you wanted the data separate. Is it reasonable to think that this is possible? Is the complexity of map ordering so high that doing this is prohibitive? Even just preparing a `KeyedAuthorization` (which will be needed to actually pass signatures, regardless of how they were obtained) requires knowledge of the map ordering.

**Comment by leighmcculloch** [comment]
It's not just about the map ordering, but about keeping the data separated once encoded so we have the context in one blob and the arguments in another, and the signatures in a third blob. Those blobs can be joined together, or embedded in a structure, but it's a red flag to me if their contents are disordered or interleaved in anyway. This is why I suggest a Vec instead of a Map. Keeping them separate comes at almost no cost I think?

**Comment by jonjove** [comment]
The red flag I'm seeing here is the desire not to use the `struct <-> Map` representation because it disrupts data ordering. If we think data ordering is important, then we probably shouldn't be using this representation in contracts anywhere. If we don't think data ordering is important, then we probably shouldn't be worrying about it here.

I'm not really understanding the reason having the data interleaved is a red flag to you. That's the part I think I really need to understand in order to resolve this issue. Why does the data ordering matter? What bad thing happens in the event that the contents are disordered?

**Comment by leighmcculloch** [comment]
> not to use the `struct <-> Map` representation because it disrupts data ordering. If we think data ordering is important, then we probably shouldn't be using this representation in contracts anywhere.

+1 I would like our maps to be insertion order preserving so that there is no special data ordering when it comes to the serialized data. We've discussed this previously as a team, and there wasn't buy in on changing it to be insertion order.

This is an astute point you make. My motivation for why these fields should be ordered and separated is largely similar to the issue with maps that we already visited and decided on.

> Why does the data ordering matter? What bad thing happens in the event that the contents are disordered?

The following signed payload is from the authorization example:
```rust
pub struct MessageV0 {
    pub function: Symbol,
    pub contrct_id: BytesN<32>,
    pub network_id: Bytes,
    pub parameters: Vec<EnvVal>,
}
```

I note that nonce is moved now into parameters, which was imo the biggest concern, so the fact that is addressed now is great.

It's convenient for tooling and some systems if this message can be constructed without deep knowledge. For example, the domain may be a fixed known thing or a derivable thing that can be prepended onto whatever the encoded arguments are. The tool signing may not know what the parameters are, other than it being some bytes.

Stellar transactions are structured like this, with the domain prepended onto the transaction in TransactionSignaturePayload ([ref](https://github.com/stellar/stellar-xdr-next/blob/6e8ac4ebbef86b044f78f8851154d8094bc86433/Stellar-transaction.x#L788-L799)), and then signatures appended in the TransactionEnvelope ([ref](https://github.com/stellar/stellar-xdr-next/blob/6e8ac4ebbef86b044f78f8851154d8094bc86433/Stellar-transaction.x#L743-L749)).

I think a Vec would be more suitable, but if we need the signed message to be a map, I would at least group the domain/context items into a single type so that there's a single type that code can derive or generate independent of arguments.

The following signature use is from the single_offer_xfer_from example, where the signature is embedded within the parameters, since it's placement matters since its placement defines who `to` is:
```rust
fn trade(e: Env, to: KeyedAuthorization, amount_to_sell: BigInt, min: BigInt) {
```

The placement of the signature within the args increases the complexity of tools, since tools need to know where and how to place things. So ideally we can take these unrelated components and just prepend / append them together to produce whatever it is we need.

I had been thinking the total message could be:

```
context | arguments | signatures
```

But as we discussed in the meeting today this doesn't address both the optimization opportunity and making it really clear what is being signed for.

Let's continue to discuss in Discord `#soroban-dev-auth` for how we can define how these params are inserted into the args.

**Comment by jonjove** [comment]
I think at this point we've decided not to do this, at least right now. If experience using authorization in CLI and wallets shows that this was the wrong decision, we should open a new issue at that point to discuss the new information. cc @leighmcculloch in case you disagree
