### ISSUE TITLE
Add deviation parameter instead of pure uniform periods

### ISSUE THREAD

**Issue by antb123** [stellar/stellar-protocol#1412]
@yuriescl The SEP originally intended to use the round based data feed system seen in solutions like Chainlink. However, we ultimately landed on doing uniform update periods. That being said, the current implementation would have known timestamp gaps so contracts could find exact prices.

There is some context as to why here: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0040.md#timestamps-instead-of-rounds

I'm not strongly attached to uniform update periods over rounds. However, the benefit of having strong temporary storage guarantees and TWAP capabilities do seem like an improvement. Was there a specific use case this change was targeting?

cc: @orbitlens

_Originally posted by @mootz12 in https://github.com/stellar/stellar-protocol/issues/1362#issuecomment-1638390936_

**Comment by antb123** [comment]
We have been discussing this and would like to also support more real time data. 

We were thinking of adding a deviation parameter. If the real-world price of an asset deviates past some interval, it will trigger all the nodes to do an update. Right now, most Ethereum data feeds have a 0.5% deviation threshold. We were thinking of doing something like that but also include events. 

https://soroban.stellar.org/docs/basic-tutorials/events

**Comment by orbitlens** [comment]
Personally I don't like the purely deviation-based approach because it's more prone to manipulations. In our implementation we utilize volume-weighted averages to normalize price inside periodically reported timeframes. However, if you report price only when significant deviations are spotted, it might be quite easy for an attacker to manipulate prices of shallow-liquidity tokens, and consumer protocols won't be able to counter it applying TWAP or any other averaging methods because there's not enough recent price history records.

If you want to support a uniform timeframe reporting AND also push updates when deviation is spotted, it's a nice extension to the protocol, we can easily extend the interface. But if you want to switch completely to the deviation-based oracle architecture, without periodic price reporting, in many ways it will be very different from current SEP-40 and will probably require its own SEP.

As I see it, the easiest path forward with modifying current SEP is to add the `deviation()` function that returns deviation threshold (or 0 if the oracle contract doesn't support this functionality) and declare custom event format for events that will be triggered with every oracle price update (both planned and triggered by the deviation threshold intersection) with a signature like `oracle_price_update(oracle_contract: Address, updated_assets: Asset[])`.

**Comment by mootz12** [comment]
I agree with @orbitlens that we need a change regardless to document required events for any price update.

I'd like to suggest including the timestamp of the priceData in the event data:
```
oracle_price_update(oracle_contract: Address, timestamp: u64, updated_assets: Asset[])
```
---
@antb123 I'm curious if you feel like you can work a deviation threshold into the current SEP as it stands? I'm assuming your interested in operating in a similar manner to Chainlink, where it's update every X seconds or if the price deviates by more than Y?

I'm on the fence about adding a deviation read function, since it's a value that won't be used on chain by a consumer.

**Comment by orbitlens** [comment]
> I'd like to suggest including the timestamp of the priceData in the event data

The timestamp can be retrieved from the transaction result, but probably it's easier to retrieve it directly from the event itself, so agree here.

**Comment by hethm999** [comment]
امر طبيعي جدا ان تتم مطالبة الملكية الفكرية هذا قانوني والاصول الرسمية هي ملكية فكرية يحق لاي شخص المطالبة بها اذا امكن مساعدة فريق الدعم في استرجاع الحقوق المشروعة لحاملي الرمز المميز والعملات وارباحها في المنصات مالم سوف يقدم بدعوى قضائية لاسترجاع حقة المشروع وحقوقة الخاصة مع دليل الاثباتات؟ وبلنسبة الذي تتهموة بلمهاجم هو ف الواقع مطور من اعلا مطورين شبكة بلوكشين اقترح ان تعملو معة وتعطوة نصيبة المشروع والقانوني لاستعادة حقة
