### ISSUE TITLE
Proposal: Use federation for additional asset information

### ISSUE THREAD

**Issue by raymens** [stellar/stellar-protocol#21]
Federation is currently used for account related stuff. Maybe expand this with information about an asset that may be useful for wallets. Using the homedomain of the issuer's account it can query the federation server using the assetcode and address. After an initial request it can cache it for some time to not flood the federation server as the values probably won't change that much.

A wallet can use this metadata to show an asset as it is meant to be shown by the issuer. This can allow different wallets to have an uniform representation of the same asset.

Request:

```
https://api.stellar.org/federation?q=EUR*[issuers_address]&type=asset
```

Response:

```
status: 200
{
    code: "EUR",
    issuer: "[address]",
    name: "Euro's",
    symbol: "€",
    ui_decimals: 2,
    ui_step_increment: 0.25,
    ... : ?
}
```

**Comment by jedmccaleb** [comment]
Why not just add this to the stellar.toml ?

**Comment by raymens** [comment]
That might be a better option yes, that seems like a different but simpler implementation. 

The main thing I wanted with this issue, is to start (and log) a conversation about handling assets in wallets.

**Comment by jedmccaleb** [comment]
This is related to this conversation: https://github.com/stellar/stellar-protocol/issues/20

And this https://github.com/stellar/stellar-protocol/issues/23

Basically I think we only need 2 modes. decimal or integer. Being able to move the decimal arbitrarily I don't think buys us much since the range of decimals that humans can deal with is pretty limited.

**Comment by MikeFair** [comment]
Having had a few of these conversations and seeing the same responses.

The 12 character asset code made up by the person issuing the credit cannot uniquely identify the asset the credit line is referencing.  It identifies what the issuer called their credit line.

If IssuerA puts out USD and IssuerB puts out USDollars; we humans in the United States can kind of tell that's "probably" the same underlying asset being credited.  We can't expect a Wallet to figure that out.

It's the distinction between the "credit line asset" and "the asset referenced in the credit line".
What we have a balance for is a "credit line asset", the underlying referenced asset is completely missing.  


> Basically I think we only need 2 modes. decimal or integer.

Has little to do with "identifying" the referenced asset for a Wallet.

> Why not just add this to the stellar.toml ?

Again, unless I'm misunderstanding how that works; this would tell you about the credit line identifier from the issuer; not the asset being credited; and you'd to search the entire data set to find the identifier you had to get any associated data; that's a lot of effort/work to expect from a Wallet when ```var details = GetAssetDetails(assetReference);``` would be so much easier.

**Comment by jedmccaleb** [comment]
What the asset is is ultimately up to the issuer. If I issue an asset called "USD" but only redeem it for olives. I'm issuing olives not dollars despite the name.  My point is I don't see what it buys you to store this extra info in the ledger. The issuer can provide extra info about what they mean by USD outside the system since this ultimately the only place that it matters. It is also not something that needs to be globally known. 

Of course I hope that people follow conventions about what they call assets. For example I hope when someone issues dollars they call it USD and if they are issuing something called USD they mean dollars but there are no operations on the ledger that require this to be true so it doesn't seem like the extra info belongs in the ledger.

**Comment by MikeFair** [comment]
@raymens 

Try this: http://76.230.245.107:8000/federation?q=IBM*&type=TICKER

You should get back every exchange listing globally that uses "IBM" as their Ticker. 
It still needs to translate the exchange code to the appropriate MIC for the exchange.
The Name, Sector, and the Security Type fields are probably the most interesting for now.

Other identifiers like SEDOL, CUSIP, and ISIN are also supported by the query API.
The full list is here: 
https://www.openfigi.com/api#supported-identifiers

These IBM results have another company that uses the IBM Ticker somewhere and some Money Market Assets. I don't recognize either of them.

Software would deduplicate these results based on the shareClassFIGI key which is linked to a specific company issued asset (as opposed to all the places that asset is traded).  
[The CompositeFIGI is specific to the Country/Region where the asset is registered, and the FIGI is unique to a specific listing on a particular exchange (which is why there are so many results).]


The federation server can also generate it's own FIGI-like identifier for accounts in Stellar.
The goal is coming up with some kind of "short code" for people to use to link to their accounts.

The thinking here is moving toward creating "Assets" as objects within the system just like "Accounts".
Not all asset codes necessarily get object status; sometimes all you want is named numeric value (like credits in an arcade or something); but when those Asset Codes are supposed to represent or be linked to actual assets in the real world; then creating an object to store some basic data about that asset makes complete sense to help coordinate our shared understanding of it.
