### ISSUE TITLE
New SEP/CAP numbering system

### ISSUE THREAD

**Issue by JeremyRubin** [stellar/stellar-protocol#286]
Proposal:

Re-number existing SEPS to be after the current highest CAP by adding 100 to every SEP number. Do not re-number any CAPS.
From now on, SEP/CAP numbers should correspond to the github Issue or PR that opened them first.
No current issues in range 100-199 should correspond to something that will get a SEP or CAP that does not already have a number (if so, just open a new issue for assigning it a number).

This is a little controversial because:

A) the numbers will all be bigger
B) there may be disagreement on which number should be chosen (the lowest reference IMO)
C) this leaves gaps in the assignable SEPs/CAPs

However, doing this fixes issues which makes it difficult to recall if we are talking about a SEP or a CAP by number, doesn't require an editor to assign a number, and scales to new RFC types other than SEP or CAP, handles competing standards for similar things, etc.

**Comment by johansten** [comment]
Boom! That's what I've been saying for ages!

**Comment by theaeolianmachine** [comment]
Yeah for certain, have definitely seen @johansten mention this in other threads, and I considered this approach as well (it's what Ethereum does, etc.).

Here's why I decided against using PR/Issue numbers for the CAP/SEP numbers:
* It highly couples the RFC process with Github. As of today, Github is not the primary place where discussion takes place, mostly because we haven't doubled down on it being the central place for discussion and have tried to focus discussion elsewhere, e.g. the dev mailing list. It's of note that I'm also currently investigating what the future of this looks like, especially with Google Groups' upcoming changes, but I generally bias against Github because while it's an ok interface for storing records, it's pretty terrible at being a place where discussion can thrive (unless you're highly motivated). In any case, I'm not a fan of coupling them for what I don't see as any real gain because...
* The cost of assigning a new number when merging it in is practically non-existent; I really haven't had a problem merging things in and immediately assigning them a number, and it seems easy to automate. Plenty of larger RFC processes (Rust can be used as an example) don't pick a number beforehand and have an editor pick it before merging; I just don't see it being a large amount of overhead.
* PRs are not long lived — provided the formatting is fine, we generally merge them in, and there are likely to be multiple PRs issued to a given proposal. I know EIPs are also like this (as opposed to say something like Rust where PRs are a canonical record), but given the PR is ultimately merged does it really make any difference on which number ultimately gets picked? Rust does ultimately use the number of the PR, but at least it makes sense there because it creates a hard link back to the entire conversation — with this proposed model, it would just point to the original PR (which is almost certainly just "draft merged"). The other question I have is are these numbers any easier to determine what a CAP/SEP actually means? To me it seems any numbering schedule still requires a lookup elsewhere (whether it's a README, Github search, or just crawling through a directory) and that ultimately the title is still the best way to convey information. It was brought up multiple times that we did not want to use PRs as the persistent record of a draft, and that we wanted them to live in the repo (especially for our Github hating friends).

However, if CAPs and SEPs starting at the same offset is confusing, changing the SEPs to start at SEP-0100 seems very reasonable (just need to fix a lot of references for existing ones, and spread the word); if that helps a good bit, I can work towards getting consensus from others.

Finally, I do think something that enables both of the projects brought up here is that they have separate websites that better serve actaully finding proposals and information about them — I would _love_ to have the equivalent of [https://eips.ethereum.org/](https://eips.ethereum.org/) for Stellar, and I'm working on getting it on someone's slate (I'd do it myself, but my front-end chops are only as up to date as say 2016 :)), so hoping to have more on that front in the future.

**Comment by JeremyRubin** [comment]
It's not the offset that is the issue, it's that there shouldn't be overlapping numbers, ever -- they should use the same counter. SEP and CAP should be just an additional descriptor on top of the numbers. It does make a difference which number gets picked because we want to have a reference number as soon as possible for discussion purposes. The number itself is not meaningful. This is especially good if we ever change the groupings of SEPs or CAPs into more categories, our numbering is stable.

Personally it's unclear to me that github isn't the best place for discussion compared to, say, the mailing list. On github I get something I can easily link to, and can link to from other github issues). It also integrates with email, so it works fine for me... (I think they fixed David's email issue?). I've not experienced issues with github being terrible for technical discussion (actually, the opposite in my experience).

Github also has the ability to maintain a wiki or index.md pages with tables, which are nicely formatted for creating a links reference. We should just do that for now -- no need to get fancy prematurely.

**Comment by theaeolianmachine** [comment]
> It's not the offset that is the issue, it's that there shouldn't be overlapping numbers, ever -- they should use the same counter. SEP and CAP should be just an additional descriptor on top of the numbers. It does make a difference which number gets picked because we want to have a reference number as soon as possible for discussion purposes.

I'm not seeing the value here, especially because SEPs should likely outpace CAPs in terms of growth and should overlap even less frequently in the future. And even if they have the same numbers, _it still says nothing about what it's referencing_ — you either have memorized the number (CAP/SEP giving a small amount of context), or you go to look up what it represents. If it means putting them in a single table to easily find them, great we can do that, but realistically there are many people who care deeply about CAPs but don't care at all about SEPs, and sometimes vice versa; I'm just not seeing how it makes it much better to share the same numbering system when the context is often very different (CAP-0013 & SEP-0016 are the only obvious pair that get referenced often with each other, and even that feels like it's coming to an end).

> Personally it's unclear to me that github isn't the best place for discussion compared to, say, the mailing list. On github I get something I can easily link to, and can link to from other github issues). It also integrates with email, so it works fine for me... (I think they fixed David's email issue?). I've not experienced issues with github being terrible for technical discussion (actually, the opposite in my experience).

For line by line commenting on a document (often less valuable with text rather than code due to long lines), it's great. But if I were to compare the experience of going to say a Discourse forum vs a Github Issues page, Github leaves much to be desired and for this use case, seems to be a strict subset of the functionality of many other systems focused on discussion. I do think it's better than email, but it certainly does not stand out to me when looking at software focused on discussion.

FWIW, (not trying to sell Google Groups here; I do think we can do better) you can get a hard link to a discussion in Google Groups, and with regard to linking, I think it's great when Issues/PRs are the authoritative place for discussion (like the typical flow for a coding project), but I don't think this can't be supplanted by something more focused on discussion that also has the ability to link between discussions (and also have integrations with things like Github).

In any case, I'm working on it, and am certainly considering it.

> Github also has the ability to maintain a wiki or index.md pages with tables, which are nicely formatted for creating a links reference. We should just do that for now -- no need to get fancy prematurely.

We already do that with the README in each respective folder, and can certainly move them to another file if it gets too long, in case you didn't know. I do think there's a lot of value with basic filtering though when we get to it.

**Comment by johansten** [comment]
These things don't get adopted because someone approves them, they get adopted because the community find them useful, and for that we need to engage the community, get early feedback, etc..

Just as Jeremy is saying, the thing about getting a number right away is that you can start talking about it, you can point people to it, you can reference it.

**Comment by theaeolianmachine** [comment]
Yeah everyone understands that — however given that drafts get merged with a number _quickly_ and the bar is "is this written in the right format as the rest of the CAP/SEPs", I don't see that as a blocker for productivity. No one is going to start massively adopting an idea over a few days, and even then you can still share the pull request if you're antsy.

**Comment by johansten** [comment]
@theaeolianmachine 

You are right, things have started moving forward with greater speed recently.

**Comment by msfeldstein** [comment]
It sounds like the main issue was in the time between writing up a draft PR and it getting merged as a Draft SEP/CAP there was no real way to reference it besides a PR link that will change/disappear.  As long as we merge these quickly this shouldn't be a large barrier to discussion.

I'm erring on the side of closing issues so feel free to re-open if that wasn't the main issue.

FWIW i also agree that github is a much better place to discuss these proposals.
