### ISSUE TITLE
SEP6 -> SEP24 migration path

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-protocol#440]
General comment:
IMO there should be a clear, backwards-compatible migration path from sep6->sep24. There are those of us who need (or would like) the non-interactive part of sep6 (although, I do think that splitting interactive and non-interactive apart into two SEPs is a good idea).

In order for there to be a backwards-compatible migration path, there should probably be another sep containing the non-interactive part of the old sep6. However, at the very least, sep24's endpoints should be renamed. This way, any anchor that migrates will not be breaking their client's relying on non-interactive endpoints.  Perhaps, the sep24 deposit endpoint is now `/sep24/deposit` or `/interactive/deposit`. To be clear, there are some endpoints that can be migrated with the same name (like `transactions`, `transaction` and `fee`) because they are the same for both interactive and non-interactive flows. So long as the responses are backwards compatible, the routes can stay the same.

**Comment by msfeldstein** [comment]
This is an interesting idea.  If we left `/deposit` alone as the legacy sep6 endpoints, and added `/interactive/deposit` and `/noninteractive/deposit` we can not worry so much about backwards compatibility.  For most people, since the behaviors are the same, they would just require adding a new URL Endpoint `/interactive/deposit` that points to the same handler as their existing `/deposit` but if someone wanted to provide both behaviors they can split their logic out into two endpoints.

**Comment by efritze** [comment]
On that note why is SEP6 marked as deprecated?

Not all anchors want to deal with the overkill of an interactive workflow.

Separate both SEP6 and SEP24 endpoints as suggested above.

**Comment by msfeldstein** [comment]
Does this solve people's problems? I changed `/deposit` to `/interactive/deposit`
https://github.com/stellar/stellar-protocol/pull/438

regarding the overkill of interactive workflow i will create a noninteractive version of SEP24 in the same way.

**Comment by msfeldstein** [comment]
@efritze 
does this work for you regarding non-interactive workflows? https://github.com/stellar/stellar-protocol/pull/454

**Comment by msfeldstein** [comment]
Fixed in #438
