### ISSUE TITLE
SEP-25: New Account Deposits

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#446]
We've created a SEP to alleviate the pain of trying to deposit assets into a new user account.
Details here: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0025.md

Please add any discussion in this issue

**Comment by leighmcculloch** [comment]
This approach seems really effective.

In the `Client` section it states that:
>the client will use Horizon's Accounts for signers endpoint to listen for new accounts the client can sign for. Once the providers transaction completes, the client will find the holding account, and claim the assets within using the transaction below.

This may be exploitable. The client is allowing anyone willing to set their key as the signer of an account to trigger behavior in the client. This would hopefully be rare, but there might be some interesting applications here that we aren't aware of. It also may not scale to have many clients polling the state of the last full ledger, vs having them polling the state of a single account (cc @bartekn).

Could the provider give the client the address of the holding account over a secure trusted connection so that the client is only polling the state of that one account?

**Comment by jonjove** [comment]
The SEP doesn't seem to make any mention of `AUTH_REQUIRED` assets, how do you intend to handle those?

Nitpick 1: `ChangeTrust` has fields `line` and `limit` rather than `asset` and `amount` (see Provider's transaction operation 2, and Client's transaction operation 3).

Nitpick 2: I think it would improve clarity to use something like "<ASSET_CODE>" instead of "ABC".

**Comment by msfeldstein** [comment]
> This may be exploitable. The client is allowing anyone willing to set their key as the signer of an account to trigger behavior in the client.

Yeah this is what i refer to in the security section.  The wallet should ensure that either the client is expecting this asset in this amount because they finished a SEP-6/24 deposit, or possibly alert the user that an account is available to claim

**Comment by msfeldstein** [comment]
I will update the AUTH_REQUIRED bits when i can verify what im planning actually works in the implementations

**Comment by istrau2** [comment]
Voting against (for now, I can be convinced otherwise).

What is the motivation behind this SEP as opposed to just listening for trustlines (as most anchors do currently)?

Pros:
1. Anchor implementation is easier perhaps (now anchors don't need to listen for trustlines), the deposit logic can be fully executed every time.

Cons:
1. Client implementation is more complicated. Instead of just adding trust, the client also needs to find the holding account, send the assets in and merge.
2. Anchors need to update their implementations (only to have this be deprecated by some real solution like CAP-23 or something like it).
3. From the user's perspective there is no real usability improvement (am I missing something?). They just add the trustline and receive the tokens right away.

Why not just push forward on a real solution to concurrent account and trustline creation?

**Comment by MisterTicot** [comment]
> This approach looks really effective at isolating the responsibilities of both parties.
> 
> In the `Client` section it states that:
> 
> > the client will use Horizon's Accounts for signers endpoint to listen for new accounts the client can sign for. Once the providers transaction completes, the client will find the holding account, and claim the assets within using the transaction below.
> 
> This may be exploitable. The client is allowing anyone willing to set their key as the signer of an account to trigger behavior in the client. There might be some abusive applications of that feature that we won't be able to predict. It also may not scale to have many clients polling the state of the last full ledger, vs having them polling the state of a single account (cc @bartekn).
> 
> Could the provider give the client the address of the holding account over a secure trusted connection so that the client is only polling the state of that one account?

Introducing trusted parties breaks crypto currency security model.

**Comment by MisterTicot** [comment]
This SEP is interesting as it shows that since we have a signer endpoint, we can implement [sponsored trustlines](https://groups.google.com/forum/m/#!topic/stellar-dev/rCNEiwp2iRg) without protocol modification.

I think this is promising but needs refinement. For instance, how do the wallet knows a given account is _meant_ to get merged?

Maybe I want to create a split account to deal with a given currency?

I assume you need some way to tag the account (a data entry "type": "trustline_request" seems the most straightforward way).

I think you also need to keep a door open for refunding in case user doesn't claim the asset - this could be achieved by having both the anchor & user having control of the transitional account account.

Anyway good job, I'm looking forward for supporting this solution as it offers a convenient way to enter in Stellar from leading currencies.

**Comment by msfeldstein** [comment]
> @istrau2  What is the motivation behind this SEP as opposed to just listening for trustlines (as most anchors do currently)?

The main benefit of this sep is for brand new accounts which don't have any lumens and haven't been created yet.  It's not as useful for existing accounts with a lumen balance already.  This sep gives anchors a way to create the account for the client, in an atomic way with the actual asset deposit, otherwise the anchor will need to create the account for the client, then wait for them to hopefully add the trustline, and if they don't then they're in a weird state.

**Comment by msfeldstein** [comment]
Even with CAP23 this may still be very useful for the case of new accounts that need to be created by the anchor for the user (because asking users to acquire lumens externally is too high a barrier to entry for most businesses)

**Comment by msfeldstein** [comment]
> @MisterTicot how do the wallet knows a given account is meant to get merged?

I will definitely need to refine this part, but its a product (wallet) question to ensure the user actually wants these assets.  The most common use case will be a SEP24 deposit in which the wallet knows the user has requested deposit assets of X type in N amount from Y distributor (since they've gone through the SEP24 flow and have those transaction details), but perhaps we need something more explicit.

**Comment by istrau2** [comment]
> The main benefit of this sep is for brand new accounts which don't have any lumens and haven't been created yet. It's not as useful for existing accounts with a lumen balance already. This sep gives anchors a way to create the account for the client, in an atomic way with the actual asset deposit, otherwise the anchor will need to create the account for the client, then wait for them to hopefully add the trustline, and if they don't then they're in a weird state.

Yeah, I understand the motivation. I guess my point is (and perhaps I didn't communicate so well in my earlier post) that I don't think this SEP provides much improvement at all in practical terms (again, I may be missing something). 

The way I see it, this SEP is aimed at benefiting anchors. It doesn't really benefit the end user in any way and it only complicates client implementation. The issue is, that I don't think it actually benefits anchors much practically speaking, for a couple of reasons:

1.  Currently, most anchors listen for trustlines (at least, we do at Stellarport). Anchors would have to update their implementation to fulfill this SEP which is really just a stop-gap solution. 
2. This SEP would result in some percent of funds getting stuck in the holding account. This puts the anchor in a worse situation than the user not adding the trustline because the anchor can't mark the deposit as abandoned.

Also, I think this SEP may be missing some subtlety that arises from the fact that deposits may take a considerable amount of time. For example, if a BTC deposit has too low a tx fee, it could get stuck for hours. We cannot rely on the client being available when the deposit clears. For example, a user could send a BTC deposit and then turn off their non-custodial wallet. Additionally, there are cases where a user might remove a trustline while the deposit is in flight (i.e. this SEP would need to be extended to already existing accounts that simply do not have the trustline in place at the time of distribution).

This means that the client must scan the network on startup for any account for these kinds of holding accounts and prompt the user to sweep them.

As I am writing this, I realized that this SEP does in fact result in a benefit to the end user. The difference between this SEP and the anchor simply listening for the trustlines is the client application being able to automatically discover and add the trustline (or prompt the user) automatically. Currently, there is no way for the client application to automatically discover deposits pending trustline addition (is this true?). Perhaps this benefit makes this SEP a net positive (I am undecided).

**Comment by ConnorMac** [comment]
If the primary reasoning for this is to alleviate the barrier to entry for customers to acquire lumens it just seems to delay the fact that a user of a non-custodial wallet would need to eventually fund their account and merge in the pending deposit accounts.

> The difference between this SEP and the anchor simply listening for the trustlines is the client application being able to automatically discover and add the trustline

I think the above is the biggest benefit of the SEP. I don't think there is a method for discovering required trustlines otherwise.

**Comment by istrau2** [comment]
@ConnorMac but is there an easier way to accomplish the same thing (i.e. discoverability of deposits pending_trust)?

**Comment by msfeldstein** [comment]
If that's the only reason i dont think its worth doing.  One of the problems i didn't solve yet, but have a solution to after a discussion with @jonjove, is the idea that if the client never 'claims' the assets they will be essentially lost.  I think creating a timelock for anchors to be able to recover unclaimed deposits will be an important part of the SEP, as well as dealing with AUTH_REQUIRED.

Note to self for the solution to the recovery is to remove all signers, and instead create two pre-auth transactions signers, one with a timelock before time X which merges the accounts into the clients account, and one with a timelock after which returns the assets to the anchor

**Comment by jimdanz** [comment]
I believe that is the anchor's responsibility to create accounts and fund them.  This should be done synchronously once the transaction has been created, even settlement will be asynchronous.  Yes, this is a cost to the anchor but it should be thought of as covered by the anchor's transaction fee.  Yes, the transaction may fail or never happen, but the prefunding cost (3 XLM) is likely less than the KYC expense already incurred by the anchor to onboard the user so this is not material.

Specifically, the flow that we used for AnchorUSD/StellarX is:
1) User gets to the very end of interactive deposit flow.
2) Anchor checks that account exists, creates it with 3 XLM if it does not.
3) Wallet immediately adds a trustline to the anchored asset.
4) ... time passes , fiat moves ...
5) Anchor is able to issue asset to the wallet

From my perspective that is a pretty easy solution for an anchor, and not too complicated for a wallet.  It worked in 99% of cases.  The failure being when a user had a hardware wallet or otherwise didn't let StellarX sign their transactions automatically.  We'd email them and they'd fix it.

-----

I also agree with @istrau2 that the client needing to be available when the transaction clears is undesirable.

> Currently, there is no way for the client application to automatically discover deposits pending trustline addition (is this true?).
Not discover, no.  But a client application knows what deposits it initiated via SEP24.

**Comment by istrau2** [comment]
I am for solving this issue using some form of https://github.com/stellar/stellar-protocol/blob/master/core/cap-0023.md. Better to expedite a comprehensive solution like that rather than pushing this stop gap solution through, especially considering the stop gap will require both anchors and clients to do a lot of extra implementation work (only to scrap it all later for CAP23).

**Comment by tempofr** [comment]
Here is what we have been doing for the past 2 years,

1) code checks if trustline exists.
2) If not it errors the deposit, checks the xlm balance and if low sends 2.1 xlm
3) sends the user an email telling them their error and how to fix it
4) someone manually un-errors the tx and funds are released (I guess this could be turned into a polling solution but the volumes aren't there yet)

@jimdanz  - I guess you securely tell them their private key via your application? We hesitated to send the private key via email or sms.

We tried the lobstr solution as well which is good but is a trusted solution. It works well if the users has a lobstr wallet.

**Comment by buhrmi** [comment]
Stupid question, but wouldn't this be solved simply by removing the need for a `createAccount` transaction and just completely eliminating trustlines?

**Comment by buhrmi** [comment]
I've just made the proposal to remove the `createAccount` transaction and trustlines as [SEP-28](https://github.com/stellar/stellar-protocol/pull/476). I think that would instantly solve the outlined problems.

**Comment by s-a-y** [comment]
@buhrmi first of all changes you propose cannot be done as SEP, it requires changes to core protocol, therefore CAP.
Second of all we're trying to come up with a way to do it without breaking current features. Proposal to get rid of account creation and trustlines can be contentions. I for one like that it's hard to lose money on stellar, because you can't just send it to random account or being able to choose tokens I want to hold on my balance.

**Comment by buhrmi** [comment]
yeah no doubt it's contentious.

**Comment by buhrmi** [comment]
I just found out about [CAP-13](https://github.com/stellar/stellar-protocol/pull/213), which seems to try to solve the same underlying issue. So how about we focus on that one?
