### ISSUE TITLE
CAP for cross order type

### ISSUE THREAD

**Issue by antb123** [stellar/stellar-protocol#450]
In traditional exchanges (futures/equities) there is the concept of a "Cross order".  A cross order is typically an Over The Counter (OTC) trade that an exchange executes that it announces to the market. E.g.  [TMX cross type](https://www.tsx.com/trading/tsx-alpha-exchange/order-types-and-features/cross-facilities). 

For example [Tempo](https://tempo.eu.com) calls [Cowrie](https://www.cowrie.exchange) on whatsapp and they agree to exchange 10,000 [EURT](https://stellar.expert/explorer/public/asset/EURT-GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S) for some [NGNT.](https://stellar.expert/explorer/public/asset/NGNT-GAWODAROMJ33V5YDFY3NPYTHVYQG7MJXVJ2ND3AOGIHYRWINES6ACCPD) This is a trade they would like to announce to the market to count for trading volumes and also for audibility in the future.  Currently the trade if put on the SDEX is open to "Cross Interference" where part of the trade might not get executed.
[https://www.investopedia.com/terms/c/crosstrade.asp](https://www.investopedia.com/terms/c/crosstrade.asp)

This could be implemented as an order that only executes with a specified public key.

**Comment by msfeldstein** [comment]
I know we talked about it at meridian but just want clarification

If this is just for auditability and accounting, could we just create a special memo type for a transaction with two payments, announcing that this is a cross order, and not touch the dex at all?  Then anyone capturing volume would just listen for any transactions with this memo type and add that to volumes

**Comment by tempofr** [comment]
Ok but it wouldn't count as trading volume.. I spoke with Tomer about it extensively.

There is a legal requirement in equities and futures to print trades on an exchange. This could also be used for a dark pool/liquidity pool that is off DEX. I believe it is how 0x works.

Normally crosses have to be within the spread. So if the trade was outside the bid/ask a the cross  would interact with the resting liquidity (buy or sell) until it got to a point where it could cross. The dex wouldn't have to deal with that. It would only have to take both sides of the order and and ensure there is no interference. 

Currently when I try to cross XLM and EURT by putting up 2 orders it generally fails  due to interference.

The work around that Nikhil mentioned is to create 2 temporary assets BTC-TEMP and EURT-TEMP that no one can hold and then trade into them and cross them (via XLM or direct). Its a bit messy but it would work.

**Comment by msfeldstein** [comment]
ok yeah the legal requirement that it's "on an exchange" makes sense (even though its not entirely clear what 'an exchange' means in a decentralized world)
