### ISSUE TITLE
SEP-10 doesn't support custodial wallets

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#458]
Currently [SEP10](ecosystem/sep-0010.md) authenticates uses based on their stellar account ID.  In custodial wallets, there can often be many users sharing a single stellar account, multiplexed by memo to determine who each transaction represents.  

SEP10 needs a way to allow authenticatino by custodial accounts.  I believe this could be solved by adding an optional `memo` param to sep10's `GET`(ecosystem/sep-0010.md#challenge) request, and then storing that memo in the `manage_data(key:)` field to be retrieved at run-time to choose who it belongs to.

With this however, there's no cryptographic link between the memo and who is signing for it.  There's no cryptographic link between the memo, and the actual signature, but this may just be the nature of custodial accounts.  However it might also be a vulnerability, as someone who is part of this custodial account could replace the memo before asking the provider to sign the challenge for them.   hm.

**Comment by leighmcculloch** [comment]
Any SEP10 authentication process between a custodial wallet and an anchor-server the anchor-client should be the wallet backend, not on the wallet frontend. There's no reason that I can think of to expose signed proofs to the frontend where it might be intercepted and exploited. I don't think the authentication really needs to be concerned with who the ultimate user is. The authentication only proves possession of a destination account and the memo is not needed for that.

Outside of the authentication we should make it possible for the anchor-client to request a memo gets used by the anchor-server for the deposit, but that would be part of SEP24/26 I think.

What am I missing?

**Comment by msfeldstein** [comment]
Yeah i guess that makes sense.  The only thing missing then is for the `/transactions` endpoint it uses the JWT to identify which user is making the request, so the anchor-server would need to then filter out the results to whichever of their customers made the request.  If the JWT had the memo in it, the client could use the JWT to request transaction statuses directly

**Comment by leighmcculloch** [comment]
This sounds like the user will be contacting the anchor's `/transactions` directly with a JWT that's been retrieved by the wallet backend. I think there are some problems with this. By using SEP-10 the wallet backend is proving to the anchor that it is in possession of an account, then the anchor is transferring that proof to a JWT. I'm a little worried about the backend sharing with the frontend any credentials including that JWT that acts as a proof of possession of an account, but I can't think of any specific ways this could be exploited, it just feels like there could be something here.

I can see how if we do as you say and include the memo into the SEP-10 authentication process, then that proof would only pertain to that memo.

>With this however, there's no cryptographic link between the memo and who is signing for it. There's no cryptographic link between the memo, and the actual signature

The memo is still part of the transaction and so will be signed with the custodial account key. The user doesn't need to prove ownership of anything since the user doesn't actually possess any account, so I think this is as much proof as is going to exist and is required.

Do we expect a custodial wallet will want the user interacting directly with the anchor's API? I would think a custodial wallet would be handling those interactions on the backend since it's essentially a closed system behind the custodial / shared account.

**Comment by msfeldstein** [comment]
You're right, especially if the usage of SEP10 expands and the 'proof of ownership' gains more powers, it may be a problem.

I think we need some input from someone who's built a custodial wallet to chime in here...

**Comment by nebolsin** [comment]
I think multiplexed addresses could be a good solution here, when the proposal finally settles as a [SEP-23](https://github.com/stellar/stellar-protocol/pull/405/files) or a CAP.

**Comment by JakeUrban** [comment]
#726 will fix this problem. In the far future when multiplexed accounts are supported in Horizon supporting them within SEP-10 will be trivial.
