### ISSUE TITLE
Discussion: SEP26 Non-interactive Anchor/Wallet Asset Transfer

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#484]
SEP26 was submitted as the non-interactive counterpoint to SEP24's interactive transfer protocol.  It uses some more forward thinking infrastructure, such as SEP27's Asset Information Server

Please discuss thoughts on this proposal here

https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0026.md

**Comment by msfeldstein** [comment]
Additional discussion: https://github.com/stellar/stellar-protocol/pull/460

**Comment by s-a-y** [comment]
1. I still don't understand why /deposit endpoint doesn't require an amount. But at the same time, there is a "fee" field in response (calculated fee). How can you calculate it without the amount?
We could do it the same way as for withdrawal.
2. Maybe responses for /deposit and /withdraw should have `id` field analogous to sep24. Just to make it easier for wallets to handle it in the same way (keep id to query /transaction endpoint later)

**Comment by s-a-y** [comment]
Regarding 1. Fritz explained to me in private, that you can request amount using optional form field using sep27. The fee is optional in response, therefore most likely won't be present unless anchor can actually calculate the specific amount.

**Comment by dolcalmi** [comment]
please reference SEP26 in SEP006.... and next time it would be nice not to deprecate before finalizing the specification

**Comment by andywer** [comment]
Hey there!

At SatoshiPay we would like to help move SEP-26 forward. Currently we need to stick to the anchors' SEP-6 implementations for our new B2B platform as anchors don't seem to implement SEP-26 yet and we need a non-interactive flow.

**I have got one question up-front, though:**

Why has the description of custom fields been moved from the `/info` endpoint to the asset info one? I would like to argue that this makes it harder for anchors to implement as they now need to implement the SEP-27 asset info endpoint in order to have a usable SEP-26 implementation.

Furthermore that information is only useful for a SEP-26 setting, hence it's not quite clear why it would reside in a general-purpose asset info endpoint instead of in one of the transfer server's.

The benefit if this decision is not clear to me as a reader of those specs. Especially since including those fields in the `/info` response doesn't interfere with SEP-24 and the format outlined in SEP-27 seems to be backwards-compatible to SEP-6 on first glance.

Maybe one of you guys can shine a light on that 😉

**Comment by andywer** [comment]
Hi @msfeldstein! I would like to propose some updates to the spec as a PR. Those are the first low-hanging fruits from my point of view:

* Change the routes to `/transactions/{deposit,withdraw}/non-interactive`, similar to SEP-24, as they are not backwards-compatible to the SEP-6 endpoints
* The SEP-27 examples make the spec hard to digest – would put them in collapsible `<details>` elements to make the doc easier to read

Will prepare a PR. Happy to hear some early feedback 🙂

**Comment by marcinx** [comment]
Hi all! @gdini2003 and I opened PR #637 to make the KYC flow in SEP-26 non-interactive. Oddly, it currently follows the interactive flow of SEP-6.
