### ISSUE TITLE
Path payment that allows you to specify how much you will send

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-protocol#49]
Right now you can only specify how much they will receive and how much you ultimately send varies. There are use cases where you really want to do it the other way, specify how much you send and vary how much is received.

**Comment by MonsieurNicolas** [comment]
Can you expand on scenarios - properties on Offers themselves may help and be more generic

**Comment by jedmccaleb** [comment]
I have $10 and I want to send all of it to you but you only want EUR. 
Actually maybe this should just be accomplished in 2 steps. a normal order to convert the USD -> EUR and then a payment. A little gross since you have to also add/remove the trust line to EUR.

**Comment by istrau2** [comment]
@jedmccaleb I don't think that 2 step method works though (because an offer is a limit order and path payment is a market order).

To me, a path payment is mechanism for conversion between assets **at market rate**, a very useful function. While there are obviously scenarios where you want to specify the destination amount (like paying a merchant in their preferred asset), there are a host of scenarios where one would want to specify the source amount.

I think we should think about hard forking (or whatever the term is in stellar) to modify the protocol.

**Comment by jedmccaleb** [comment]
a limit order is a market order if you set the limit low enough.

**Comment by istrau2** [comment]
@jedmccaleb
Yeah, I guess you are right about the real issue (not having the two operations be atomic).

Couple of points with your proposed solution:

1. Why solve it that way? It seems like quite a roundabout way of solving the issue (as opposed to simply allowing a path payment that specifies a source amount)?

2. Also, I think that kind of a series of operations would run into issues if the user already has a balance of EUR (then that balance would get sent as well). Additionally, it seems to me that there is no way to specify a maximum amount on the payment operation since you don't know what cumulative rate the trade will execute at ahead of time.

**Comment by jedmccaleb** [comment]
Yeah I'm open to a protocol change to add this I just want to make sure we need to first

**Comment by istrau2** [comment]
@jedmccaleb Wouldn't adding a maximum amount for a payment require a protocol change as well?

**Comment by MonsieurNicolas** [comment]
reason I was asking about offers and clarification on scenarios in the first place was that I was thinking we could create offers that cannot be taken partially for example which seems like a very useful building block.

**Comment by jonjove** [comment]
Addressed by CAP-24
