### ISSUE TITLE
SEP-0007 links opening issues in various operating systems and browsers

### ISSUE THREAD

**Issue by dmgmyza** [stellar/stellar-protocol#491]
1. Desktop application can register itself as a sep-7 handler on a system level (Depending on the operating system).
In this case, user doesn't have even option to choose any other sep-7 wallets on their desktop.
This is because sep-7 system handlers are executed before browser handlers.

Chrome and Safari as an example. These browsers (on Mac OS) open the last used desktop app that supports web+stellar links. If no desktop apps are installed, the default handler website will be used (no selection presented).

2. Apple mobile devices and SEP-7 links:
The logic of app selection for such links opening is not specified by Apple at all.

Please, check [this table](https://docs.google.com/spreadsheets/d/16yHy3pP0_jLlxfVjUv-JCIaU7fz7xnFAz325hdc6xo0/edit?folder=0ABGDDD6SL65NUk9PVA#gid=0) for the detailed comparison of SEP-7 links flow in different operating systems and browsers.

Quick preview:
![image](https://user-images.githubusercontent.com/3429825/70268160-f1678e00-17b0-11ea-9b83-2b5811b9a83a.png)

**Comment by pitsevich** [comment]
To summarize, the users sometimes have limited control over which app is opened upon clicking on web+stellar link.

1. This is quite problematic for iOS devices.
2. On desktop, when application registers itself to handle web+stellar links at system level, it may overwrite the previous handler app. Changing the handler back often will be difficult by the user, because the OS does not provide easy ways to see current handler or change it. The applications often make updates to the handler without any confirmations from the user, providing no functionality to opt out.

**Comment by tomerweller** [comment]
This is concerning. Especially iOS and desktop Chrome.  
@MisterTicot, @nikhilsaraf, thoughts?

**Comment by MisterTicot** [comment]
You have two ways of linking txs: custom URI scheme (like sep7) or universal links (like Cosmic.link).

The drawback of universal links is that you have to target a specific service, which means you need a relay between apps and wallets when app is not aware of which wallet to contact.

This can be mitigated by giving that information to the apps, shortcutting the need for a relay. Alternatively, a solution can be implemented that guarantees relay integrity.

For more details about this design you can check https://cosmic.link/#about

It should be noted that this is not all that bad as it prevents request hi-jacking which is an issue with Custom URI scheme.


What one should keep in mind is that, unlike universal links, Custom URI scheme has never been designed as secure component, but rather as a convenient way to pass a request to its default handler.

In crypto, it has first used for payment requests by Bitcoin (BIP21 `bitcoin:` adresses), but that proposal is from early '12, when BTC was worth $6. The crypto userland did not had the same security requirements than today.

The other issue with custom URIs is indeed the poor UX: Android & iOs doesn't allow webapps to register as handlers, Ubuntu Chrome will refuse to re-register a handler if you used it once but then replaced it by another one. People who haven't registered a handler yet are left clueless in front of a cryptic error page. People using two or more wallets are also left clueless in most setups.

It is worth noting that this situation is not likely to improve, as both Apple & Google switched to Universal Link as the preferred way to communicate requests to applications.

----

My proposal regarding this situation is to turn CosmicLink _XDR link_ into a standard. This format is similar to what sep7 did, but is compatible with universal links & has things such a custom network and source-less requests figured out. It won't be much work to switch due to similarities between both solutions:

https://cosmic.plus/#view:js-cosmic-lib/web/doc/tutorial-10-specs-query.html

Worth nothing, it encodes the request into a query so it can still be used with `web+stellar:` links, but application-specific links should be preferred for the reasons I mentioned.

This feature is an important security improvement, and requires a large adoption to make sense. I think it's better to push for something like this that is simple enough to implement and that'll cover 98% of use cases, so implementators can follow up.

Sophisticated pseudo-operations & transactions templates can be handled app-side, or implemented at a later time when everyone already figured out the basics.
________________________________

**Comment by MisterTicot** [comment]
(updated my previous comment so the proposed solution displays on GitHub website)

**Comment by tomerweller** [comment]
Thanks @MisterTicot. Sorry for the delayed response. 

I'm looking at information from cosmic.link and specifically at: 

> What if Cosmic.link gets compromised?
> Cosmic.link doesn't use any centralized server or database - so really, there's nothing to crack. In fact, as everything happens on your side, Cosmic.link doesn't have access to users' activity or personal data at all.

What stops a malicious cosmic.link from mutating a user's transaction to drain their account?

**Comment by MisterTicot** [comment]
Good question: nothing but it's not an issue.

I've worked on that case but chose not to mention it on the public page
because I did not know how to put it in a way that is easy to understand.
It's pleasant to see that you spotted that very point.

I designed CosmicLink as an imitation of hardware wallets flow. In other
words, the goal is to use software wallets the same way we use hw wallet
today (can log into many apps, and sign tx securely).

Ultimately, apps will get pubkeys with an API call and the user will be
asked if she's willing to share it.

In some cases, the tx request will go directly to her wallet (direct
app->wallet connection).

In other cases, a step through Cosmic.link is required. It can be visible
(showing up the GUI) or invisible (background conversion CosmicLink->Sep7).

A malicious transaction can come from two parties: the application itself
or Cosmic.link.

This is the same attack than sending a malicious transaction to a Ledger
Wallet, and in Ledger security model that attack is meant to be repelled by
the user noticing the transaction is not what it should, and rejecting it.

Similarly, any wallet Cosmic.link link to offers a view of the transaction
before signing: so we're on a known ground as so far it has worked pretty
well for Ledger wallet users.

Whatever way you put it, if the wallet itself is genuine, users end up
seeing the transaction before signing.

Now, here's my point:

1. Cosmic.link is pretty well secured.
2. Crafting a malicious Cosmic.link (or Sep7 link) achieves an attack that
has almost the same success rate. (Can work only against blind signers)

Conclusion: while the malicious tx case is worth thinking about, taking
over Cosmic.link to run this attack has a high cost and low additional
profitability, which means that realistically it won't happen.

In any case, we can assume the "average" user is less careful than most
Ledger users, and that designing protections against malicious tx request
at the wallet level is something we want to do.

It can be asking for confirmation when sending funds to new addresses,
warning against signers changes, warning against trustlining esoteric
assets and so on.

A "pro" mode could remove all those securities for people who know what
they're doing.


Le lun. 23 déc. 2019 à 19:32, tomerweller <notifications@github.com> a
écrit :

**Comment by tomerweller** [comment]
Good points. However, I disagree with the claim that that's not an issue.

DNS hijacking is not uncommon in our world (myetherwallet, blackwallet, etc) so that attack vector shouldn't be ignored. The comparison to a hardware wallet is problematic as they are not susceptible to these types of attacks.

**Comment by MisterTicot** [comment]
Let me clarify this point: I never said to ignore the issue, and I just
made proposals about how to mitigate it.

What I'm saying is that you can run the exact same attack for free by
crafting malicious transaction requests - so why would you bother with a
DNS attack, which would require crafting a valid Cosmic.link certificate as
well as I have HSTS enabled?

(Unfortunately, MyEtherWallet did not enable this basic protection which
would have blocked users
from navigating to the compromised website)

The generic attack is as follows:
1. Send a malicious tx request to user wallet.
2. Hope that user doesn't notice the tx is malicious and signs it.

HW wallets are subject to the exact same attack as apps can send malicious
tx requests to those as wel.

The fact that it happens through a compromised app, a malicious request or
a DNS attack does not change the attack flow much.



Le lun. 23 déc. 2019 à 20:36, tomerweller <notifications@github.com> a
écrit :
