### ISSUE TITLE
SEP24: No security around callback POSTs.

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#493]
Sep24 offers a way for anchors to call back to a wallet with updated transaction state and details.  This is useful for communicating the state of the interactive flow, which the wallet has no insight into.  This endpoint needs some type of security to ensure that the callbacks being POSTed to a wallets servers are indeed the anchor, otherwise a malicious actor can simply call back to the wallet and pretend to be the anchor to update the state of transactions.

**Comment by msfeldstein** [comment]
When we re-think this it may make sense to expand it to a webhook style callback allowing for continued updates, rather than simply for signalling the end of interactive flow.  This would allow wallets to enable push notifications for transaction state changes

**Comment by leighmcculloch** [comment]
In similar systems the existing design of the callback would survive. The backend would be able to verify the contents of the callback by calling the transactions endpoint and verifying the state of the transaction or retrieving the event, and confirming it is legit before taking any meaningful actions.

In our case this is not possible because the wallet server has no credentials to speak to the transfer server on behalf of the wallet client. It's unlikely a wallet client will share authentication credentials with the wallet server, and we shouldn't recommend that.
