### ISSUE TITLE
stellar.toml: support multiple versions

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#514]
The current [stellar.toml spec](https://github.com/stellar/stellar-protocol/pull/512) makes it difficult to introduce breaking changes.

I propose allowing anchors to expose multiple versions of their `stellar.toml` file using a simple version based pattern for the url path: `/.well-known/stellar.v{major_version}.toml`.

Examples: `/.well-known/stellar.v1.toml`, `/.well-known/stellar.v2.toml`, etc.

For convenience and backward compaitbility, the current path: `/.well-known/stellar.toml` could redirect to the latest version. 

Clients could build with a specific version in mind and when they fetch the configuration they know what they're getting. 

This would make it easier to introduce things like https://github.com/stellar/stellar-protocol/pull/512#issuecomment-574421368

I can think of alternatives like adding expected version in the request header, but that sounds like a more complex implementation. Any other ideas?

**Comment by leighmcculloch** [comment]
I don't think we should introduce multiple files, and instead we should embrace additive changes to the existing TOML file format.

Multiple files for different versions doesn't make the effort of reducing breaking changes any less easier. It spreads those difficult changes across multiple files. While this might make the definition of what is in the file a little bit clearer, or the file look a lot prettier, it won't reduce the effort required to maintain such a change because the more effort is required to maintain both files.

See below for some reasoning:

>makes it difficult to introduce breaking changes

Having multiple files is going to make interacting with TOML files complicated for the producer and consumers. The producer has to maintain both files which increases the chance of human error.

Most breaking changes can be reduced to additive changes and if we embrace additive changes they are not difficult to introduce.

For example, if we need a new way to define something we can be okay with saying you can define it the new way while allowing the old way. You mention it would make it easier to introduce the changes in #512 by allowing us to replace `TRANSFER_SERVER` with:
```
TRANSFER_SERVER_v1="https://api.domain.com/v1"
TRANSFER_SERVER_v2="https://api.domain.com/v2" 
```
or:
```
[[TRANSFER_SERVERS]]
URL="https://api.domain.com/v1"
VERSION="1.1.0"

[[TRANSFER_SERVERS]]
URL="https://api.domain.com/v2"
VERSION="2.0.0"
```
But using an additive approach would be simple and easy to understand and would look like this:
```
TRANSFER_SERVER="https://api.domain.com/v1"
TRANSFER_SERVER_v2="https://api.domain.com/v2" 
```
Or this:
```
TRANSFER_SERVER="https://api.domain.com/v1"

[[TRANSFER_SERVERS]]
URL="https://api.domain.com/v1"
VERSION="1.1.0"

[[TRANSFER_SERVERS]]
URL="https://api.domain.com/v2"
VERSION="2.0.0"
```

>For convenience and backward compaitbility, the current path: `/.well-known/stellar.toml` could redirect to the latest version.

To make this change backward compatible we'd need to have the current path point to v1, otherwise whenever someone adds support for v2 anyone pointing to this URL would break.

**Comment by tomerweller** [comment]
@leighmcculloch, thanks. Closing because you're right.

**Comment by tomerweller** [comment]
This does make me feel like we've handling `stellar.toml` changes wrong. We should have marked fields as deprecated and keep them around, rather than get rid of them.

**Comment by tomerweller** [comment]
cc @rice2000

**Comment by leighmcculloch** [comment]
I think the approach we take depends on the situation.

If we have some certainty that few people are using a field I think we can make a calculated decision to remove a field.

But most of the time we should attempt to keep a field valid as in the example above where we end up with `TRANSFER_SERVER` and `TRANSFER_SERVER_v2` rather than adding `TRANSFER_SERVER_v1` as well.

If we absolutely need to replace a field then deprecating makes sense. e.g. Replacing a single `TRANSFER_SERVER` field with multiple `TRANSFER_SERVERS` sections.
