### ISSUE TITLE
SEP24: status code for SEP10 JWT

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#537]
As described in https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#5-authentication-required, the Anchor must respond with a 403 Forbidden response if the SEP10 JWT is missing from the request.
I suggest changing that section to allow two possible responses:
1) 401 Unauthenticated: Missing or invalid JWT token in the request
Status would be `401` since we don't know the identity of the requester
2) 403 Forbidden: JWT expired
Status would be `403` since we do know the identity of the requester (`pub` field from the JWT) but the token is expired, therefore the Wallet must get a new SEP10 token.

Wallets would then be allowed to only renew the SEP10 token when necessary, instead of always getting a new SEP10 token before each SEP24 request.

**Comment by yuriescl** [comment]
Created this issue as a Bug but I'm not sure if it's the proper label. It's just a suggestion.

**Comment by leighmcculloch** [comment]
>Status would be 403 since we do know the identity of the requester

Returning a 403 if the JWT matches an account might leak information to someone who has managed to get ahold of an old JWT. It would allow someone who has an old JWT to check if an account still exists.

I think it's safer to treat an expired token like an invalid token. A service should expose no information to an unauthenticated user.

If we're being pure about it I would argue that the status code in the case that authentication required should be 401, since the server does not know who the user is if the JWT is expired, and 403 or 404 should be used for an authenticated user who is attempting to access a resource they are not permitted to access.

These sections of [RFC2616](https://tools.ietf.org/html/rfc2616) are relevant:
- [401 Unauthorized](https://tools.ietf.org/html/rfc2616#section-10.4.2)
- [403 Forbidden](https://tools.ietf.org/html/rfc2616#section-10.4.4)
- [Authorization](https://tools.ietf.org/html/rfc2616#section-14.8)

**Comment by yuriescl** [comment]
Indeed, it is more secure to have a single error. Thanks for the response.
