### ISSUE TITLE
SEP-0030: Add endpoints and procedure for rotating signers

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-protocol#595]
### What
Add endpoints and procedure for rotating signers when a SEP-30 server thinks it would be a good idea to rotate a signer.

### Why
SEP-30 doesn't provide any specific procedures or instructions for how to rotate the signer of an account. A client is always able to rotate the signer of their account by deleting an accounts registration with a SEP-30 server then re-registering the account. While this works there are two gaps missing:
- There is no way for a server to initiate or recommend key rotation and ideally it should have that capability since it is the one in control of the signer key. 
- There is no way for the client to perform key rotation without the account being unregistered for a period of time. If there was a catastrophe between delete and register the account would not be registered with the recoverysigner.

**Comment by johansten** [comment]
I' not sure where to discuss this SEP, but have you looked at voting pools? They seem similar a concept.

You'd have an account, signed fully by a bunch of delegate signers, w/ some appropriate threshold, and when you as an owner of the account wants to transact, you sign a message and send it to all of the delegates, who sign it for you.

Where the similarities really come in is that since there's no direct connection between what account you use to sign with for the delegates, if you lose control of that signing key the delegates can upgrade you to a new key, provided you go through some sort of more-or-less rigorous identity check.

**Comment by leighmcculloch** [comment]
@johansten Thanks for pointing out we don't have a good place to discuss SEP-30 in general. I've started [a thread over on the stellar-dev mailing list](https://groups.google.com/forum/#!topic/stellar-dev/SFr2dHBZlsY). Would you be able to post your thoughts about voting pools there? Thanks!
