### ISSUE TITLE
make it less likely for accounts to get stuck

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-protocol#62]
Right now the clients have to jump through a lot of hoops to prevent accounts from getting stuck:
https://github.com/irisli/stellarterm/issues/76
After stuck it is a really bad user experience to get the account usable again.

This mainly results from selling XLM for some other asset.

The proposal is to leave enough lumens in your account to pay the fee for 1000txs when:
- an offer of yours selling XLM crosses.
- you send lumens

This way the only way an account can get stuck is if they send/sell all the lumens they can and then do 1000 more txs.

**Comment by MonsieurNicolas** [comment]
I think we need to think about this a bit more:
an account getting stuck because of an XLM offer is actually very unlikely as in the common case, the offer gets deleted as soon as it reaches the reserve balance, causing the reserve to get lowered.

I imagine that users are probably much more likely to lose their secret key than run into those edge cases - and I am not sure how we would solve that problem just yet (and solving this may give us an idea on how to solve this particular problem of account getting stuck because of the lack of funds).
For that particular class of problems, the solution may be in leveraging pre-signed transactions using new semantics on the requirement from the signers and bumpseq like operations.

**Comment by jedmccaleb** [comment]
> an account getting stuck because of an XLM offer is actually very unlikely
actually happens all the time. For example the case where you are not placing an order but just consuming existing orders. You will be left sad with nary a spare stroop.

**Comment by MonsieurNicolas** [comment]
Oh you’re talking about manageOffer that has a buggy/unintuitive behavior right now when trying to create an offer to sell XLMs. When that is fixed it won’t let you get into more trouble than having outstanding offers.

**Comment by jedmccaleb** [comment]
How are you imagining changing manageOffer? You could still get stuck by sending away too many lumens

**Comment by MonsieurNicolas** [comment]
I opened an issue and a PR that explains the changes to manage offer see https://github.com/stellar/stellar-core/pull/1431

**Comment by lenondupe** [comment]
I suppose it's not an option to make operations that release resources, such as canceling an offer and removing a data entry feeless? As these will not be propagated through the network without there first being a corresponding operation that *sets* the data and *creates* the offer it seems they cannot be used to spam the network for free.

**Comment by jedmccaleb** [comment]
the changes from CAP3(https://github.com/stellar/stellar-protocol/blob/master/core/cap-0003.md) make this way less necessary so closing
