### ISSUE TITLE
SEP-007 (license to curl) ambiguities in `replace` parameter

### ISSUE THREAD

**Issue by Synesso** [stellar/stellar-protocol#644]
### What version are you using?

SEP-0007 v2.0.0

### Problem

No guidance is given to valid structure of _reference_identifier_ and _hint_ fields in the `replace` parameter of the SEP-0007 URL. This value is logically structured with invariants that are ambiguous.  It is perhaps easiest to define this problem via examples.

**reference_identifer mismatch**
`replace=tx.sourceAccount:X;Y:Source Account`
The reference identifier set in the _field to id_ half should match the reference identifier set in the _id to hint_ half exactly. In this example, `{X} != {Y}`

**Separators in hints**
`replace=tx.sourceAccount:Signing Account,operations[0].sourceAccount:Paying Account;Signing Account:If you please, the signing source account goes here,Paying Account:The account Id for the payer`

Commas are important delineators in the structure, but also useful characters in the hints (and perhaps also labels). There should be guidance on how to differentiate between separators and content. 

`replace=tx.sourceAccount:Signing Account,operations[0].sourceAccount:Paying Account;Signing Account:The signing source account,Paying Account:The account Id: paying account`

Similarly, colons can be employed in hints.

Semi-colons in hints might also cause confusion.

### What did you expect to see?

Ideally a defined structure that avoids ambiguity and redundancy; or more detailed parsing implementation guides in the SEP.

JSON might have worked well as the value here. If it's too late to tighten up that value, then perhaps the SEP can be modified to include parsing guidelines.

**Comment by nikhilsaraf** [comment]
Hi! Thanks for raising these issues. I'll try and address them as best as I can and if we conclude that the SEP needs modification then that's on the table.

#### reference_identifer mismatch
>  replace=tx.sourceAccount:X;Y:Source Account
The reference identifier set in the field to id half should match the reference identifier set in the id to hint half exactly. In this example, {X} != {Y}

The example quoted above is invalid, for the reason your mentioned, i.e. {X} != {Y}

We should use the [example specified in the SEP](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md#operation-tx), quoted for reference:
> sourceAccount:X,operations[0].sourceAccount:Y,operations[1].destination:Y;X:account from where you want to pay fees,Y:account that needs the trustline and which will receive the new tokens

Here, we specify two variables: `X` and `Y`, both of which are on the left hand side of the `;` separator and have an corresponding explanation on the right hand side. Also, `Y` is repeated twice on the left hand side to indicate that it should be the same value for both those fields (`operations[0].sourceAccount` and `operations[1].destination`)

My intention was to make the above clear from the written text in the SEP, but if that's not clear I'm happy to modify the SEP to more clearly convey this intention. If you have suggestions for this please let me know and we can work on a fix for this.

#### Separators in hints
While thinking about separators, we decided to disallow the following characters in hints: colons (`:`), semi-colons (`;`), and commas (`,`) to avoid confusion. This is not explicitly specified in the SEP under the replace parameter section, but it probably should be made explicit.

The reason is to avoid confusion about how to encode these characters. While these characters would be useful in the hints, it would be fairly straightforward to define hints that do not require these characters. This would require producers of the SEP-7 URI to have well-thought out hints which is the idea of the hints since they are user-facing.

However, if the community prefers we can fallback to an escape sequence for these three characters. We could also free up the semicolon character (`;`) by repeating the comma (`,`) character twice. i.e `sourceAccount:A,operations[0].sourceAccount:B,,A:explain,B:explain` instead of `sourceAccount:A,operations[0].sourceAccount:B;A:explain,B:explain` (notice `,,` used instead of `;`). (Or we can free up the comma (`,`) character and use the semicolon (`;`) character as the second separator.

#### Note
Also, please note that you should not prefix the replace text with `tx` as is done in [Txrep (SEP-0011)](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0011.md). This can be seen in the [description for `replace` param in the SEP](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md#operation-tx) as well.

#### Parsing Tips

As for parsing the replace text, it should be easily achievable with some string `split` commands, which all languages support.

In its current state, developers can first split by semicolon, then by commas, and finally by colons. Example pseudocode:
```
rawReplaceField = url.getField("replace")
replaceString = urlDecodedString(rawReplaceField)

outerParts = replaceString.split(";")
mappings = outerParts[0]
explanations = outerParts[1]

mappingList = mappings.split(",")
explanationsList = mappings.split(",")

// extract fields and variables from mappingList (left hand side)
for item in mappingList:
    mapParts = item.split(":")
    txRepField = mapParts[0]
    mappedVariable = mapParts[1]

// extract variables and explanations from explanationsList (right hand side)
for item in explanationsList:
    explanationParts = item.split(":")
    mappedVariable = explanationParts[0]
    explanationDescription = explanationParts[1]
```

After this explanation, please let me know what is most helpful to add into the SEP and I can make that change.

Thanks!

**Comment by Synesso** [comment]
Thank you.

I attempted to address *reference_identifer mismatch* in
https://github.com/stellar/stellar-protocol/pull/664

*Separators in hints* might be addressed with unix style single quoting. -
'value that can contain anything except another single quote'. If a single
quote is required in the hint, then the typographic variant can be used -
’

**Comment by nikhilsaraf** [comment]
@Synesso, I approved the PR #664 
I didn't fully understand the suggestion above for separators in hints, but feel free to add a PR or elaborate on the explanation.
