### ISSUE TITLE
SEP-24: Wallet Attribution - verifying users' client applications

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#685]
**Problem Statement**
There has been ongoing discussion among wallets and anchors about how to verify that a particular user, or rather a particular stellar account, uses a specific client wallet application when making SEP-24 deposits and withdrawals.

The benefits of this would be:
- improved BI analytics for anchors
- the ability to process users from specific wallet applications differently

For example, Anchor A could decide to not charge any fees for users from Wallet B.

**Solution**
One solution being discussed uses [SEP-2](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0002.md), specifically reverse federation lookup. The main idea is that when a user (through a wallet) makes a deposit request with an anchor, the anchor can call the wallet's federation server to verify that the stellar address used in the deposit request belongs to a user of the wallet application.

This solution would require two things from the wallet organization:
- Every stellar account the wallet acts on behalf of must have its `home_domain` option set to the home domain of the wallet's [stellar.toml](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md)
- The wallet must maintain a SEP-2 federation server that allows authenticated clients to make requests using the `id` parameter

The flow would be as follows:
1. The user (using Wallet A) initiates a deposit with Anchor B
1. Anchor B requests the account information from Horizon
1. Anchor B uses the `home_domain` option on the account to find the `FEDERATION_SERVER` URL for the wallet
1. Anchor B makes a request to the server for the account requesting a deposit
1. Wallet A responds with a valid SEP-2 response containing information on the user

Anchor B could then not charge a fee for the user, or simply update its usage analytics.

**Discussion**
This issue is a place for interested parties to weigh in on this solution. If accepted by the ecosystem, SEP-24 (and potentially other relevant SEPs) will be updated to include a section on wallet's hosting reverse federation lookup servers.

**Comment by leighmcculloch** [comment]
I think one issue is that this relies on the optional reverse lookup feature of a federation server, looking up a username from a Stellar address. Not all federation servers will implement this. Some will not want to support reverse lookup to prevent someone from discovering usernames for addresses.

We could address this concern without any changes to SEP-2, by saying that a federation server that wishes to prevent exposure of a username with reverse lookup should still return a valid response for reverse lookup, but instead of the real username, use the Stellar address as the username.

Example:
```
https://example.com?q=GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ&type=id
```
```
{
  "stellar_address": "GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ*example.com",
  "account_id": "GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ"
}
```

A server doing this would need to support looking using the Stellar address as the username though.

**Comment by msfeldstein** [comment]
Another solution might be to have the anchors give the wallets an API key to use when making requests to their server.  This would prevent bad actors from pretending to be a different wallet.

The downside to this might be that we need to store API secrets on device, and that's a new security concern that wasn't there before.  If we don't want to add a proxy server for signing these requests, we would need to securely store an API secret on device.  Does anyone know of any prior art or best practices on this?

**Comment by tomerweller** [comment]
Regarding BI: the `wallet_url` and `wallet_name` fields of sep24 requests might be sufficient (similar to how the HTTP `User-Agent` header is used for analytics). But that won't work for any wallet/anchor agreements that need strict tracking.  

Reverse federation indeed looks like a low hanging fruit to solve this. It does, however, change the semantics of reverse federation. Instead of just answering the question of "what's the federated address for this account?" it also answers the question of "Do you take ownership of this account?". Not the end of the world but that needs to be clarified in SEP2.

@msfeldstein I'm not aware of secure ways to distribute a static key to clients. Following that thread though - maybe the client can ask for a one-time apikey from the wallet's backend before initiating the request? Though that adds a bunch of operational complexity

**Comment by pitsevich** [comment]
Changes to the reverse federation response are rather minor. 
We'd be happy to support that and implement this in LOBSTR and StellarTerm.

Some comments on the privacy concerns that @leighmcculloch mentioned -- we've been also thinking about that.
Our plan is to give the control over that to the users, so it would be their choice to select whether their federation address is exposed in the reverse federation response or not.

So, the way I see it, for users who are okay with exposing federated address the response would be:

```https://example.com?q=GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ&type=id```

```{
  "stellar_address": "alice*example.com",
  "account_id": "GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ"
}
```
If the user would later decide to prefer to keep it private that would change to:
```{
  "stellar_address": "GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ*example.com",
  "account_id": "GCIBUCGPOHWMMMFPFTDWBSVHQRT4DIBJ7AD6BZJYDITBK2LCVBYW7HUQ"
}
```

**Comment by andywer** [comment]
Looks like an elegant approach so far. I am just wondering what to do if the user wants to use an alternative federation server for the account (like their own).

Maybe setting the `home_domain` on the account isn't even necessary? When the wallet send a request with a `wallet_url` to the anchor's SEP-24 transfer server, the transfer server could just look up that `wallet_url`'s domain's federation server to verify that the account has been registered with the wallet provider, no matter what federation address the account is currently using.

**Comment by JakeUrban** [comment]
Your comments about using `wallet_url` are true @andywer but it requires the optional `wallet_url` parameter. As an anchor, I'd want a way to find the federation server regardless of whether or not the client specified the URL to use in the request. 

I also wouldn't want clients to be able to offer different federation servers from whats specified in their account on Horizon. The value from this change would be the anchor's ability to confirm _with the wallet_ that the user "belongs" to them. Any federation server other than the wallet's wouldn't be trusted by the anchor. It also lets the `home_domain` be the single source of truth for the account creator.

**Comment by JakeUrban** [comment]
Since the changes described here largely pertain to the wallet & anchor's functionalities, I'm going to add guidance on this subject to SEP-24 and SEP-6 instead of adding to the SEP-2 document. There are no SEP-2 changes other than the ability for wallets to change the stellar_address based on the user's wallet settings. A small PR for that recommendation could be necessary too.

**Comment by JakeUrban** [comment]
One thing I want to note here which I think is pretty important is that this solution does not enable anchors to verify that the user is using a wallet application _for a particular transaction_. A user could create an account with Lobstr, get the credentials, and make a deposit or withdraw with a different wallet that doesn't change the user's `home_domain`.

To me this seems to be a major limitation. Anchors almost certainly would like to verify the wallet used per-transaction. What do you all think?

**Comment by leighmcculloch** [comment]
Federation:

>it also answers the question of "Do you take ownership of this account?"

>this solution does not enable anchors to verify that the user is using a wallet application for a particular transaction

I think this statement `ownership of this account` and @JakeUrban's question highlights for me that I've been conflating account ownership and wallet use when thinking about this issue.

Based on the information in this issue, this issue is concerned with what wallet software is making the request in that moment, and not what wallet is "owning" the account, or created the account, or is sponsoring the account. In practice most people are probably going to use an account with one wallet, but none of the SEPs make that assumption today and we should probably avoid introducing that assumption, even though the federation solution is simple.

---

API Key:

>have the anchors give the wallets an API key to use when making requests to their server

The biggest issue I see with storing a single API key is not that the secret might be exposed, it's that the wallet will not be able to play any role in protecting their own product from abusing anchors because the wallet will provide a single API key for all of their users to share. While the anchor could ban users who are bad actors by the address in the SEP-10 JWT that leaves all the responsibility on the anchor.

---

Session-Based Auth:

Another option to consider is session based authentication between the wallet and the anchor, where the wallet server issues a short-lived session authentication token to the wallet client that the anchor can use to prove the request is coming from the wallet.

It would have these benefits:
- Updates to keys do not require users to download new apps since the app holds no keys.
- No sharing of keys.
- Session tokens could be signed using asymmetric keys, reversing the need for the anchor to issue keys. The wallet publishes the key at some common endpoint, maybe at a URL specified in the wallets stellar.toml.
- There is no need for the anchor to make outgoing requests to other servers to validate the claim/proof, assuming they already have the wallet's public key.
- Session tokens could be bound between the three parties: wallet server, user's Stellar account, and the anchor, so the session token is only used with that specific configuration, by including the user's Stellar account address and the audience (the anchor) in the signed token, and being signed by the wallet server.
- How a wallet manages their session tokens is out-of-scope for the anchor, and wallets have flexibility for how they implement that.
- A wallet server can prevent bad actors on their platform from receiving new session tokens without impacting any other user.
- Session tokens could be only issued to user of the wallet who are already authenticated with the wallet.
- Wallet's are motivated to prevent bad actors at the source (their app) since anchors could stop accepting a wallets session tokens.
- JWTs and their associated standards can define the formats of the tokens, as well as the formats for sharing and publishing keys (RFC7517 JSON Web Key's and Keysets) which setup a solution using them to handle things like key rotation well, etc.

This would be a little more work, but there's not many unknowns or much to invent to make this to work.

**Comment by JakeUrban** [comment]
A high-level overview of what the solution would entail.

## A New SEP

This protocol would outline how a wallet client could receive a JSON Web Signature ([RFC 7515](https://tools.ietf.org/html/rfc7515)) that allows anchor servers to verify that the _client requesting the relevant operation is owned by the wallet server_. In this context thats a SEP-24 deposit or withdraw, but could be used in other contexts.

This SEP would be very similar to SEP-10, except for the following adjustments:
- the client's request for a challenge transaction must include a transaction ID returned from the anchor server
- the wallet server must include the transaction ID as the challenge transaction's memo
- the wallet server must return a serialized JWS, not a JWT. JWS's allow the anchor server to verify the token came from the wallet server.
- The decoded representation of the JWS returned must include a `tid` key containing the transaction ID returned from the anchor server

## Modification to SEP-24

An additional step could be added to SEP-24 that would allow clients to submit their JWS to the anchor. This would need to happen _after_ the transaction ID was returned from `POST /transactions/interactive/deposit` but _before_ the client opens the interactive URL for the user.

This request allows the anchor to verify that the client requesting the transaction belongs to the organization running the wallet server. The client would have to receive another JWS for different transaction request.

---

I can create a PR for this new SEP if we agree on the overall objective and properties of this protocol. @tomerweller @leighmcculloch

**Comment by JakeUrban** [comment]
As mentioned in [my closing comment](https://github.com/stellar/stellar-protocol/pull/713#issuecomment-682228021), we're trying to make a nonbreaking change to SEP-10 that would allow anchors to verify a wallet server's signature on the challenge transaction in addition to the usual user keypair signature by the wallet.

**Comment by JakeUrban** [comment]
Here is what the change described above might look like:

### The wallet server signs the challenge transaction

- The wallet application requests the challenge transaction as usual
- The wallet application authenticates with its backend server, the wallet server
- The wallet application posts the challenge transaction XDR to the wallet server
- The wallet server signs the challenge with the keypair referenced by its [stellar.toml](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md) `SIGNING_KEY` and returns the signed envelope XDR

### The wallet signs and sends two challenge transactions

- The wallet application validates the wallet's signature and signs `envelopeA`
- The wallet application signs the original challenge returned from the authentication endpoint, creating `envelopeB`
- The wallet makes a POST request to the `WEB_AUTH_ENDPOINT` with the following body:
```json
{
  "transaction": <envelopeA>,
  "attribution_transaction": <envelopeB>,
  "wallet_domain": "vibrant.cash"
}
```

The two added attributes:

- `attribution_transaction`: The envelope signed by both the wallet application (user) and wallet server, proving both client account control and the wallet identity
- `wallet_domain`: The home domain of the wallet server's TOML file. This is required if `attribution_transaction` is passed, otherwise the authentication endpoint won't know who's `SIGNING_KEY` signature to verify.

The authentication endpoint can maintain a local map of wallet domains to `SIGNING_KEY`'s.

### The authentication endpoint returns a token

```
{
    "iss": "testanchor.stellar.org/sep10/auth",
    "sub": "GAC22YV3EG62HMQF5UQIO5HT6FCPLC2GEZ2FIAVGPEEIKWRQM5AN5TIS",
    "jti": "aa77983a-e550-4d90-8cc2-d661d7f0b8f6",
    "exp": "1597789801",
    "iat": "1597703375"
    "w": "vibrant.cash"
}
```

This token has an added attribute, `w`, signaling to the service that can verify the integrity of the deserialized payload that the client who sent this token was cryptographically attributed to the wallet server specified by `w` (I'm open to changing the key name).

Adding the attribute to the JWT claims allows the service to verify that the client has been attributed to a wallet server on each request.

**Comment by leighmcculloch** [comment]
@JakeUrban I'm just caching up on this. I have a few questions and comments based on revision https://github.com/stellar/stellar-protocol/commit/4bd4b575e8a42c010d7580d3cc4534068943186b:

1. >Using the same algorithm allows signing servers to use the keypair specified by their stellar.toml's SIGNING_KEY to sign the JSON-encoded objects described here

   If we use the SIGNING_KEY variable we are overloading the use of this parameter so now it will be used for SEP-10 and other use cases. It might not be practical for implementers to use the same key for these different use cases. Also, the SIGNING_KEY field doesn't allow an implementor to rotate its JWT issuing keys. I think we should probably have a stellar.toml parameter that points to a URL where the issuing keys are available. Those issuing keys shouldn't need to be Stellar keys, they can be any commonly used key/algo type used with JWTs. I think we're binding this solution too deploy to existing Stellar technology and it is unclear to me how if the algos underneath Stellar keys changed how we'd adapt that here.

   Ideally the URL holding the keys would return the standard JWKS format. As an example of how other services serve keys, this is the JWKS URL for Firebase's JWKs: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

2. > Wallet Request Attribution for Anchors

   I think we should rename this to `Secure Client Request Attribution`, because this has applications beyond anchors, it's attribution between a client and a server generally where the client and server are run by independent parties.

3. > jti — the identifier for the resource (transaction) being processed by the Wallet and defined by the Anchor Server

   What's the motivation for tying use of this JWT to prove who the client is with one single transaction? It would be feasible in my mind that a wallet server might issue this JWT to a client with a 24 hour expiry and it might use that token for all requests during that period. Of course a server could issue them for smaller windows, but limiting them for single-use is maybe unnecessary. Also, I think if a [`jti`](https://tools.ietf.org/html/rfc7519#section-4.1.7) is to be included it should be generated by the issuing server, because it should not be possible for multiple JWTs to contain the same `jti`. If a third party server (anchor) is defining the value of the `jti` field then the issuer has no control over the `jti` being unique to that specific token. The `jti` is mostly useful for tracking use of a single JWT and to prevent replay.

4. >The Anchor can keep the public keys of known Wallet Servers, but if the client is unknown, the Anchor should request the Wallet Server's stellar.toml and validate that the value found was used to encrypt the JWS.

   I think it is more common practice that clients periodically retrieve keys from the JWKS URL and so we should remove the statement encouraging anchors to store the public keys of known wallet servers. Wallet servers need to be able to rotate keys and if anchors aren't checking the JWKS URL they'll start rejecting requests.

5. >kid — the Stellar public key address used to sign the JWS

   I think this field is redundant. We only need to include the JWK ID in the header, not the payload. If it is being included in the payload to mean something else, then we should probably use a different name since `kid` is reserved for a specific use in the header.

**Comment by tomerweller** [comment]
@JakeUrban why is the wallet posting two signed challenge transactions instead of just one signed by both the wallet and the wallet server?

**Comment by leighmcculloch** [comment]
>one signed by both the wallet and the wallet server?

Why is the wallet server signing a challenge transaction? Are we referring to a SEP-10 challenge transaction? A SEP-10 transaction should only be signed by the key holder, the wallet.

**Comment by JakeUrban** [comment]
Leigh, great to have you back.

The above solution is a rough draft I thought up on the heels of getting [SEP-34](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md) across the finish line. Once we realized there was a better way _and_ that there wasn't any pressing reason to keep moving forward for now, I wrote this up to come back to it later.

The solution was written with two priorities:
- integrate with SEP-10 in a _non-breaking_, additive fashion
- use the cryptographic tools used in the Stellar ecosystem today

The 2nd point came from a discussion I had with Tomer and we felt that requiring services to become familiar with JWK encryption standards was an unnecessary burden on authentication services. If we chose to use standard JWKS formats and provide a URL for exposing a list of rotating keys, we would need to change the design significantly

> why is the wallet posting two signed challenge transactions instead of just one signed by both the wallet and the wallet server?

Because the change needs to be additive. Adding an additional signature requires the SDKs to update to allow and check for the wallet's `SIGNING_KEY` signature. This signature would normally be unexpected signed its not a signer of the client account.

With a 2nd challenge, SDK's can simply add helpers to verify attribute challenges while leaving the original challenge alone.

> Why is the wallet server signing a challenge transaction? Are we referring to a SEP-10 challenge transaction? A SEP-10 challenge transaction should only be signed by the key holder, the wallet.

The idea is that the wallet server _is_ a key holder. When the wallet server signs the challenge sent to it by the client, it essentially "takes ownership" of the client who made the request. So as I pointed out in the first question, the challenge signed and returned by the wallet server proves something _separate_ from the control of the client Stellar account.

**Comment by leighmcculloch** [comment]
>integrate with SEP-10 in a non-breaking, additive fashion

Why does wallet attribution need to integrate with SEP-10? Wallet attribution can sit alongside SEP-10 and the token for wallet attribution can be passed as a header in requests to servers. In theory wallets can use wallet attribution in cases where authentication of a Stellar account is not needed, and so it can be used for requests prior to SEP-10, or in SEPs that never use SEP-10.

**Comment by JakeUrban** [comment]
Have you read [SEP-34](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0034.md)? I'm curious what you think.

**Comment by leighmcculloch** [comment]
Yup, I read SEP-34, that's what I was discussing above in https://github.com/stellar/stellar-protocol/issues/685#issuecomment-697003125. I understand from what you're saying that we've put SEP-34 to the side to explore a solution building wallet attribution into SEP-10. Am I understanding correct?

I think I should have reviewed https://github.com/stellar/stellar-protocol/issues/685#issuecomment-682243738. Is that the latest proposal?

**Comment by JakeUrban** [comment]
Thats correct. I'm happy to discuss SEP-34 but I think the per-transaction token idea was unnecessary, which is largely why we chose to try to piggyback on SEP-10. I do think you raise good points though.

> In theory wallets can use wallet attribution in cases where authentication of a Stellar account is not needed, and so it can be used for requests prior to SEP-10, or in SEPs that never use SEP-10.

Thats certainly true, but I think we need to continue to design with the users of the solution in mind. Thats why a SEP-10 adaptation was ideal, since authentication of a Stellar account is a very convenient time to also prove the client's identity (i.e. having the wallet backend sign a challenge thats sent back to the authentication server).

This design uses a single token that has 2 claims (account ownership and client attribution). This change also adds a 2nd challenge to the POST API call. Maybe we should leave SEP-10 alone and make a new challenge-response-token flow for client attribution. But how is this attribution token sent in requests?

**Comment by leighmcculloch** [comment]
I think SEP-34 could be session based and not per transaction as there's nothing inherent that requires it to be limited to a transaction. An appropriate expiration limit would probably suffice?

> why is the wallet posting two signed challenge transactions instead of just one signed by both the wallet and the wallet server?

Back to @tomerweller's question ☝️, why do we need two separate transactions?

**Comment by tomerweller** [comment]
> Back to @tomerweller's question ☝️, what's driving us to two separate transactions? I can see some advantages both ways, but not sure what is leaning you there.

I think that the motivation is backwards compatibility.  

> 11. The server verifies the client signatures on the transaction are signers of the user's account;

Current SEP10 server implementations will reject a challenge transaction that has an additional attribution signature.

**Comment by JakeUrban** [comment]
Correct @tomerweller , two transactions is also a better design because they make independent claims, one about account ownership and the other about client attribution.

Regarding your comments on SEP-34 I agree, thats why we're talking about this SEP-10 based solution. Optionally we could alter SEP-34 if we wanted to leave SEP-10 alone.

**Comment by JakeUrban** [comment]
This has been on the backburner for awhile but we need to start moving since a client has requested a solution.

**Comment by leighmcculloch** [comment]
>Current SEP10 server implementations will reject a challenge transaction that has an additional attribution signature.

I think there's another way to address this issue in a single SEP-10 transaction. In SEP-10 v2.1.0 we started to lay the groundwork for supporting additional manage data operations where each manage data operation is a claim:
- A key-value pair providing some value to some predefined registry/list of keys
- A source account who is the party proving that claim is true

If a client states in the GET request to the SEP-10 server that it also wishes to prove attribution it can provide the claims it wishes to prove (source account, key, value). The SEP-10 server can include those claims in the challenge transaction. The client can sign for them. The SEP-10 server has proof that the source account specified signed for those claims.

I haven't given this part enough thought yet, but we can think of ways to lookup source accounts from domains so that a wallet could say they wish to prove they are the example.com wallet. But my main point is I think if we want attribution to be part of SEP-10 it can and should be part of the same transaction as part of some broader claim/proof system.

---

I'm still concerned we're overloading SEP-10 with this though, and a separate session based (not transaction based) JWT that the wallet client gets from its wallet backend, and that the anchor server (or other server) can verify was issued by a specific domain or wallet. I can help specify this if you'd like.

**Comment by JakeUrban** [comment]
Thanks Leigh, I agree with the v2.1 changes, we can use a single challenge transaction.

I want to clarify something: SEP-10 _is_ a session-based token, not a transaction-based token. So any additional session-based token is not really needed, even if the design may have a better separation of concerns. I think we also need to take into account our ecosystem participants. They'll likely prefer an additive change to SEP-10 over a separate system.

In my mind, the solution I suggested in this comment is still ideal. Now that v2.1 is here, we can use a single transaction (instead of the two listed in the comment). The only extra step for clients is to POST the challenge to their backend service, which should be the only service in possession of the Wallet Organization's secret signing key. The backend service will returned the signed challenge, the client app will then sign with the user's SK, and finally POST is back to the SEP-10 service, which can verify the signature belongs to the `wallet_domain` parameter included in the request.

**Comment by leighmcculloch** [comment]
👍  I think this sounds good. Let's see what this look like as a modification to SEP-10.

---

> 2\. The backend service will returned the signed challenge, the client app will then sign with the user's SK

Have the backend return the signature alone, rather than the entire challenge. The client can attach the signature and it means the client does not need to revalidate the transaction. We use this pattern in SEP-30.

**Comment by JakeUrban** [comment]
Great! I''ll begin drafting up a PR

**Comment by JakeUrban** [comment]
@leighmcculloch 

> Have the backend return the signature alone, rather than the entire challenge.

I was planning to leave the interaction between the wallet server and wallet client out of the scope of this change. I think thats the way to go since any given Wallet organization likely already has an internal mechanism for secure client-server interaction. 

Another way to think about it is that SEPs are all about interoperability, but there are no interoperability concerns here because the client and server are the same party.

**Comment by JakeUrban** [comment]
To add to that ^, the client attribution changes to SEP-10 will only document the mechanism for client and SEP-10 server.

**Comment by leighmcculloch** [comment]
>leave the interaction between the wallet server and wallet client out of the scope of this change

Great idea 👍

**Comment by JakeUrban** [comment]
@leighmcculloch can you take a look at the outstanding PR? I think its ready to be piloted in Polaris and we can merge it if we believe the design is sufficient once it's been tested
