### ISSUE TITLE
Add Regex to fields!

### ISSUE THREAD

**Issue by shredding** [stellar/stellar-protocol#698]
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#info

We want to do client side validation for fields like this:

```
"dest": {
    "description": "your IBAN number",
    "regex": "^[A-Z]{2}\d{2} (?:\d{4} ){3}\d{4}(?: \d\d?)?$"
}
```

The `regex` part is new.

**Comment by tomerweller** [comment]
I think we should avoid promoting a standard that has clients evaluating regular expressions coming from a remote server. This has the potential to expose a very large attack surface.  

ReDoS: https://en.wikipedia.org/wiki/ReDoS

**Comment by shredding** [comment]
Fair point. 

Could we add a validation section to the error response? The current error is quite technical and arbitrary. If we'd have a key-value of fields to error, we could at least do server side validation and show the user hints to problems.

**Comment by leighmcculloch** [comment]
Another challenge with using a regular expressions is that regex syntax isn't universal. Languages have slightly different syntaxes, and some languages implement the syntaxes differently. It's possible an anchor define a regular expression and a clients execution of it results in a different validation. This might be rare, but it is possible.

Instead of a regex we could define an enumeration value of common data formats. It would be up for clients to implement the validation of different fields. Even if this is used we should assume that a client validation might allow some data to go through that the server errors on and so it's still important to have that feedback loop back to the client informing them of which field has an issue and what the issue is specifically.

**Comment by shredding** [comment]
I would like to expand the error a bit, then we could do server side validations:

```
{
   "error": "This anchor doesn't support the given currency code: ETH",
    "fields": {
           "asset_code": "ETH is not supported, supported currencies are FOO, BAR",
           "dest": This must be a valid IBAN.
     }
}
```

Then we could at least show the error where it belongs. Currently I get error messages like "dest_ext must be xyz" and I don't want to explain users what "dest_ext" is.

Another way would be to add an optional validation endpoint, such as 

```
GET /validate/deposit/
GET /validate/withdraw/
```

... with the same parameters as the original deposit.

Then we could just query the server for validations. It could give a `204 No content` if everything looks fine and a 400 if things went wrong.

**Comment by leighmcculloch** [comment]
Adding well defined server side validations would be a good start, and adding that to the transfer server SEPs would be worthwhile I think. Adding a validation endpoint is an optimization, but regardless it would be worthwhile to make the errors parseable.

The format you suggest would work. I think we should also consider does the format need to be more flexible and support multiple errors per field, and how do we display errors about subfields of a field, as well as of the field itself. We should probably do some research and see if there are any good standards or APIs to learn from.

**Comment by shredding** [comment]
We might have a look into how django rest framework does it, as polaris is shipping it anyways. The basic idea is that internationalisation is opt-in by adding a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language header.
