### ISSUE TITLE
SEP31: add dynamic fee endpoint

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#716]
The SEP31 `/info` endpoint already supports fixed fees and percentage fees. However, often times the receiver might have a more complex fee structure in place.

This is already supported in SEP24 through the `/fees` endpoint.

I propose adding a similar dynamic fee endpoint to the SEP31 spec. In SEP31 we might want this to be an authenticated endpoint so that the receiver can give different quotes based on the identity of the sender anchor.

**Comment by JakeUrban** [comment]
bump

**Comment by leighmcculloch** [comment]
Could we make it optionally authenticated, so if possible fees can be exposed regardless like SEP-24, then user specific fees can be served when authenticated? Will it be possible for the fee endpoint to maintain the same format and structure as SEP-24?

**Comment by JakeUrban** [comment]
@leighmcculloch 

> Could we make it optionally authenticated

Yes

> so if possible fees can be exposed regardless like SEP-24

Sure. Do we want to make authentication required per asset though? Otherwise I see a world where anchors return 400 HTTP codes from `/fee` with a message like `"not authenticated to request fees for asset"`.

> then user specific fees can be served when authenticated?

Interesting idea. This would work for SEP-31 because the sending Stellar account always exists at this point in the flow, but it wouldn't work for SEP-24 because anchors are expected to sponsor account creation for users.

**Comment by JakeUrban** [comment]
> Will it be possible for the fee endpoint to maintain the same format and structure as SEP-24?

The fee endpoint already maintains the same structure.

**Comment by JakeUrban** [comment]
I have a draft PR, can we discuss there?

**Comment by JakeUrban** [comment]
Not stale, just related to a larger problem we haven't addressed
