### ISSUE TITLE
SEP-10: SIGNING_KEY verification requirement can have a gap after a key rotation 

### ISSUE THREAD

**Issue by howardtw** [stellar/stellar-protocol#721]
The new change introduced in [this](https://github.com/stellar/stellar-protocol/pull/708) PR makes it so that the signature of the challenge transaction has to match the one specified in the TOML file. However, a key rotation of the server can happen after the challenge transaction is given, the challenge transaction will then be considered invalid by the client.

In order to tackle this, webauth server supports having multiple signing keys at a time so that the server won't produce transactions that cannot be verified going through a key rotation.

The new requirement imposed by SEP-10 seems to invalidate the support of that.

**Comment by JakeUrban** [comment]
Do I need to take some action on this? I thought you were designing the go changes to `webauth`

**Comment by JakeUrban** [comment]
Howard has pointed out an issue that is related but separate from the SEP-10 PR referenced.

When a TOML's `SIGNING_KEY` is changed (rotated),  existing tokens currently in use by clients are "stale" in the sense that they were issued after verifying a cryptographic signature the server no longer claims to control.

In the same way, clients in the process of obtaining a SEP-10 token may have received a challenge transaction signed by the prior `SIGNING_KEY`, so when the client POST's the signed transaction back, the `SIGNING_KEY` the server expects to have signed the transaction has changed. 

**This issue should start a discussion surrounding the appropriate behavior of the anchor server regarding stale tokens and challenge transactions**

Meaning, should the service require clients to re-authenticate or restart the current authentication process? 

If not, how will client's verify stale challenges if the `SIGNING_KEY` listed on the service's TOML file is different than the public key that signed the returned challenge? @howardtw believes we may want to list multiple `SIGNING_KEY` attributes on the TOML file so client's can still use stale challenges.

The PR referenced in the issue description allows multiple home domains (and hence multiple TOML files) to list the same `WEB_AUTH_ENDPOINT`. 

Since the clients connecting to one of these home domains needs a challenge signed by the `SIGNING_KEY` on the home domain's TOML, key rotation and the stale token/challenge problem is somewhat related to this change. However, this stale token issue must be solved independently.

**Comment by JakeUrban** [comment]
@tomerweller @nebolsin

**Comment by nebolsin** [comment]
Challenge transactions are short-lived by design (I believe that recommended TTL is 5 minutes), which really limits the impact of the key rotation. I would expect the server which implements the key rotation to accept valid challenge transactions issued using the old key, but I think that's an implementation detail.

As far as the client side is concerned, server key validation happens _before_ presenting a transaction for signing to the user.  The only case where client would notice the key rotation is if it happens between fetching the stellar.toml and requesting the challenge transaction, which suggests that probably simple retry strategy on the client might be a viable solution. I imagine the client flow to be like this: 
1. Download the service's stellar.toml, extract WEB_AUTH_ENDPOINT and SIGNING_KEY
2. Request challenge transaction from WEB_AUTH_ENDPOINT
3. Verify that it is signed with a SIGNING_KEY. If validation fails — fetch service's stellar.toml again, extract SIGNING_KEY and try challenge verification again. In case of second failure show a warning to the user that service's authenticity cannot be established which might indicate that someone is doing something nasty.

Having said that, I think it might be a good idea to allow multiple signing keys in the stellar.toml (and we also might want to use a separate field instead of sharing the one with compliance protocol, similar to how SEP-7 uses dedicated URI_REQUEST_SIGNING_KEY). For example, in HA setup WEB_AUTH_ENDPOINT might be provided by two physical servers in different availability zones behind the load balancer. The requirement to use a single signing key on both servers is less secure and makes it impossible to use any kind of HSM-based signing.

**Comment by JakeUrban** [comment]
> 1. Download the service's stellar.toml, extract WEB_AUTH_ENDPOINT and SIGNING_KEY
> 2. Request challenge transaction from WEB_AUTH_ENDPOINT
> 3. Verify that it is signed with a SIGNING_KEY. If validation fails — fetch service's stellar.toml again, extract SIGNING_KEY and try challenge verification again. In case of second failure show a warning to the user that service's authenticity cannot be established which might indicate that someone is doing something nasty.

This is exactly what I think the client should do, and as you said I don't see a reason to add the old key to the TOML. The signing server can maintain a reference to the old signing key to validate stale challenges internally. @howardtw

**Comment by howardtw** [comment]
> I would expect the server which implements the key rotation to accept valid challenge transactions issued using the old key, but I think that's an implementation detail.

Is it fine for a server to sign/verify a challenge transaction with a key that's not specified in the TOML file? I wasn't sure whether it's a good practice to do something beyond what we say.

> simple retry strategy on the client might be a viable solution

My concern to this is that it might be a bad user experience. Maybe this is acceptable given that a key rotation doesn't happen often. And as long as we are able to make everyone aware of this situation and retry accordingly, I'm good too.

> in HA setup WEB_AUTH_ENDPOINT might be provided by two physical servers in different availability zones behind the load balancer. The requirement to use a single signing key on both servers is less secure and makes it impossible to use any kind of HSM-based signing.

I agree. Besides I personally don't see a downside of having multiple signing keys in the TOML file regardless how we present it, whether we use the same field or separate fields.

**Comment by JakeUrban** [comment]
> Is it fine for a server to sign/verify a challenge transaction with a key that's not specified in the TOML file?

They should not _sign_ a new challenge with a key that is not specified in the TOML, but they should still _verify_ challenges that were signed with the old key for a given grace period, maybe even the same TTL on the challenge. This would mean that a challenge signed by the old `SIGNING_KEY` would be valid only until the challenge itself would normally expire.

> My concern to this is that it might be a bad user experience. Maybe this is acceptable given that a key rotation doesn't happen often. And as long as we are able to make everyone aware of this situation and retry accordingly, I'm good too.

Clients should have this retry functionality in place and ensure a good user experience while re-authenticating. Maybe we should get the ecosystem team involved in communicating these expectations when its the clients' turn to implement the SEP-10 changes.

> Besides I personally don't see a downside of having multiple signing keys in the TOML file regardless how we present it, whether we use the same field or separate fields.

I agree the use of another signing key in the TOML is appropriate for separate use cases like `URI_REQUEST_SIGNING_KEY` (SEP-7). But I disagree that we should have a "most-recently-rotated-out" `SIGNING_KEY entry. Its add unnecessary confusion to a well-defined standard.

**Comment by JakeUrban** [comment]
@leighmcculloch @tomerweller feel free to weigh in here

**Comment by howardtw** [comment]
> They should not sign a new challenge with a key that is not specified in the TOML, but they should still verify challenges that were signed with the old key for a given grace period, maybe even the same TTL on the challenge. This would mean that a challenge signed by the old SIGNING_KEY would be valid only until the challenge itself would normally expire.

@JakeUrban while I was updating the web auth server, I realized this is already what the [current](https://github.com/stellar/go/blob/master/exp/services/webauth/README.md#usage-serve) design is: `first key is used for signing, others used for verifying challenges`. My bad that I missed the fact that it only uses the first key to sign and verify, and the rest key(s) to verify.

I think we can close this issue if you'd like.
