### ISSUE TITLE
SEP-24: Claimable Balance Op Support

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#747]
Currently, when an anchor creates an account for a user, the anchor must wait for the user to add a trustline before making the SEP-24 deposit. 

With the new protocol's ClaimableBalance functionality, anchors no longer have to wait when the account doesn't have a trustline. Instead, it can make the payment using the ClaimableBalance functionality and the user can collect the funds at any time.

**Comment by JakeUrban** [comment]
These changes are also relevant to SEP-6

**Comment by Zagan202** [comment]
# SEP-0024 Changes for Claimable Balance Op Support

There should be 2 optional paths for anchors and wallets regarding claimableBalances

## Path 1 claimableBalances Not implemented

### [Stellar account does not exist](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#stellar-account-does-not-exist)

### [Stellar account doesn't trust asset](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#stellar-account-doesnt-trust-asset)

## Path 2 claimableBalances is Implemented

### Stellar account does not exist *or* Stellar account doesn't trust asset

Anchors should create accounts if they don't exist similar to [this](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#stellar-account-does-not-exist)

The anchor should then use [https://developers.stellar.org/docs/start/list-of-operations/#create-claimable-balance](https://developers.stellar.org/docs/start/list-of-operations/#create-claimable-balance) to create a claimable balance.

### Predicates (optional)

[https://developers.stellar.org/docs/glossary/claimable-balance/#parameters](https://developers.stellar.org/docs/glossary/claimable-balance/#parameters)

We suggest if you decide to set predicates to claim the balance in 30 days. `BEFORE_RELATIVE_TIME(X)`

However if implemented, its up to the anchors to handle refunds (of off network funds) to the the waller/user . 

### Update the GET /Transaction endpoints (Strongly recommended)

```markdown
GET /transactions
GET /transaction
```

On success the transaction JSON should be extended to include a field named `claimable_balance_id` who's value is a string that returns the `BalanceID` 

[Claimable Balance - Stellar Documentation](https://developers.stellar.org/docs/glossary/claimable-balance/#balanceid)

This is important for wallets to know exactly how the anchor submitted the transaction.

The Wallet should then communicate to the user that their transaction was submitted as a claimable balance and the recipient (whether it be the user or another party) must claim the asset balance at their own time.

In order to claim it the recipient must either get access to the account that the anchor created and or establish a trustline (for the asset code of the claimableBalance) with their existing account.

### If an anchor decides not to update GET /Transaction endpoints endpoints then the Wallet will need to perform the following steps

1. Call the anchor's `GET` transaction(s) endpoint to get the `stellar_transaction_id` of the completed deposit(s) 
2. Query Horizon's  `GET /transactions/:transaction_id`  with the `stellar_transaction_id` received from step 1 to get the ledger [https://developers.stellar.org/api/resources/transactions/single/](https://developers.stellar.org/api/resources/transactions/single/) 
3. Query Horizon's List Claimable Balances endpoint periodically with the sponsor's publicKey [https://developers.stellar.org/api/resources/claimablebalances/list/](https://developers.stellar.org/api/resources/claimablebalances/list/) 
4. Parse the results from List Claimable Balances to find the claimableBalance(s) of interest (find those who match the ledger) (`last_modified_ledger == ledger`)
5. The matched transactions will have an id (this is a balanceID) wallets can expose this claimableBalance information to the user with Horizon's `GET /claimable_balances/:claimable_balance_id` [https://developers.stellar.org/api/resources/claimablebalances/single/](https://developers.stellar.org/api/resources/claimablebalances/single/)

**Comment by JakeUrban** [comment]
@leighmcculloch @tomerweller Can you review the above flow and suggested changes? I've worked with @Zagan202 to produce this.

**Comment by JakeUrban** [comment]
@Zagan202 I think the client's flow would be a bit simpler than what you outlined in the last section. Also, your approach of using the last modified ledger doesn't work because there could be multiple claimable balance operations made in a ledger.

1. Make a request to Horizon for `/claimable_balances?claimant=<users stellar account>`
2. Iterate over the list and save the new claimable balances. Claimable balances should be "new" when the `id` attribute doesn't exist in anchor/wallet's database.

Note that this doesn't map a Transaction's `id` to a ClaimableBalance's `id`. If we wanted to do that, we would need the `claimable_balance_id` attribute to SEP-24's `/transaction(s)` endpoints.

**Comment by Zagan202** [comment]
> 2\. Iterate over the list and save the new claimable balances. Claimable balances should be "new" when the `id` attribute doesn't exist in anchor/wallet's database.

Yeah that makes sense and is a much less complex.

> Note that this doesn't map a Transaction's `id` to a ClaimableBalance's `id`. If we wanted to do that, we would need the `claimable_balance_id` attribute to SEP-24's `/transaction(s)` endpoints.

Exactly. The client will call `GET /transaction(s)` endpoints.
` and use the `claimable_balance_id`s received when they call Horizon's `GET /claimable_balances/:claimable_balance_id`

**Comment by Zagan202** [comment]
Currently this [code change to Polaris](https://github.com/stellar/django-polaris/pull/341) does support claimableBalances for SEP-0024.
However the predicate set by default is `UNCONDITIONAL` and the `GET /Transaction(s)` endpoints currently do not have the `claimable_balance_id` field in the response.

**Comment by JakeUrban** [comment]
@Zagan202 I'd link the PR directly, either by doing this in the PR description:
```
resolves stellar/stellar-protocol#747
```

Or linking it via the UI on the side here.

**Comment by tomerweller** [comment]
This looks good. We need an introduction roadmap. If anchors adopt this before tooling and ecosystem wallets then we'll see a breakage.

**Comment by JakeUrban** [comment]
These are the steps we need to take in order:

- Draft, discuss, and merge the SEP-24 & SEP-6 ClaimableBalance Support PR's
- Implement the claimable balance support in our demo client/wallet
    - I think we should begin deprecating the original demo client and only add new features to the new one
- Reach out to ecosystem wallets announcing the SEP changes and their action items
- Monitor progress, test with our reference server's ClaimableBalance support
- Announce SEP changes and Wallet support for those changes to Anchors
    - We can use Polaris as a reference

We can discuss the timing of each step. Lawrence is drafting the initial PR's for SEP-24 and SEP-6.

**Comment by Zagan202** [comment]
I had some questions about the `Special Cases` flows in SEP 24 and how it can be represented as a POC using `Stellar-Demo-Wallet` and `Polaris`

A few points to keep in mind

1. Do we agree with following flows?
2. Are there any flows I am not considering?
3. There are comments/questions about features that are or are not represented in either `Stellar-Demo-Wallet` and/or `Polaris`

**Stellar account does not exist**

1.  Given Stellar `account` does not exist 
    - Currently there is no way to have `Stellar-Demo-Wallet` users without `Accounts` associated with them.
    This is because the `Stellar-Demo-Wallet` either creates an `Account` for them 
    or
    they load an existing `Account` with their Secret Key
    - We would have to make a change to `Stellar-Demo-Wallet` that makes a user (with a name and email etc *SEP2?*) but doesn't give them a stellar account. Then `Stellar-Demo-Wallet` would have to let the user deposit their `off chain funds` (of whatever denomination) to get tokenized equivalent `Asset` using their `Wallet`. Afterwards we proceed with the rest of the steps here.
2. Anchor uses `create_account` to create the account with at least enough XLM for the minimum reserve and a trust line (2.01 XLM is recommended)
3. `Anchor` doesn't have the user account's secret key and the user account doesn't have a `trust line` to the `anchor's asset`
    - This user didn't have an `Account` until the `Anchor` made them one. 
    Question(s): So who has the secret key? How can the the user get the secret key? What scenario is this where someone deposits `off chain funds` to get a tokenized equivalent amount on an account that they don't even have the secret key for?
4. `Anchor` accepts the deposit and makes a `claimable balance` to the newly created `Account`

**Stellar account doesn't trust asset**

1. `Account` wants to deposit `off chain funds` to get tokenized equivalent `Asset` using their `Wallet`
2. `Wallet` sees `Account` doesn't trusts `Asset`.
3. `Wallet` still then allows `Account` to make deposit of `off chain funds` to get tokenized equivalent `Asset`
4. `Anchor`  of equivalent `Asset` sees that the account does not trust the their `Asset`.
5. `Anchor` receives `off chain funds`
6. `Anchor` then makes a `Claimable Balance` to to the `Account`
7. `Anchor` updates the transaction’s status as `complete`
8. Wallet polls */transaction* and notices transaction is `complete`
9. Wallet notifies `Account` that there's a `Claimable Balance` for the `Account` to claim.

We would need to make `Stellar-Demo-Wallet` give `Accounts` the ability to make deposits on assets they **do not trust** Currently `Accounts` using `Stellar-Demo-Wallet` only show `Assets` that they already trust as *deposit-able* 
If the `Account's` `wallet` on `Stellar-Demo-Wallet` shows a *deposit-able* `Asset` then there is no way for them to make this flow happen because its determined that the asset is trusted already

**Comment by leighmcculloch** [comment]
Apologies, I missed being mentioned above and just discovered this.

In response to https://github.com/stellar/stellar-protocol/issues/747#issuecomment-710398419:

>If an anchor decides not to update GET /Transaction endpoints...

I think an anchor implementing a use of claimable balances should update the `GET /transaction` endpoint and we shouldn't specify ways around that. I would have thought the work and effort to implement claimable balances will probably be significantly more difficult than just adding a single field to the GET response and therefore not worth providing an out for. Do we have evidence that suggests otherwise? or know of any anchors who would not be able to update the `GET /transaction` endpoint?

**Comment by JakeUrban** [comment]
Any anchor that adds support for claimable balances should be able to update their transaction endpoint as well.

**Comment by JakeUrban** [comment]
@Zagan202 if the goal is to be able to test every possible scenario, particularly the special cases, we need to completely re-think the UX. The stellar-demo-wallet would have to become more of a technical debug tool that should be used by engineers testing particular cases. Right now, the idea behind the demo wallet is a hybrid of 1. act like a wallet & 2. allow people to test their anchors.

#1 gets in the way of #2. If #2 is the main goal, we need to put less emphasis on this being a wallet-like application.

**Comment by JakeUrban** [comment]
For example, if we want to allow anchors to test the `The account does not exist` case, then we need to allow users not to create or load an account, and instead just specify a public key without account creation.

If we want to test the `The account doesn't have a trustline` case, then the UI needs to allow people to add assets to their "wallet" without yet having a trustline.

**Comment by JakeUrban** [comment]
The end result would be an application that allows for more fine-grained client-side control, but it wouldn't act like a wallet because it would provide too many different ways of doing the same thing.

**Comment by Zagan202** [comment]
@leighmcculloch 
The comment you referenced is a bit outdated from the conversations we've had since I posted it.?
I'm drafting out the changes to SEP24 here https://github.com/stellar/stellar-protocol/pull/757 
This will more accurately guide `Anchors` and `Wallets` on what necessary changes need to made in order to support claimable balances properly.

**Comment by Zagan202** [comment]
> @Zagan202 if the goal is to be able to test every possible scenario, particularly the special cases, we need to completely re-think the UX. The stellar-demo-wallet would have to become more of a technical debug tool that should be used by engineers testing particular cases. Right now, the idea behind the demo wallet is a hybrid of 1. act like a wallet & 2. allow people to test their anchors.
> 
> #1 gets in the way of #2. If #2 is the main goal, we need to put less emphasis on this being a wallet-like application.

Thats kinda the root of my concerns, currently `Stellar-Demo-Wallet` leaning more towards the `act like a wallet` path.
We might have to implement the ability to have it seamlessly change behavior states to be a usable resource for `Anchor` devs to use to debug and test weird special case flows.

**Comment by Zagan202** [comment]
> For example, if we want to allow anchors to test the `The account does not exist` case, then we need to allow users not to create or load an account, and instead just specify a secret key without account creation.

How does one "specify a secret key without account creation."?


> If we want to test the `The account doesn't have a trustline` case, then the UI needs to allow people to add assets to their "wallet" without yet having a trustline.

That feature is easy to implement but we should mock up how this would work.
Like we could have "ASSETS _supported_ by the wallet" listed on the UI to allow  a use to enact the `Stellar account doesn't trust asset` special case flow.

This is making a strong argument for the aforementioned state change debugging feature.

**Comment by Zagan202** [comment]
> The end result would be an application that allows for more fine-grained client-side control, but it wouldn't act like a wallet because it would provide too many different ways of doing the same thing.

I don't entirely agree.
The default use case would "act like a wallet" but the more fine grained control behaviors could be flags that changes the application's behavior to fit these special edge cases.

What do you think?

**Comment by JakeUrban** [comment]
You're saying we can have both an application that acts and looks like a wallet but can be configured to test special cases. Maybe thats true, but its difficult from a design perspective. We may need to bring a frontend/design engineer to spec out what the interface would look like. @tomerweller any updates on that?

**Comment by JakeUrban** [comment]
> How does one "specify a secret key without account creation."?

You just ask for a secret key like we do today on the "Load Account" button, but you don't try to fund the account via friendbot. The result is that the wallet will use the account in API calls but the anchor will (or should) realize that the account doesn't exist yet and will fund it. This approach will be much more common when we build out mainnet support.

**Comment by Zagan202** [comment]
> > How does one "specify a secret key without account creation."?
> 
> You just ask for a secret key like we do today on the "Load Account" button, but you don't try to fund the account via friendbot. The result is that the wallet will use the account in API calls but the anchor will (or should) realize that the account doesn't exist yet and will fund it. This approach will be much more common when we build out mainnet support since we don't have friendbot.

I'm still a bit lost. 
If they provide the secret key like we do when the user hits "Load Account" I was under the assumption that secret key is always associated with a stellar account on the DEX (mainnet or testnet). So how would an `Anchor` _"realize that the account doesn't exist yet"_?

**Comment by JakeUrban** [comment]
Go to the Create Account tab on https://laboratory.stellar.org/, and you'll see two steps for account creation: generating a key-pair, and then funding an account at that public key address. Key pairs are just cryptographic keys, just like any other asymmetrical cryptographic key system. The account on Stellar isn't created until another account uses the "Create Account" op to fund an account at that addess
