### ISSUE TITLE
Feature Request: SEP12 PUT - add type field(the type of action the customer is being KYCd for) 

### ISSUE THREAD

**Issue by gaclaudiu** [stellar/stellar-protocol#803]
### What problem does your feature solve?
Server will know which fields are sent when doing a put for SEP12 customer. 
Right now there is no way to know for what type are the fields for : 
* Counter Party 
* individual (person) client
* or entity (organization) client

### What would you like to see?
Add SEP type field in the SEP12 /PUT model .

**Comment by JakeUrban** [comment]
I think its clear which type is being provided based on the fields right? If fields from [the person list](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0009.md#natural-person-kyc-fields) are used then its an individual, and if the fields are from [the organization list](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0009.md#organization-kyc-fields) its an org right?

So if I understand correctly the issue is only that servers cannot determine if the request is for a counter party?

**Comment by JakeUrban** [comment]
Would adding a `customer_type` field whose value must match one of the `sender_sep12_type` or `receiver_sep12_type` values work?

**Comment by gurub109** [comment]
That should work @JakeUrban
