### ISSUE TITLE
SEP-0012: property verification

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#812]
Some KYC properties such as phone number, email address and even home address can be verified using a verification code.

Verifying phone numbers using text messages is especially popular. 

SEP12 currently doesn't provide a mechanism to convey if a property is verified/unverified. 

More so, there's no clear way for a wallet to initiate verification of a property.

This issue is created to facilitate discussion of potential solutions.

**Comment by morleyzhi** [comment]
This is how we've modeled phone validation in Vibrant:

- PUTting mobile_number alone will send a code + return an error (indicating that a code was sent)
- The anchor will only store a mobile_number when it's PUT with a valid mobile_number_verify
- Vibrant would PUT:/customer a mobile_number
- The anchor would send a code to the phone
- Vibrant would show a code input
- The user would enter the code
- Vibrant would PUT:/customer mobile_number_verify and mobile_number
- mobile_number_verify should otherwise not be returned by GET:/customer as a missing field or whatever

**Comment by JakeUrban** [comment]
My issue with the current approach is the lack of separation between KYC information and data used to verify that information.

What I suggest is a new endpoint, `PUT /customer/verification` that accepts forms of verification the following fields:
```
{
    # ID of an existing customer, probably in PROCESSING status
    "id": "e793dc26-c8fc-4b95-bf3d-231f8126e8e1",
    # data used for verification
    "fields": {
        "mobile_number_verification": "185014",
        "email_address_verification": "205721",
        "address_verification": "457023"
    }
}
```
Email address verification is probably easier to do the typical way -- the service sends a confirmation link that the user has to click, but you get the point.

**Comment by JakeUrban** [comment]
Actually, to match the format used in `PUT /customer` I would remove the `fields` attribute:
```
{
    # ID of an existing customer, probably in PROCESSING status
    "id": "e793dc26-c8fc-4b95-bf3d-231f8126e8e1",
    # data used for verification
    "mobile_number_verification": "185014",
    "email_address_verification": "205721",
    "address_verification": "457023"
}
```

**Comment by tomerweller** [comment]
I'm with @JakeUrban on separating this out. Overloading the customer PUT can be somewhat confusing. 

In both of these suggestions there's a pre-requisite that the anchor knows that a field requires verification - should the server communicate this to the wallet? If so, how?

**Comment by JakeUrban** [comment]
Good point @tomerweller, I have a solution

Lets say a wallet just submitted a customer's mobile phone number with a `PUT /customer` request. The server's response currently just includes an `id` or `error` attribute. Instead, it could include data to indicate that some of the fields passed need verification codes:
```
{
    "id": "793dc26-c8fc-4b95-bf3d-231f8126e8e1",
    "verification_required": {
        "mobile_number": {
            "verification_attribute": "mobile_number_verification",
            "description": "A 5 digit code sent to the customer's phone number"
        }
    }
```
The beautiful thing about this design is that server's can define their own verification attributes; no need to standardize them unless we want to.

We could also add this data to the `GET /customer?id=793dc26-c8fc-4b95-bf3d-231f8126e8e1` request:
```
{
    "id": "793dc26-c8fc-4b95-bf3d-231f8126e8e1",
    "status": "PROCESSING",
        "verification_required": {
        "mobile_number": {
            "verification_attribute": "mobile_number_verification",
            "description": "A 5 digit code sent to the customer's phone number"
        }
    }
}
```
This way a wallet can fetch the fields needed for verification again instead of having to persistently store the `PUT /customer` response.

**Comment by tomerweller** [comment]
Interesting. Do we really need to convey information about the verification syntax in the response? Will a wallet ever make use of that? seems like verification code can always be generalized as a string

I'd like to discuss another option, which is to extend the `fields` object for the customer info GET request, both in shape and in scope. We currently use `fields` only for `NEEDS_INFO` responses although it has the potential to serve us in other places as well: 
1. `ACCEPTED` - `fields` can contain existing values so the wallet can show the user what details the anchor has
2. `PROCESSING` - `fields` can pinpoint exactly what fields are being processed. 
3. `NEEDS_INFO` - `fields` can be extended to also show existing values in addition to new values required. example: 

Example, specifically for `PROCESSING`, combing both an unverified email and a photo id check:

```js
{
   "status": "PROCESSING",
   "fields": {
      "email_address": {
         "description": "Email address of the customer",
          "type": "string",
          "value": "john@doe.com",
         "status": "UNVERIFIED"
      },
      "photo_id_front": {
         "description": "A clear photo of the front of the government issued ID",
         "type": "binary",
         "status": "PROCESSING"
      }
   }
}
```

We need to figure out if this presents backward incompatibility issues but would love hear any thoughts about this

**Comment by JakeUrban** [comment]
I don't think the changes you suggest introduce any backwards incompatibility. `fields` is mentioned to be required for `NEEDS_INFO` responses but it doesn't disallow it to be present in other `status` values.

So to summarize, you're suggesting the following changes:
- Allow/recommend the use of `fields` for any `status` value (instead of just `NEEDS_INFO`
- Add a `status` attribute to each attribute described in `fields`
    - I suggest the following values: `INCOMPLETE`, `PROCESSING`, `UNVERIFIED`, `ACCEPTED`, `REJECTED`

I would also suggest adding an `error` attribute to explain the reason for `REJECTED` values.

----------------

Regarding verification of `UNVERIFIED` attributes, are you on board with the `PUT /customer/verification` endpoint? What would the request parameter names be? I suggest using the name of the attribute being verified plus `_verification`.

**Comment by leighmcculloch** [comment]
I like the idea of the verification methods being explicit as in your example with the `PUT /customer/verification` rather than them being arbitrary. There's a limited number of cases probably, we may as well define those attributes explicitly.

**Comment by tomerweller** [comment]
Not stale
