### ISSUE TITLE
SEP-0012: Customer ID and account information included in requests is duplicate

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-protocol#822]
SEP-12 defines several endpoints.

All the endpoints require authentication with a SEP-10 server. Authentication with a SEP-10 server proves to a server that a customer is a specific customer, and indicates the customers account, memo, and memo type.

All the endpoints also require as parameters either a customer `id`, or an `account` and `memo` and `memo_type`. 

It isn't clear to me why we duplicate information that is in the authentication with information in the request message or request URL. This creates burden on servers to implement correctly because they must either ignore the request message/url parameters and rely solely on the authenticated data, or check that the two are equal.

Is there a use case where the customer `id`, `account`, `memo`, or `memo_type` would not be the same information that is indicated by the SEP-10 authentication?

cc @stellar/integration @stellar/nebula

**Comment by JakeUrban** [comment]
I agree we could remove the `account` parameter from our SEP-12 (and for that matter, SEP-6, 24, 31 etc.) since that information is included in the JWT token, however thats a breaking change. Are you interested in making the change regardless?

> they must either ignore the request message/url parameters and rely solely on the authenticated data, or check that the two are equal.

Polaris currently checks for equality between the token's `sub` value and the `account` parameter. 

> Is there a use case where the customer id, account, memo, or memo_type would not be the same information that is indicated by the SEP-10 authentication?

Right now, SEP-10 authenticates an `account`, but not a `memo` or `memo_type`. #726 will change that though. If we wanted to, we could deprecate the parameters in favor of the values included in the SEP-10 token once that issue is merged.

**Comment by leighmcculloch** [comment]
Is it possible to use SEP-12 to provide information about another account? In that case it makes sense, but I guess could be optional when providing details for the authenticated account.

**Comment by JakeUrban** [comment]
@leighmcculloch No, it is not possible, the API should only expose information for the account that is authenticated. If the stellar account is shared between many users, then the `memo` must uniquely identify a user.

**Comment by leighmcculloch** [comment]
What about counter-parties, as is being discussed here https://github.com/stellar/stellar-protocol/issues/803?

**Comment by JakeUrban** [comment]
In a SEP-31 flow, the sending anchor registers both the sender and receiver (a.k.a the counter party) with the receiving anchor, so in that case the sending customer and receiving customer both share the sending anchor's Stellar account and are distinguished by a `memo`.

Note that this means a receiving customer would have a `/customer` record with the receiving anchor _for every sender to that receiving customer_.

On the backend, the receiving anchor could de-duplicate these customer records. Say the receiving anchor requires a phone number for all customer types. They could use the phone number as the PK and store all the (account, memo) pairs used to identify that customer. 

However, this introduces additional problems. Lets say that same customer has 2 emails, and a customer record is created for each email. Since the customer's record is de-duplicated, the receiving anchor only stores a single email, which would be overwritten the second time that customer is registered.
