### ISSUE TITLE
SEP-0012: Format of PUT with SEP-9 fields is not defined

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-protocol#832]
[SEP-12] does not specify, as far as I can tell, how to format the [SEP-9] fields in the Customer PUT (`PUT [KYC_SERVER || TRANSFER_SERVER]/customer`) request.

This can probably be guessed accurately for simple SEP-9 fields such as `email_address`:

```json
{
  "email_address": "user@example.com"
}
```

But it is harder to guess accurately for complex SEP-9 fields that have sub-fields, such as `organization.name`.

For example, should the field be provided using the full field name as the key:
```json
{
  "organization.name": "SDF"
}
```

Or, should the field be provided with sub-fields as sub-keys to an object:
```json
{
  "organization": {
    "name": "SDF"
  }
}
```

I don't see this documented in SEP-12 but I assume people have implemented use of these fields and so there must be a common approach.

I'm asking this question because I'm modeling how SEP-9 fields are provided to a SEP-12 server for new functionality we are adding to SEP-8 in https://github.com/stellar/stellar-protocol/pull/758 and https://github.com/DSTOQ/stellar-protocol/pull/3/files#r558710763.

[SEP-12]: https://stellar.org/protocol/sep-12
[SEP-9]: https://stellar.org/protocol/sep-9

**Comment by accordeiro** [comment]
I'm not sure what is most common implementation, but I've always interpreted this spec as using nested fields, as in:

```javascript 
payload = {
  "organization": {
    "name": "SDF"
  }
}
```

I think this is the approach that leads to less confusion to whomever is writing the parsing code (e.g. a server-side SEP-12 implementation), since some languages (like JavaScript) use `.`s to traverse the JSON structure, so you'd actually have to work around the syntax to be able to parse an attribute called `"organization.name"`. This [SO question](https://stackoverflow.com/questions/2577172/how-to-get-json-objects-value-if-its-name-contains-dots) should provide further context on the issue I'm talking about.

**Comment by leighmcculloch** [comment]
@istrau2 @marcinx @JakeUrban I see you all have committed to [SEP-12](https://stellar.org/protocol/sep-12) in the past. Do you know the answer to how sub-fields should be rendered in the Customer PUT request?

**Comment by JakeUrban** [comment]
Polaris expects SEP-9 fields used to match the way they're defined in the SEP: as strings. See the way it extracts SEP-9 arguments from a dictionary: https://github.com/stellar/django-polaris/blob/1b1ae8c755fb41bd645f9bbec51e1408135826ad/polaris/polaris/utils.py#L336-L396

It does this because `multipart/form-data` and `application/x-www-form-urlencoded` do not support nested data structures, only simple key-value pairs. Only JSON allows nested structures like @accordeiro's example.

**Comment by leighmcculloch** [comment]
@JakeUrban Does Polaris use the simple string approach for JSON requests also, or only for the other content types?

**Comment by JakeUrban** [comment]
@leighmcculloch It uses the simple string approach for all content types including JSON. I could update it to support the nested structures for JSON, but to be honest I did not consider it when implementing. There was no indication int the SEP that nested structures were supported at all.

**Comment by leighmcculloch** [comment]
@gaclaudiu You opened some issues regarding SEP-12 recently. How have you implemented SEP-9 fields with sub-fields with SEP-12? Are you using JSON? Is your JSON usage hierarchical or flat?

**Comment by JakeUrban** [comment]
@gurub109

**Comment by JakeUrban** [comment]
I don't see a reason to allow the sub-fields format. We should clarify that all field names specified via SEP-9 are strings.

Reasons:
1. They are presented in SEP-9 as simple strings
2. It makes the structure used in all content types consistent. `multipart/form-data` and `application/x-www-url-formencoded` do not support nested structures

@leighmcculloch does this sound alright to you?

**Comment by leighmcculloch** [comment]
This sounds like the simplest approach, but I think we need to understand how others have interpreted the specification because even internally there are folks who assumed it was hierarchical. Understanding this will help us determine if making a change is a breaking change or a clarification.

**Comment by JakeUrban** [comment]
I agree that would be ideal, but we don't have a good mechanism for understanding how this has been interpreted in the wild.

If we assume both approaches are used, how would that change what we do? Would we standardize the use of both methods? Applications accepting one type would then have to add support for the other. I don't see why thats a better outcome than picking a single method. Either way, people may have to adjust their implementations. Supporting both methods just means everyone has to update instead of just those implementing the wrong method.

**Comment by leighmcculloch** [comment]
Knowing what we know so far I think we should support the method you mentioned, and only that method, but without understanding how others have implemented this we don't know what the impact will be. I defer to you and @tomerweller for if we know all we can know at this point.

The main reason I think this approach is best is because you pointed out that Polaris uses that approach.

I think the change you proposed in https://github.com/stellar/stellar-protocol/pull/867#pullrequestreview-588089395 is good.

**Comment by marcinx** [comment]
> @istrau2 @marcinx @JakeUrban I see you all have committed to [SEP-12](https://stellar.org/protocol/sep-12) in the past. Do you know the answer to how sub-fields should be rendered in the Customer PUT request, or if you have implemented SEP-12, how you have done it?

We work without SEP-12 at the moment, using other KYC channels with anchors for now. One thing that would be good to have is the ability to add arbitrary numbers of beneficial owners, company directors, and binaries (to transfer docs). It doesn't really matter to us what format we do this in but I guess nested JSON that allows lists would be ideal? 

Personally I prefer this option:

```
{
  "organization": {
    "name": "SDF"
  }
}
```

instead of 

```
{
  "organization.name": "SDF"
}
```

The latter would probably also cause annoying issues in JS? You would have to access `json['organization.name']` instead of the more intuitive `json.organization.name`.

Some fields should allow for a list of items (e.g. beneficial owners).

**Comment by JakeUrban** [comment]
@marcinx We opted to use the flat field notation ([PR](https://github.com/stellar/stellar-protocol/pull/867))
```
{
    "organization.name": "SDF"
}
```
I outlined the reasons for doing so in [this comment](https://github.com/stellar/stellar-protocol/issues/832#issuecomment-776954447)

**Comment by marcinx** [comment]
> @marcinx We opted to use the flat field notation ([PR](https://github.com/stellar/stellar-protocol/pull/867))
> 
> ```
> {
>     "organization.name": "SDF"
> }
> ```
> 
> I outlined the reasons for doing so in [this comment](https://github.com/stellar/stellar-protocol/issues/832#issuecomment-776954447)

Okay, fair enough. It might be hard to iterate through lists with that format though. And lists or arbitrary lengths are probably required by most KYC/AML collectors/transmitters. Maybe food for thought for the future?
