### ISSUE TITLE
Proposal: Support partially signed multi-sig transactions

### ISSUE THREAD

**Issue by pselden** [stellar/stellar-protocol#84]
I posted this over here: https://galactictalk.org/d/1266-stellar-multisig-improvements-in-the-stellar-protocol but also would like to get some discussion going through the "official" channels.

-----

My project StellarGuard.me uses Stellar's multisig with 2-factor authentication to protect your account. One very serious usability issue is that it requires you to submit your partially-signed transactions directly to StellarGuard instead of horizon, because the Stellar protocol does not have any notion of half-signed transactions (it will just reject it with a bad auth error).

By looking at all the applications out there that support multi-sig it became clear to me that most of them are building a third-party multisig coordinator to hold onto these partially signed transactions. While this is fine, it leads to a lot of duplication of effort and also a fracturing of any "standard" way to handle multisig. The problem will not resolve itself unless one multi-sig coordinator becomes the defacto standard way (centralization :( ) or a way to handle partially-signed multi-sig transactions are added to the Stellar protocol itself.

I would like to start a discussion about the merits of adding support for this in the protocol itself.

There are a couple ways I could see it working:

1. Partially-signed transactions are accepted to the Stellar network, there would need to be some mechanism to set them apart from fully valid transactions. They could be queried like regular transactions and then resubmitted.

2. It still errors when it is submitted, but the errors are stored somewhere so they could be queried later to get the full transaction envelope. This would probably be slightly riskier change but also might allow some new use cases that weren't thought of.

Either of these approaches would have to consider how sequence numbers and fees are handled, since you would not be able to sign a transaction that already had its sequence number "used up". 

Obviously the details would have to be fleshed out better, but discussion is welcome.

**Comment by pselden** [comment]
Possibly ties into some discussion here https://github.com/stellar/stellar-protocol/issues/79 re: not bumping seq numbers.

**Comment by zulucrypto** [comment]
As yet another person who has thought about implementing a multisig coordinator, I'm going to chime in here and say that I don't think it makes sense to add this to the protocol because:

1. There are a lot of reasons/ways to do multisig and I think the specific implementation is going to change for each of those cases. It would make more sense to handle this in each specific app.

2. Lots of times you don't even need to store the transaction to sign. As long as what you're doing is known, each party signing it can already build the transaction on their own and you don't need to pass anything besides the signature around.

3. Stellar already allows you to store arbitrary data on an account. Instead of making the protocol/servers a lot more complicated, signatures could just be stored as data entries on accounts.

I think it would be great to have more standards around multisig, but instead of adding anything to the protocol I think it would be better to come up with a standard for an exchange format so tools could send the partially signed transactions to each other.

As an extremely rough idea of what I mean:

**payment-tx.json**
```
{
    "description": "Pay salary from operating account for March 2018",
    "transactionXdrBase64": "...",
    "signatures": [
       { "hint": "XYZ", "signature": "..." }
    ]
}
```

Tools could use this standard format to pass information around them and whenever enough signatures were found in the `signatures` section it could be submitted to the network.

**Comment by pselden** [comment]
I would tend to think that not having it built into core will just end up having reinvented over and over again, possibly with security holes in each one.

> There are a lot of reasons/ways to do multisig and I think the specific implementation is going to change for each of those cases. It would make more sense to handle this in each specific app.

Yes, that's true, but I think the question that needs to be answering is would adding support for this enable new sorts of experiences/possibilities? I think the greatest benefit would be instant interoperability between all wallets and any app that uses multisig (and selfishly, my app).

> 3. Stellar already allows you to store arbitrary data on an account. Instead of making the protocol/servers a lot more complicated, signatures could just be stored as data entries on accounts.

I just have a feeling this will not be very widely used because it increases the minimum account balance and is not very intuitive to end users "uh... I thought it was 1 XLM!".

**Comment by s-a-y** [comment]
just found it following from galactictalk discussion.
I've stumbled across this problem too and implemented it on-chain using that npm package
https://www.npmjs.com/package/stellar-sign

it encodes XDR into multiple data fields (and removes data fields in the same transaction, so it doesn't bump reserve) and sends 0.0000001 XLM ping to the account, that needs to sign it.

Potentially wasteful, because stores the same transaction multiple times to the ledger in not-at-all efficient way, but convenient and doesn't require external resources: IPFS / webserver.

**Comment by pselden** [comment]
@s-a-y Clever solution! One problem that I see is that a signer does not actually need to be a funded account (in fact, that's how StellarGuard is able to use a  new key per account), so the notification system of sending a small amount of XLM would fail in that scenario.

**Comment by s-a-y** [comment]
@pselden I didn't consider that use case, I also like your way with special account to listen to, I could use that with my package. It's just a little bit inconvenient in current SDKs, that you can't listen to transactions on multiple accounts, only one or all.

**Comment by jedmccaleb** [comment]
I really don't want the ledger to become a messaging layer. I think there should be a standard generic messaging layer that is used by the ecosystem for thing like multi-sig coordination but it should be a layer above the core protocol.  Closing for #143

**Comment by pselden** [comment]
I haven't checked myself -- but @orbitlens actually mentioned in his Stellar.Expert comeback post that failed transactions are actually included in history already?? If that's true then technically this could be done already -- it just would be a horrible user experience as you'd be getting transaction failed messages even though I could listen for them and resubmit them as StellarGuard transactions. I doubt I'll go that route, but it's interesting nonetheless that this was possible.
