### ISSUE TITLE
Proposal: accounts with deterministic sequence numbers

### ISSUE THREAD

**Issue by robdenison** [stellar/stellar-protocol#99]
(EDITED to revise details of proposal)

This proposes a new operation, `create_account_2`. The `create_account_2` operation creates a new account, with the following differences from accounts created with `create_account`:

* The account ID is `0x18 ++ sha256(masterKey, creatingTransactionSourceAccountId, creatingTransactionSequenceNumber, creatingOperationIndex, salt) ++ checksum`, rather than `0x30 ++ masterKey ++ checksum`. (The different prefix byte means that in base32, deterministic account IDs start with a "D", while `create_account`'s account IDs start with a "G".)
  * `masterKey` is the initial master key on the account
  * `creatingTransactionSourceAccountId` is the source account of the transaction that created the account (not necessarily the source account of the `create_account_2` operation)
  * `creatingTransactionSequenceNumber` is the sequence number of the transaction that created the account
  * `creatingOperationIndex` is the index of the `create_account_2` operation in the transaction that created the account
* The initial sequence number is 0.

## Rationale

This allows users to presign transactions from an account before that account is created, which is otherwise impossible because the sequence number is not predictable. This would enable a wide range of protocols that involve presigning chains of transactions. (Right now, such protocols are limited to ones that send transactions from accounts that already exist at the time the transactions are being signed.) 

These accounts are also impossible to resurrect if deleted, since the creating account's sequence number will never go down. This makes them safe from any kind of replaying.

Other potential advantages:

* any presigned transaction can be assured that its `createAccount2` operations (and Lumen payments into those newly created accounts) will succeed (whereas `createAccount` operations can be made to fail by creating the account before the transaction is published).
* sequence numbers that start with 0 are easy to reason about and work with (particularly in languages like JavaScript that do not yet have native support for 64-bit integers)
* a user can create multiple accounts with the same initial signer

## XDR

```
struct CreateAccount2Op
{
    Signer initialSigner;
    uint256* salt; // defaults to 0
    int64 startingBalance;
};

/******* CreateAccount2 Result ********/

enum CreateAccount2ResultCode
{
    // codes considered as "success" for the operation
    CREATE_ACCOUNT_2_SUCCESS = 0, // account was created

    // codes considered as "failure" for the operation
    CREATE_ACCOUNT_2_UNDERFUNDED = -1, // not enough funds in source account
    CREATE_ACCOUNT_2_LOW_RESERVE =
        -2, // would create an account below the min reserve
};

union CreateAccount2Result switch (CreateAccount2ResultCode code)
{
case CREATE_ACCOUNT_2_SUCCESS:
    void;
default:
    void;
};
```

## Alternatives

* Allowing transactions with flexible sequence numbers (as suggested in some of the comments on #88) would also allow users to presign transactions from not-yet-existing accounts, solving most of the problems addressed by this change. (Limiting this feature to preauthorized transactions would _not_ be sufficient; it would have to work with presigned transactions as well.) As noted in that issue, that change might cause some issues with replayability and malleability.
* The initial sequence number could be the initial sequence number on the source account. 0 seems simpler (and easier to work with than 64-bit numbers), but it might potentially conflict with an alternative meaning for 0 sequence numbers, such as the one proposed in #88 (although that one could be adapted to use -1 or MIN_INT64 instead).
* We could exclude the optional `salt` argument entirely. This would slightly simplify the operation, but would prevent a user from creating multiple accounts with the same master key in the same transaction, which allows for a minor optimization to Lightning.

## Compatibility

* Explorers would need to change any hard-coded dependencies on accounts having a "G" prefix.
* Wallet compatibility with deterministic accounts would be desirable eventually but would not be a priority, because at first, these accounts would primarily be used as part of some special protocol like Lightning, rather than as accounts for ordinary users.

**Comment by bartekn** [comment]
I think it will be useful in other projects as well. Ex. in [Bifrost](https://github.com/stellar/go/tree/master/services/bifrost), when you need to create and configure account's trustlines before confirming if BTC/ETH transaction succeeded to make the process faster but also prevent from stealing a starting balance by users.

My idea to solve this specific scenario was to change `create_account` operation so that you can atomically change the master signer of this account (ex. by adding `signer` to this operation params). Then when account is created another key can configure the account and finally change the master key back to account ID when everything succeeds.

What I think that could be simplified is calculating the account ID of the new account. First of all, if you create multiple accounts like this in the single transactions using:
```
0x18 ++ sha256(masterKey, sourceAccountId, sourceAccountSequenceNumber, salt) ++ checksum
```
with the same `salt` (let's say `0`) it will create the same account (because `sourceAccountSequenceNumber` does not change within a single tx). Why not just:
```
0x18 ++ random bytes ++ checksum
```
and define master key of that account in operation struct:
```
struct CreateAccount2Op
{
    uint256 accountID; // Crypto random bytes str-key encoded to `D...` form
    uint256 masterKey; // ED25519 public key
    int64 startingBalance;
};
```
This is very similar to the idea from the beginning of this comment but seems to be more flexible.

> These accounts are also impossible to resurrect if deleted, since the creating account's sequence number will never go down. This makes them safe from any kind of replaying.

This is one thing that will not work in my solution without other changes (like disallowing account-merge for these accounts).

**Comment by bartekn** [comment]
OK, I forgot someone (ex. stellar-core node admin) can see txs before applying them to the ledger. Makes total sense.

**Comment by MonsieurNicolas** [comment]
This might work, but it may not be as simple as what you are describing here.

At the XDR level, `AccountID` is defined like this:
```c++

union PublicKey switch (PublicKeyType type)
{
case PUBLIC_KEY_TYPE_ED25519:
    uint256 ed25519;
};

// (...)

typedef PublicKey AccountID;
```

So really we need to add a new `PublicKeyType`, which will require all SDKs to be updated to support it.

This also brings up the question of signature verification: which key would be used to verify transactions made with such an account?

Would "masterkey" be added automatically as signer?
In the context of multi-party protocols, I imagine that this is not good enough as typically shared accounts are setup with some form of multi sig (ie, the "masterkey" of the account is disabled as its key is either shared or only known to a subset of the participants)?

**Comment by robdenison** [comment]
Revisiting this issue since I think it might have significant benefits for not just HTLCs but also payment channels (since it allows you to create ratchet accounts lazily, which ultimately allows channels where only one party has to lock up Lumens upfront, among other potential benefits).

> So really we need to add a new PublicKeyType, which will require all SDKs to be updated to support it.

Ah, this is unfortunate, particularly because this new ID type would never be used in other contexts where a public key is used (such as a signer or node), just as an account ID. Really `AccountID` should be a union type too...

I'm not especially familiar with XDR, but I wonder if it would be possible to do some type punning here to preserve the ability to parse the old data structures. Could you redefine `AccountID` as follows:

```
enum AccountIDType
{
    ACCOUNT_ID_TYPE_ED25519 = 0
};

union AccountID switch (AccountIDType type)
{
case ACCOUNT_ID_TYPE_ED25519:
    uint256 ed25519;
}
```

That should be able to correctly interpret the old data structures, right? (Although the validation logic would have to change a little.)

Then you could add a new AccountIDType like "ACCOUNT_ID_TYPE_DETERMINISTIC." It would still require an SDK update, but at least the change would only touch account IDs and not all public keys. (Unfortunately this would mean that you would need to add a new account ID type for each new public key type that you wanted to allow in account IDs.)

> This also brings up the question of signature verification: which key would be used to verify transactions made with such an account?
>
> Would "masterkey" be added automatically as signer?
> In the context of multi-party protocols, I imagine that this is not good enough as typically shared accounts are setup with some form of multi sig (ie, the "masterkey" of the account is disabled as its key is either shared or only known to a subset of the participants)?

I think adding "masterkey" as the sole initial signer on the account should be OK. I expect that in the vast majority of cases (or at least, in the cases necessary for payment channels and HTLCs), protocols should be able to set custom initial signing conditions by having the transaction that creates the account also set its permissions using `SetOptions`.

**Comment by JeremyRubin** [comment]
I think this is something we should revisit and get together a formal proposal for inclusion. I think I can eliminate concerns of backwards compatibility entirely. If that is the only concern for deterministic accounts, then we should standardize on something like below:

Deterministic accounts are a critical infrastructure piece for building reliable contracts for three key reasons:

1) Predictable sequence numbers
2) Never-fail creation
3) Known initialized state


Correct me if I'm wrong here, but I think if you define the deterministic key to be a stealth-key generation with the nonce being the hash you discussed above. This is then both deterministic and a signable key. No one can re-create this key via another create account because of the different prefix, and signatures can't be duplicated to the other account because of the prefix being signed as well. n.b. This does mean there could be two accounts that differ only by prefix! @MonsieurNicolas can you verify?

Inside the Hash, I think we may want to specify a couple different standards for different use cases. I've excluded Master Key, assuming that the above stealth derivation works on our signature scheme.

- sourceAccountId
- sourceAccountSequenceNumber
- operation-index (this serves as a salt)
- transaction hash
- initial state
- .... etc

I propose that the fields included should be specified by a bitvector in the operation to allow maximum flexibility -- the bitvector can be comitted to as well, which effectively namespaces the keys should poor parameters be picked (e.g., no sourceAccountId). We probably want to explicitly whitelist the allowed vector combinations, but this makes future upgrades easier to roll out.

Furthermore, I propose that we should have some initialization feature to add records to the account immediately without requiring a signature from the account (adding keys, setting sequence, etc).

I would like to add the semantic that at SEQUENCE_MAX, a deterministic account's only signer is dropped to the parent account. We can tightly encode this by providing a key-derivation proof with the deterministic salt we generated that includes the source account (perhaps serialize source into the hash last to make this tighter). The purpose of this functionality, with bump sequence, is to allow a deterministic account to perform only a predefined number of steps (ie, Bump to SEQMAX - n) . Probably easiest to just add this as a part of the initialization.

```xdr
struct CreateAccount2Flags : uint64_t {
  bool sourceAccount : 1;
  bool sourceAccountSequenceNumber :1;
  bool operation_index :1;
  bool transaction_hash: 1;
  bool starting_data :1; // perhaps broken down by field into different categories. if tx hash is set, must be set 
  // ... reserved for future data...
}
struct CreateAccount2StartingState {
    SequenceNumber sequence;
    Signer signers<20>;
    Thresholds thresholds;
    uint32 startingFlags;
}
struct CreateAccount2Op
{
    SignerKey keyToDeriveFrom;
    CreateAccount2Flags flags;
    int64 startingBalance;
    CreateAccount2StartingState startingState;

};


```

Missing features
----

I'd also like to have a way to initialize trust-lines on deterministic creation, but that may be more controversial. 

I also think it could be useful to specify some way to be deterministic derived from multiple accounts states (e.g., sequences from a couple different accounts). This would allow compiling rather complicated programs! However, this seems more complicated to get right and is emulable with the above primitive already to an extent.

**Comment by robdenison** [comment]
> Correct me if I'm wrong here, but I think if you define the deterministic key to be a stealth-key generation with the nonce being the hash you discussed above. This is then both deterministic and a signable key. No one can re-create this key via another create account because of the different prefix, and signatures can't be duplicated to the other account because of the prefix being signed as well. n.b. This does mean there could be two accounts that differ only by prefix! @MonsieurNicolas can you verify?

If you already have a new prefix on the account ID, I'm not sure there's any reason—at least, not any XDR-related reason—to require that the account ID include a public key instead of a hash.

Could you describe the exact key-derivation algorithm you'd use to go from the `keyToDeriveFrom` to the new master key for the account? Are you sure it guarantees no collisions?

However you derive it, one problem is that the secret key for this new key would not be a valid Stellar secret (because of the way Ed25519 secret seeds work), and you'd have to write new code to derive the Stellar public key from it, or to generate signatures from it. Generally I'm reluctant to hardcode any cryptography more complicated than ed25519 signatures and sha256 into the protocol unless absolutely necessary.

> Inside the Hash, I think we may want to specify a couple different standards for different use cases. I've excluded Master Key, assuming that the above stealth derivation works on our signature scheme.

> I propose that the fields included should be specified by a bitvector in the operation to allow maximum flexibility -- the bitvector can be comitted to as well, which effectively namespaces the keys should poor parameters be picked (e.g., no sourceAccountId). We probably want to explicitly whitelist the allowed vector combinations, but this makes future upgrades easier to roll out.

I think this adds more complexity than it is worth—is there anything this lets you accomplish that you can't do using the options I described above? I'm open to it, though.

> Furthermore, I propose that we should have some initialization feature to add records to the account immediately without requiring a signature from the account (adding keys, setting sequence, etc).

I don't really see the harm in just doing this using `setOptions` in the transaction that creates the account. At worst you can use a public key for which the private key is well-known, so either party knows they can generate the signature for it. This avoids having to duplicate all the `setOptions` logic in this operation.

> I would like to add the semantic that at SEQUENCE_MAX, a deterministic account's only signer is dropped to the parent account. We can tightly encode this by providing a key-derivation proof with the deterministic salt we generated that includes the source account (perhaps serialize source into the hash last to make this tighter). The purpose of this functionality, with bump sequence, is to allow a deterministic account to perform only a predefined number of steps (ie, Bump to SEQMAX - n) . Probably easiest to just add this as a part of the initialization.

I don't see the use for this—it doesn't even seem like it would save much trouble even when it's what we want to do, and reverting to the parent account seems like a strange default that could bite people. This would also require setting a different kind of SEQUENCE_MAX to apply to these kinds of accounts than to other accounts, which we may not otherwise need to do.

> I'd also like to have a way to initialize trust-lines on deterministic creation, but that may be more controversial.

You could just do it in the same transaction that created the account; that should cover most cases.

> I also think it could be useful to specify some way to be deterministic derived from multiple accounts states (e.g., sequences from a couple different accounts). This would allow compiling rather complicated programs! However, this seems more complicated to get right and is emulable with the above primitive already to an extent.

Yeah—you can probably mostly emulate this using multiple intermediate accounts.

**Comment by MonsieurNicolas** [comment]
Interesting idea in [CAP-0007 proposal](https://github.com/stellar/stellar-protocol/pull/203) to add placeholders.

If we do this, we probably want to differentiate `AccountID` used in Ledger Entries and `AccountID` used in transactions as placeholders are not valid in the context of ledger entries.

[CAP-0008](https://github.com/stellar/stellar-protocol/pull/209) seems to  also introduce a (third ) `AccountID` type, different from the one that can be used in operations and ledger entries.

**Comment by JeremyRubin** [comment]
The proposal does differentiate I think -- they have a different enum tag in the accountid (I changed the accountid to be an enum)

**Comment by MonsieurNicolas** [comment]
OK, so I played around with the XDR and the cleanest thing I can come up with is https://github.com/MonsieurNicolas/stellar-core/commits/cap007-xdr which enforces where we can use the relative extensions.

This helped me think more about implementation and impact on other parts of the ecosystem:
* the implementation is going to be a bit messy in core
   * the validation rules are very ad-hoc
   * in the actual implementation it's also all over the place and quite ad-hoc
* on the consuming side, those relative IDs smell abstraction break and require to be computed in clients that want to understand what transactions are actually doing (hard to understand what transactions are actually doing).

As we're reopening the can-o-worms of changing the envelope format and potentially having chained transactions that go into the same ledger - there might be better ways to think about this that make it a bit easier to reason about across the board and most importantly move certain responsibilities outside of the core protocol.

For example (I am not saying this is the way, just that there are ways to do it), if we were to adopt something closer to bitcoin masking semantics, we could have a pair of transactions, one that is similar to what is described in cap007 (only modeled as opaque binary in the transaction), and the "paired" transaction (that looks like today's transactions), that matches that other transaction. When then end up with both the proof of execution of the pattern and the low level transaction (that can easily be looked up and analyzed). With those semantics, we shift the burden of generating unique IDs outside of the protocol, and more importantly keep a better separation between layers and (also important) keep the door open to more powerful changes that won't require something entirely different.

We can use the same mechanism for transferring fees (in fact we can have as semantics have the new transaction be the one that pays for both regardless), and in the future overriding amounts or adding new conditions (general purpose parametrized transactions).

**Comment by theaeolianmachine** [comment]
@robdenison there are a few other proposals on deterministic accounts right now. [CAP-0012](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0012.md), [CAP-0007](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0007.md), etc. Do any of these feel they settle your criteria presented in your CAP?

If not, would you mind submitting your proposal separately as a PR, following the process in readme/core.md?
